### ISSUE TITLE
mbedtls_ssl_read will endless loop

### ISSUE THREAD

**Issue by DragonQuestHero** [ARMmbed/mbedtls#1162]
Version:mbedtls-2.6.1
OS:windows 10
Compiler:VS2015 Pro
use programs/ssl/ssl_client1.c
the programe will endless loop in mbedtls_ssl_read
every mbedtls_ssl_read return value is the same,buff too
Problem recurrence:
change programs/ssl/ssl_client1.c line:65 66 67
#define SERVER_PORT "443"
#define SERVER_NAME "202.228.139.213"
#define GET_REQUEST "GET / HTTP/1.1\r\n\r\n"
build and run.the problem will be reproduced
thank you guys

**Comment by RonEld** [comment]
Hi @DragonQuestHero 
Please note that the sample application is a reference program tested with HTTP 1.0 with the ssl_server program( it was run with other servers as well)
Note the endless loop is when the server infinitely sends:
~~~
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
~~~
This message is after the TLS handshake has successfully finished, and it seems that the HTTP message sent in the sample application does not fit the HTTP 1.1
At the moment, I don't consider this a bug, as it is due to HTTP protocol implementation on the sample application.
Please update if you see it otherwise

**Comment by RonEld** [comment]
In addition, quoting [stack overflow](https://stackoverflow.com/questions/6686261/what-at-the-bare-minimum-is-required-for-an-http-request):
>in HTTP/1.1, the Host: header is compulsory in addition to the above.
Omitting the Host: header in HTTP/1.1 is the most common cause of 400 errors.

I would recommend you add the Host: yo your HTTP 1.1 GET request
Since I don't know what is the domain name of your server, I couldn't test it myself

**Comment by RonEld** [comment]
AS for the infinite loop, it is because `mbedtls_ssl_read` doesn't return  EOF / 0 bytes read. AS long as there is data in the socket, the application will print it. I have tested on linux as well, and the loop happens there. In addition, I have tested with a different server (www.server.com), and no loop. I believe that the error is with the server continuing to send the message.

**Comment by DragonQuestHero** [comment]
you are right!
i ues Wireshark packetcapture.just as you say.the server send message loop
actually,this sever not mine...
most of the time my programe is work...just something...or sometime...not work
Perhaps because the weather is not good....
thank all guys.and sorry my english
