### ISSUE TITLE
A question about DTLS handshake failed.(DTLS work in STM32)

### ISSUE THREAD

**Issue by Supowang** [ARMmbed/mbedtls#1202]
- Type: Question
- Priority:  Minor

   I'm trying to make DTLS work in STM32F429，I've been using  dtls_client.c as my template，let this demo run on STM32F429 as client, and also I've been using dtls_server.c as my template,let this demo run on vs2010 as server. 
   when my stm32F429 try to handshake with the server, stm32 send the Encrypted Handshake Message,then the server send a Alert message and close the connection;
 When I check the server log, I find that the function mbedtls_cipher_auth_decrypt() returned (-0x6300), then send alert message, at the end ,server notes that handshake failed, Verification of the message MAC failed.
  I  can not find the reason, Can anyone help me explain this for what reason or tell me how to solve the problem，I am greatly appreciated！

Thanks a lot！ 
supowang

**Comment by RonEld** [comment]
Hi @Supowang The error you are receiving is `MBEDTLS_ERR_CIPHER_AUTH_FAILED`. It means that authenticating the message failed, beause the generated MAC is different than the one in the message. It usually happens when the key or IV are different in both peers. You could look at [this post](MBEDTLS_ERR_SSL_INVALID_MAC) for more information. It is most likely that the IVs are the same, as they are same, so I believe that the generated key material on both sides is different. It could be a memory issue. It could also be that the hashed message is different, as mentioned in the link I referenced.

**Comment by Supowang** [comment]
@RonEld  thanks a lot , you are so kind. I hava solve this problem by using psk instead of ca.
