### ISSUE TITLE
crypt_and_hash program fails  when used with "AES-XXX-ECB"

### ISSUE THREAD

**Issue by rahmanih** [ARMmbed/mbedtls#1211]
Hi,

When running `crypt_and_hash` program as below
`$>./crypt_and_hash 0 /tmp/foo.txt /tmp/foo.txt.enc "AES-192-ECB" MD5 hex:AB5412CC7856A00B101`
the following error is shown.
`mbedtls_cipher_update() returned error`
the function `mbedtls_cipher_update()` fails with _**MBEDTLS_ERR_CIPHER_FULL_BLOCK_EXPECTED**_

Note:
all the "AES_XXX_ECB" algos fail with the same error.

regards
Haithem.

**Comment by RonEld** [comment]
Hi @rahmanih Thank you for your query.
As you may know, AES requires input which is a multiple of 16 bytes ( size of AES block ). in addition, Mbed TLS Aes ECB API acepts input of only 16 bytes:
~~~

int mbedtls_aes_crypt_ecb( mbedtls_aes_context *ctx,
                    int mode,
                    const unsigned char input[16],
                    unsigned char output[16] );
~~~
Since ciphering more than 16 byte in ECB mode is not considered secure
The error you are receiving is a valid error.

**Comment by RonEld** [comment]
Closing this issue as I believe the question has been answered. If you feel it was wrongfully closed, please reopen
