### ISSUE TITLE
how to use nonblock mbedtls_net_connect

### ISSUE THREAD

**Issue by DragonQuestHero** [ARMmbed/mbedtls#1226]
i try to use mbedtls_net_set_nonblock
mbedtls_ssl_read and mbedtls_ssl_write is nonblock
but mbedtls_net_set_nonblock not change
so.how to use nonblock connect?
thank you guys

**Comment by RonEld** [comment]
Hi @DragonQuestHero in order to use a non-blocking socket, you will need to call `mbedtls_net_set_nonblock()`
I am not sure why you think that `mbedtls_ssl_read()` and `mbedtls_ssl_write()` are nonblocking, if you haven't set the socket to be nonblocking.

**Comment by DragonQuestHero** [comment]
ok...sorry my english
I use mbedtls_net_set_nonblock() After mbedtls_ssl_read() and mbedtls_ssl_write() will is nonblocking.return MBEDTLS_ERR_SSL_WANT_READ or MBEDTLS_ERR_SSL_WANT_WRITE
but mbedtls_net_set_nonblock() still block.just return YES or ERROR
thanks.

**Comment by DragonQuestHero** [comment]
I just want use non-blocking connect
return YES or ERROR or connecting.look like nonblock read() and write()

**Comment by RonEld** [comment]
Hi @DragonQuestHero thank you for your clarifications. Yes, the `mbedtls_net_connect()` sample code supplied with the Mbed TLS library is using a blocking connect. In order to do a non blocking connect, you will need to have your own network implementation( pretty much a copy of the current `net_sockets.c`), setting your own `bio` callbacks. For `mbedtls_net_connect()`, you will need to create a non blocking socket, and then use `connect` and `select` to have the timed connect.
Another option, is to have the default reference implementation of `net_sockets.c` (assuming your platform supports it), and you will need to create the socket, set it to non blocking, call `connect` and then `select` in your own proprietary function
