### ISSUE TITLE
'mbedtls_x509_crl_parse' free  null pointer

### ISSUE THREAD

**Issue by niuys** [ARMmbed/mbedtls#1255]
### Description
- Type: Bug | Question
- Priority: Major

---------------------------------------------------------------
## Bug
In 'mbedtls_x509_crl_parse', if ret is not 0, 'mbedtls_pem_free' may free a null pointer.

**Comment by deleisha** [comment]
man 3 free states that
If ptr is NULL, no operation is performed.

**Comment by deleisha** [comment]
As `mbedtls_free` is expanded to `free`, It should be safe. man 3 free states that freeing a NULL pointer does not do anything.
On platform where mbedtls_free is not free, we need to check

**Comment by RonEld** [comment]
Hi @niuys I would like to second @deleisha statement about `free` is allowed to get NULL pointer.
In fact, quoting the [C standard](http://www.open-std.org/JTC1/SC22/wg14/www/docs/n1124.pdf)(p.313):
>The free function causes the space pointed to by ptr to be deallocated, that is, made
available for further allocation. If ptr is a null pointer, no action occurs.

This implies that it is perfectly OK not to check for `NULL` before freeing it, infact, it adds additional redundant code.  
You can see in most of the code, there aren't checks for pointer being null, before calling `mbedtls_free`.

As @deleisha rightfully stated, if someone implements `mbedtls_free()` otherwise, then the `NULL` check should be there.

**Comment by niuys** [comment]
You are right, I found other discussions about this on stackoverflow too. In fact, my platform didn't  obey the standard.Maybe it's better to refactor the code to be more clear.
