### ISSUE TITLE
No record_overflow alert

### ISSUE THREAD

**Issue by EMH-MHA** [ARMmbed/mbedtls#1282]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug
https://github.com/ARMmbed/mbedtls/blob/297d7535fb7f325507a4c35104f11000c613bbc4/library/ssl_tls.c#L3521-L3527
Upon receipt of a message exceeding the SSL buffer size, mbedTLS returns to the user with `MBEDTLS_ERR_SSL_INVALID_RECORD`.

RFC 5246 (ch. 7.2.2) mandates that
```
Whenever an implementation encounters a condition which is defined as
 a fatal alert, it MUST send the appropriate alert prior to closing the connection.
```

Shouldn't mbedTLS send the `record_overflow(22)` fatal alert in this case?

Since the generic error code `MBEDTLS_ERR_SSL_INVALID_RECORD` is returned, even the user has no chance of distinguishing this error from, say, a version mismatch and sending the correct alert message.

**Comment by RonEld** [comment]
Hi @EMH-MHA thank you for reporting this.
According to [RFC5246](https://tools.ietf.org/html/rfc5246), `record_overflow` should be sent with:
> A TLSCiphertext record was received that had a length more than
      2^14+2048 bytes, or a record decrypted to a TLSCompressed record
      with more than 2^14+1024 bytes.  This message is always fatal and
      should never be observed in communication between proper
      implementations (except when messages were corrupted in the
      network).

The issue you are describing does not fit the description of the fatal alert. The error might be because of configuration error, which the message received is larger than the input buffer size. You may be correct that the error might not be informative enough.  
Nonetheless, we will look into this deeper.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2045
