### ISSUE TITLE
Report of potential vulnerable code components that could potentially leak RSA private key in mbedTLS 2.5.1

### ISSUE THREAD

**Issue by computereasy** [ARMmbed/mbedtls#1332]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Blocker | Major | Minor

---------------------------------------------------------------
## Bug

**OS**  
linux|

**mbed TLS build:**  
Version: 2.5.1
OS version: Ubuntu 16.04

Dear mbedTLS Developers,

We are some security researchers and we are working on some research projects to detect cache-based side channel vulnerabilities that could leak program secrets. Our current finding shows that in mbedTLS (version 2.5.1), function **mbedtls_mpi_exp_mod** (from library​/bignum.c) may lead to potential cache line access-based side channel issues, and we are writing to confirm that.

To elaborate, function **mbedtls_mpi_exp_mod** uses a precomputed table to store computation results of exponentiation. Variable "wbits" is a window size of the program secret, and it is used to query the precomputed table at line 1767 of **library/bignum.c**:

           MBEDTLS_MPI_CHK( mpi_montmul( X, &W[wbits], N, mm, &T ) );

While there is no direct secret-dependent memory access, later in function **mpi_montmul**, we have identified four memory access via variable **B** (which is from **&W[wbits]**) that can lead to the access of different cache lines, given different secrets in **wbits**. In other words, by observing the access of different cache line, in each iteration of the modular exportation loop in function **mbedtls_mpi_exp_mod**, attacker could be able to infer certain bits in **wbits**, hence potentially recovering the whole RSA private key.

I paste the related code components and highlight program variables which could store program secrets as well as four potentially vulnerable program memory accesses (note that those five memory accesses are compiled into four memory loading operations):

    int mbedtls_mpi_exp_mod( mbedtls_mpi *X, const mbedtls_mpi *A, const mbedtls_mpi *E, const mbedtls_mpi *N, mbedtls_mpi *_RR )
    {    
      while( 1 )
      {
        ei = (E->p[nblimbs] >> bufsize) & 1;              <------------  ei holds bits of secrets
        ...
        wbits |= ( **ei** << ( wsize - nbits ) );           <------------ wbits is a window-size of secrets
        ...
        MBEDTLS_MPI_CHK( mpi_montmul( X, &W[wbits], N, mm, &T ) );       <------- W[wbits]
        ...
       }
    }

    static int mpi_montmul( mbedtls_mpi *A, const mbedtls_mpi *B, const mbedtls_mpi *N, mbedtls_mpi_uint mm,
                     const mbedtls_mpi *T )
    {
       m = ( B->n < n ) ? B->n : n;         <------------  first two vulnerable mem access at B->n
       ...
       u1 = ( d[0] + u0 * B->p[0] ) * mm;     <------------ third vulnerable mem access at B->p[0]

       mpi_mul_hlp( m, B->p, d, u0 );           <------------ last vulnerable mem access at B->p
       ...
    }

Our verification in a hardware simulator (gem5) shows that by modifying the secret array entries with different values (e.g., modify the 13th entry of **E->p** with 0x40000000 vs. 0xc0000002​), all the four highlighted memory access would access different cache lines. In addition, the cache state of the third memory access is different as well ("hit" by assigning secret as 0x40000000 while the other is "miss" with 0xc0000002). 

Besides mbedTLS version 2.5.1, this function exists in old and the newest versions as well, such as lastest version on the github.

Please let us know if it makes sense to you. Thank you in advance and have a good day!

**Comment by sbutcher-arm** [comment]
Thanks for raising this with us! We'll look into it immediately.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2082

**Comment by yanesca** [comment]
Dear @computereasy, thank you very much for your bug report! Version 2.5.1 comes with an RSA exponent blinding as a countermeasure against attacks like this. The countermeasure has been released in Mbed TLS 2.5.0 and all subsequent versions (and corresponding backport versions 2.1.8 and 1.3.20 and later) are protected. If we missed something and RSA exponent blinding doesn't protect against your attack, then please let us know!

**Comment by yanesca** [comment]
Thank you for your interest in Mbed TLS!

You are absolutely right! No countermeasure can protect agains all side channel attacks and side channel attacks like all attacks are only getting better and more dangerous over time. The measurements are getting better, the statistical techniques to extract information are getting better too. However while the adversary is not able to extract the key from a single trace, blinding does protect against the attack. 
                                                                                
Regarding the attacks you mentioned, there is another blinding countermeasure in Mbed TLS since version Polar SSL 1.3.0 that protects against them. The exponent blinding I was referring to is there to protect against a more recent class of side channel attacks (see for example [Schwartz et al](https://arxiv.org/pdf/1702.08719v2.pdf) and [Inci et al](https://eprint.iacr.org/2016/596.pdf)). 
                                                                                
I mentioned the exponent blinding in my previous post, because this current issue is about memory accesses depending on bits of the exponent.

**Comment by yanesca** [comment]
@computereasy 

I agree, exponent blinding is not a panacea, it does not make all side channels go away. For example the [Schindler paper](https://eprint.iacr.org/2014/869.pdf) you mention describes an attack that works if exponent blinding is the only countermeasure in the implementation. One of the mitigations he mentions is base blinding alongside exponent blinding and as I mentioned before, that is exactly what we have in Mbed TLS.

Inferring the secrets from the access variants is not harder at all, a single access variant is sufficient to derive the secret key. What blinding makes harder is to get the access pattern. The attacker infers the access patterns based on measurements. The measurements are usually relatively noisy. The noise can introduce errors in the inferred key. This can be deleting, inserting or flipping a bit and the attacker does not know at which positions these errors are. Even if he managed to recover the majority of the key bits correctly, recovering the rest with exhaustive search can be still infeasible. Therefore the attacker needs to make additional measurements and combine them. With exponent blinding this is not an option, because the new measurements will correspond to a completely different value and thus prevents the attack. On the other hand if the attacker can derive the exponent from a single trace, this countermeasure does not make any difference.

Does that make sense?

**Comment by yanesca** [comment]
Hi @kouzili77,

It was my pleasure! :)

The reason is that the blinded exponent can decrypt or sign just as well as the original exponent can, this is why blinding works in the first place. If a single trace is enough to recover the blinded exponent, then the adversary already has an information equivalent to the private key.

If the blinding is longer, but the resulting exponent can be still recovered in a single trace then blinding does not help.

That said, making the blinding coefficient longer requires more data points/longer measurements to attack and depending on the type of the attack this might increase the noise, making single trace recovery harder to achieve. This impact depends strongly on the actual specific side channel and measurement/attack methodology used and it is really hard to argue for it in general.

Does that help?

**Comment by kouzili77** [comment]
@yanesca You are so nice to reply promptly! 

Your words make me realize my misunderstanding~ The blinded exponent d+r(p-1)(q-1) generates the same plaintext as d, so in the real scenario, a single trace attacker can just use the blinded key, however, the funny thing I was thinking is that the attacker must retrieve the d itself. I totally understand your clear and straightforward explanations about the method, goal, and security level of exponent blinding, they are helpful, thx!

Currently, I have a possibly limited knowledge in mathematic that I'm not sure whether it is easy or computational feasible for a single trace attacker to recover the value of d (considering the r has the same length with d). Anyway, feel free to ignore my puzzle~

**Comment by yanesca** [comment]
I am happy that it helped! :)

It is possible (, although I suspect that someone more skilled in mathematic could come up with something more elegant than this): e(d+r(p-1)(q-1))-1=s(p-1)(q-1) for some integer s. In an average case (p-1)(q-1) has small prime factors and factorisation is computationally feasible. Once the factorisation is complete test all combinations of the prime factors to find (p-1)(q-1). (If x is the smallest combination for which a^x = 1 mod N, where (a,N)=1, then x=(p-1)(q-1).) After this we can use e to compute d exactly like during key generation.
