### ISSUE TITLE
error loglevel (1)  floods with non-errors in case of nonblocking IO

### ISSUE THREAD

**Issue by harmv** [ARMmbed/mbedtls#136]
polarssl comes with neat error/debug messages.
I prefer to have debug_set_threshold( 1 );  so that you see errors.

Unfortunately, when using non blocking IO, lots of level 1 messages are triggered that are not actually errors at all, they are just informative would_block() notification to the callers of ssl_read()/ssl_write(). 

This basically renders the level 1 useless (less usefull).

This is caused because in several places every retval != 0 is considered an error, while the bio routines net.c::net_recv()/net_send()  return return POLARSSL_ERR_NET_WANT_READ, POLARSSL_ERR_NET_WANT_WRITE to indicate there is no data right now.

below a typical snippet of a logging flood, while actual communication runs just fine. (no errors)

    polarssl/library/ssl_tls.c(2047): ssl_fetch_input() returned -82 (-0x0052)
    polarssl/library/ssl_cli.c(0899): ssl_read_record() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2047): ssl_fetch_input() returned -82 (-0x0052)
    polarssl/library/ssl_cli.c(0899): ssl_read_record() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2047): ssl_fetch_input() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2740): ssl_read_record() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2047): ssl_fetch_input() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2740): ssl_read_record() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2047): ssl_fetch_input() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2740): ssl_read_record() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2047): ssl_fetch_input() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2740): ssl_read_record() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2047): ssl_fetch_input() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(4306): ssl_read_record() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(2047): ssl_fetch_input() returned -82 (-0x0052)
    polarssl/library/ssl_tls.c(4306): ssl_read_record() returned -82 (-0x0052)

### expected behaviour
I'd expect something like this.

retval not in [ POLARSSL_ERR_NET_WANT_WRITE, POLARSSL_ERR_NET_WANT_READ]  -> reported at level 1
retval in [POLARSSL_ERR_NET_WANT_WRITE, POLARSSL_ERR_NET_WANT_READ]  reported at level 3 or 4.

**Comment by mpg** [comment]
Solved in the internal development branch for the upcoming 2.0: `debug_print_ret()` now silently returns in the return code is WANT_READ. It still prints WANT_WRITE though, since it is likely to be more rare, and could be associated with subtle bugs in the application (it once was associated with a nasty bug in our code, before we had automated tests with non-blocking I/O), so you probably want to know about it when it happens.

I didn't touch it in the 1.3 branch, however it is easy to fix by hand: just add `#include "polarssl/net.h"` in `debug.c` and then `if( ret == POLARSSL_ERR_NET_WANT_WRITE ) return;` at the start of `debug_print_ret()`.

Note that this doesn't prevent flooding at higher debug levels, due to message each time a function like `ssl_read()` is entered. It still reduces the amount of junk. The only real solution to avoid flooding then is to sleep before retrying, or better yet, use `select()` or similar to retry only when data is ready to be read. (The examples in `programs/ssl` could probably be improved by demonstrating that.)
