### ISSUE TITLE
use ssl_server.c to excuate a ssl_server.exe, and connect it, but failed

### ISSUE THREAD

**Issue by longsungnewman** [ARMmbed/mbedtls#1429]
AT+LSHTTPURL=100,20
>https://113.140.31.150:61369+++
OK
AT+LSHTTPGET
+QHTTPGET:response timeout

ERROR
****

**Comment by sbutcher-arm** [comment]
Thanks for the feedback. Unfortunately, I'm not sure how to interpret the log you've provided. Were you running this on Windows? I guess so because you say `ssl_server.exe`. And if so, do you know if the firewall was properly configured to allow the test applications to connect to each other? This is a common problem on Windows.

**Comment by RonEld** [comment]
Closing this query, as no followup
