### ISSUE TITLE
X509 certificate verification problem

### ISSUE THREAD

**Issue by JanZimmer** [ARMmbed/mbedtls#1492]
Hey guys,
during investigation of the certificate verification logic, I came up with an issue regarding the comparison of the top certificate of the chain with the trusted CA certificates.
In [1] and [2], the memcmp is done as follows:
`memcmp( child->subject_raw.p, trust_ca->subject_raw.p, child->issuer_raw.len )`

However, I think this should be done with `child->subject_raw.len`.
Otherwise, someone with a crafted certificate at the top of the chain, might be able to either make at least one byte out-of-bound access through an longer issuer than the subject by tricking memcmp into comparing more than subject_raw.len bytes, or might be able to trick the memcmp into comparing less than the wanted number of bytes by using a shorter issuer than the subject.

I did not try to verify if this is indeed possible, but I think, it should be fixed anyway.

Best regards,
Jan

[1] https://github.com/ARMmbed/mbedtls/blob/f3ada4adb00723a540a77de88a2831313b443190/library/x509_crt.c#L2006

[2] https://github.com/ARMmbed/mbedtls/blob/f3ada4adb00723a540a77de88a2831313b443190/library/x509_crt.c#L1956

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2197

**Comment by mpg** [comment]
Hi @JanZimmer and thanks for your report!

We agree this is a bug and a potential security issue, however we think this is the same issue that was reported as https://github.com/ARMmbed/mbedtls/issues/825 and that a fix has been merged in all of our maintained branches this morning.

Therefore I'm closing this issue, but feel free to double-check and re-open if you think any part of this issues remains in the current 'development', 'mbedtls-2.7' or 'mbedtls-2.1' branches.

**Comment by JanZimmer** [comment]
Hi,

I'm wondering that the issue was fixed around 6 months ago [1] but is still not present in the 2.7.2 LTS patch [2] even though you call it a potential security issue.

I'm not 100% sure, if I got this right, but in the 2.7.2 tag of the 2.7 branch, the fix was not applied or was it?

[1] https://github.com/ARMmbed/mbedtls/commit/2e7fee09da8b00c58effd3f1957eece9514a8be9
[2] https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.7.2/library/x509_crt.c#L2010

**Comment by mpg** [comment]
That's a very fair question.

Potential security issues are not all equal, and this one was assessed to be relatively minor: the problematic lines can only be reached if `check_parent()` passed which means that `child->issuer` and `parent->subject` compare equal, so the only difference in length can come from the encoding of the length bytes in the ASN.1 structure, and considering the minimum length of the material that's after `subject_raw` in the buffer (at least 192 bytes assuming the CA uses ECC with a 256-bit curve, more for larger curves or RSA keys), we concluded that the buffer overread can only be triggered if a trusted CA has more than 12 components it its name (something that's not under the control of the attacker, and relatively unlikely: the maximum over CAs trusted by Mozilla is 10, for example). Also, the potential impact is relatively minor: this buffer overread will result in at most an application crash (DoS), there are no opportunities for data leaks here.

So, while we acknowledge this is a potential security issue, it only occurs under relatively rare circumstances and with limited impact. Had the issue been more severe, we would have made it a higher priority and fixed it more quickly.

However, we agree 6 month is still a long time, and way longer than the time we original planned for merging and releasing the fix. We're analysing the reasons why this happened, so that we can do better in the future.

**Comment by mpg** [comment]
Note: yesterday I wrote I was closing this issue, but apparently clicked the wrong button.
