### ISSUE TITLE
Strange soversion bump in mbed TLS 2.7.0 vs. 2.7.2 vs. 2.8.0

### ISSUE THREAD

**Issue by robert-scheck** [ARMmbed/mbedtls#1573]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.7.0, 2.7.2, 2.8.0
OS version: RHEL/CentOS 6 and 7
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): https://koji.fedoraproject.org/koji/packageinfo?packageID=20366 (links to binaries and build logs)

**Expected behavior**   
mbed TLS 2.7.0 and 2.8.0 lead to:
```
/usr/lib64/libmbedcrypto.so.1
/usr/lib64/libmbedcrypto.so.2.7.0
/usr/lib64/libmbedtls.so.10
/usr/lib64/libmbedtls.so.2.7.0
/usr/lib64/libmbedx509.so.0
/usr/lib64/libmbedx509.so.2.7.0
```

```
/usr/lib64/libmbedcrypto.so.1
/usr/lib64/libmbedcrypto.so.2.8.0
/usr/lib64/libmbedtls.so.10
/usr/lib64/libmbedtls.so.2.8.0
/usr/lib64/libmbedx509.so.0
/usr/lib64/libmbedx509.so.2.8.0
```

**Actual behavior**  
mbed TLS 2.7.2 leads to:
```
/usr/lib64/libmbedcrypto.so.2
/usr/lib64/libmbedcrypto.so.2.7.2
/usr/lib64/libmbedtls.so.10
/usr/lib64/libmbedtls.so.2.7.2
/usr/lib64/libmbedx509.so.0
/usr/lib64/libmbedx509.so.2.7.2
```

Why was there a soversion bump from `libmbedcrypto.so.1` to `libmbedcrypto.so.2` from 2.7.0 to 2.7.2? That should not happen. I would have expected such a change from 2.7.0 to 2.8.0, but not in a minor update. Even the soversion bump is really correct in 2.7.x series, it still would mean that 2.7.0 and 2.8.0 are ABI compatible, but 2.7.2 isn't. This feels like a bug.

**Comment by sbutcher-arm** [comment]
So this was very simply a screw-up in our versioning and packaging that we didn't spot before release.

What happened, was we shipped Mbed TLS 2.7.0, but accidentally broke the API/ABI, which wasn't picked up in our testing. For the sake of Mbed OS, we then did a very quick fix to revert those interface changes, which took us to 2.7.1, and bumped the so version. Whilst that was released in Mbed OS, it was never released onto the Mbed TLS website as a standalone release. 

Moving forwards, 2.7 became a maintenance branch, inheriting the so version number of 2.7.1, leading us to 2.7.2, whilst 2.8.0 was based on 2.7.0, and missed the so version bump. 

And that's why we had the confusing and misleading version numbers.

To fix this, we've bumped the version number in our most release release 2.9.0 to match 2.7.2 and 2.7.2, all of which are API/ABI compatible, although 2.9.0 differs in available functionality.

To avoid such mistakes in the future, we're introducing API checking into our testing and CI, with PR #1433, and will be reviewing all future version changes as a PR.

I hope that answers the question! My apologies on behalf of the project for any problems this mistake may have caused.

I'm closing the issue, but please feel free to reopen or reply if you feel unsatisfied by the answer.
