### ISSUE TITLE
when out_left  != 0, ssl_write_real  just return without sending data

### ISSUE THREAD

**Issue by cstriker1407** [ARMmbed/mbedtls#1635]
- Type:  Question
- Priority: Major
---------------------------------------------------------------
## Question

Hello guys,
     When I read the source code of [ **ssl_tls.c -- ssl_write_real (Line 7225)** ]， Version 2.9.0 . 
I am confused of the managent about **out_left  != 0**
     When I want  to send  data through tls，and  ssl->out_left != 0 is true， then we will go to function mbedtls_ssl_flush_output and if this function return OK， then the total function just returns  len without calling mbedtls_ssl_write_record. I think it is a bug.
     My suggestion is the **"else" should be removed**. if there is old data left ,then send the left data first,if no errors, then send the new data. Or just **return 0** not length to notify the caller that no new data send.

remove the else
```
static int ssl_write_real( mbedtls_ssl_context *ssl,
                           const unsigned char *buf, size_t len )
{
。。。。。
    if( ssl->out_left != 0 )
    {
        mbedtls_ssl_flush_output
    }  
//    else 
//    {
        mbedtls_ssl_write_record
//    }

    return( (int) len );
}
```
return 0 
```
static int ssl_write_real( mbedtls_ssl_context *ssl,
                           const unsigned char *buf, size_t len )
{
。。。。。
    if( ssl->out_left != 0 )
    {
        mbedtls_ssl_flush_output
        return 0; // just return 0 
    }  
    else 
    {
        mbedtls_ssl_write_record
    }

    return( (int) len );
}
```

Sorry for my poor English....

Good Luck && Best Wishes~~

**Comment by hanno-arm** [comment]
Hi @cstriker1407,

thanks for studying our code and for reporting the issue!

While surprising at first, the behaviour you observed is deliberate: If `out_left != 0`, then a previous API call to`ssl_write` will have returned `WANT_WRITE`, indicating that an attempt to send data couldn't be completed because the underlying transport wasn't available, and in this case the [documentation](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h#L2623) states:

```
* \note           When this function returns MBEDTLS_ERR_SSL_WANT_WRITE/READ,
*                 it must be called later with the *same* arguments,
*                 until it returns a positive value. When the function returns
*                 MBEDTLS_ERR_SSL_WANT_WRITE there may be some partial
*                 data in the output buffer, however this is not yet sent.
```

Hence, it is invalid API usage to call `mbedtls_ssl_write` with fresh data after a previous call failed.

You are not the only one to find this behaviour unintuitive at first, though, see e.g. https://github.com/ARMmbed/mbedtls/issues/1356.

Thanks again for your report,

Kind regards,
Hanno, Mbed TLS team member

**Comment by cstriker1407** [comment]
Thanks @hanno-arm .
But  I am still confused, when the old data all send. function < mbedtls_ssl_flush_output > return 0, we think it is ok. then the function < ssl_write_real > return len, then < mbedtls_ssl_write > return len. So in the demo code < ssl_client1.c >, we call the function < mbedtls_ssl_write > in a while loop. So when the  function < mbedtls_ssl_flush_output > return 0, mbedtls_ssl_write return len but not sending any data. The caller < ssl_client1.c > just quit while, actually the data is not send. So I think the real problem is the return code of mbedtls_ssl_flush_output, when it return 0.

**Comment by RonEld** [comment]
Hi @cstriker1407 
In case this is still not clear, I'll try to clarify the answer.

`mbedtls_ssl_flush_output` is called from `ssl_write_real()` when the previous call returned `MBEDTLS_ERR_SSL_WANT_WRITE` or `MBEDTLS_ERR_SSL_WANT_READ`(because no data was sent, and we need to flush it) . In this case, you shouldn't try to send a new buffer, but the *same previous buffer*
`mbedtls_ssl_flush_output()` returns 0 on success, which means that *all the data was sent*, otherwise, it would have returned an error.
So, `mbedtls_write()` will return the number of bytes asked to be sent, or an error.

**Comment by RonEld** [comment]
We believe this question was answered, therefore closing.

If you feel there are still something unclear, please reopen, and specify what needs further explanation.
