### ISSUE TITLE
Compilation for MBEDTLS_ARC4_C disabled and MBEDTLS_CIPHER_NULL_CIPHER enabled

### ISSUE THREAD

**Issue by TrinityTonic** [ARMmbed/mbedtls#1719]
### Description
- Type: Bug 
- Priority: Minor

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.9.0 and probably older

Scenario:
Configuration file has MBEDTLS_ARC4_C disabled and MBEDTLS_CIPHER_NULL_CIPHER enabled. This will lead to a compilation error ('mbedtls_cipher_base_t' has no member named 'stream_func') coming from module cipher.c. This is because MBEDTLS_CIPHER_MODE_STREAM is enabled when MBEDTLS_CIPHER_NULL_CIPHER  is enabled, which IMO should not be implemented like this.

**Comment by RonEld** [comment]
@TrinityTonic thank you for raising this issue!
I believe `MBEDTLS_CIPHER_MODE_STREAM` *should* be defined when `MBEDTLS_CIPHER_NULL_CIPHER` is enabled, as the streram function is `null_crypt_stream()`
However, this compilation error should not happen, and this needs further investigation.
I believe the root cause is that `MBEDTLS_CIPHER_MODE_STREAM` is defined in `cipher.c`, while all the callback functions are defined in `cipher_wrap.c`, and `stream_func` is defined in `cipher_internal.h`
From brief view, I believe the `MBEDTLS_CIPHER_MODE_STREAM` definition should move to `cipher_internal.h`

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2365
