### ISSUE TITLE
mbedtls_pk_decrypt uses both public or private key to decrypt the signature?

### ISSUE THREAD

**Issue by Naveenkumar28** [ARMmbed/mbedtls#1786]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Feature Request
- Priority: Blocker 

---------------------------------------------------------------
## Why mbedtls_pk_decrypt supports only private key to decrypt the signature. What if I have private key for signing and public key for decryption ?

**OS**  
Mbed OS|windows|

**mbed TLS build:**  
Version: x.x.x or git commit id  
OS version: x.x.x  
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**   
mbedtls_pk_decrypt should uses both public or private key for decryption.
**Actual behavior**  
mbedtls_pk_decrypt uses only private key for decryption.
**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://tls.mbed.org/discussions)**

**Comment by Naveenkumar28** [comment]
My Requirement is below,

I want to decrypt the signature using the public key. The Key was extracted from certificate.

In this case, which APIs are suggested by MbedTLS. 

This is very critical and urgent now. 
Please address asap.

**Comment by RonEld** [comment]
@Naveenkumar28 You are mixing two concepts in asymmetric operations.
One is signing vs. verification.
The second is encrypting vs. decrypting.

If you sign data using private key, you *verify* it using `mbedtls_pk_verify()` with the public key.
If you encrypt data using the public key, you *decrypt* it using the private key.

Having it the other way around doesn't make sense and is not secure.
If you want to send someone encrypted data, that only they can decrypt, you encrypt it using their public key, and only they can decrypt it, using their private key. You wouldn't want to decrypt data with a public key, as it means that everyone can decrypt this sensitive data.

If you want to verify that data was sent by a specific someone, the data should have been signed by that specific person, with their private key, and you verify the signature of the data ( the data is not encrypted) with their public key.

If you want to send encrypted data and authenticate it as well, I suggest you use symmetric AEAD algorithm, such as GCM or CCM. You would consider exchanging the symmetric key using a key exchange algorithm such as DHM or ECDH.

**Comment by RonEld** [comment]
Closing this issue, as I believe it was addressed and answered.
If you believe that this deserves further action, please reopen.

**Comment by k-a-z-u** [comment]
I do not fully agree to above remarks.

If the API does not allow the public key to be used for decryption, why does it allow the private key to be used for encryption?
In terms of above security concerns, the encryption part should be the one to prevent!

Furthermore, above remarks define security as "only one instance should be able to decrypt".
That indeed is the typical use case.
But, what about a scenario, where "only one instance should be able to send/construct"?
Imagine a bunch of IoT devices which have some configuration.
Only one device should be able to change this configuration.
Yes, this is what the signature is used for. 
But IMHO, for the presented example, encryption is more suited.
Only one device uses the private key to encrypt the configuration, and sends it to the IoT devices which decrypt it using the public key.
You do not care whether the world is able to decrypt the configuration, as long as the world is unable to encrypt it.
Furthermore, you do not want the private key to be on the IoT devices, because they can be reverse engineered and so one can steal your private key.
Even password-protecting the key will not help you, as you would have to add the password to the IoT device. 
Which can again be reverse engineered.
So using two key-pairs does not make sense either.
You want the private key on a single device, e.g. Desktop PC.
You can password-protect the private key, and only the operator knows it.
No reverse engineering.
I think, in this type of scenario, using the public key for decryption is much safer, than the other way round, and outperforms just using a signature.

Therefore, the API should support both ways, and let the developer decide what fits best.

**Comment by Archie1978** [comment]
hello, I have exactly the same issue as k-a-z-u on IOTs. If I made a signed file in the memory of the IOT. With 2 memory dump, I manage to modify the signed file.
* The first dump to locate in the memory the file and modify it
* The 2nd dump to change the verification of the signature.

If I encrypt a conf (which contains a CRC) with a private key. And that all IOTs read this file with the public key. I have one advantage. If the encrypted conf file is changed, it does anything (easily searchable without the CRC). After I can get around this system, it becomes more sporty.
