### ISSUE TITLE
nist_kw: possible bug when a size argument is 0

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#1882]
According to https://github.com/ARMmbed/mbedtls/pull/1658#issuecomment-407013183 it seems that a test was failing and part of the fix involved the [following patch](https://gist.github.com/Patater/9fc367023e2ae68ccc9e94173e612724) (which has been erased from the history due to a post-review but pre-merge rebase):
```
diff --git a/tests/suites/test_suite_nist_kw.function b/tests/suites/test_suite_nist_kw.function
index 2724fbdb1..eb67c03f0 100644
--- a/tests/suites/test_suite_nist_kw.function
+++ b/tests/suites/test_suite_nist_kw.function
@@ -158,7 +158,16 @@ void nist_kw_plaintext_lengths( int in_len, int out_len, int mode, int res )
 
     memset( key, 0, sizeof( key ) );
 
-    plaintext = mbedtls_calloc( 1, in_len );
+    if (in_len == 0)
+    {
+        /* mbedtls_calloc can return NULL for zero-length buffers. Make sure we
+         * always have a plaintext buffer, even if the length is 0. */
+        plaintext = mbedtls_calloc( 1, 1 );
+    }
+    else
+    {
+        plaintext = mbedtls_calloc( 1, in_len );
+    }
     TEST_ASSERT( plaintext != NULL );
     ciphertext = mbedtls_calloc( 1, output_len );
     TEST_ASSERT( ciphertext != NULL );
```
This can't be right. `in_len == 0` and `plaintext == NULL` should be valid input. If something failed then this is a product issue, not a test issue.

**Comment by Patater** [comment]
The line `TEST_ASSERT( plaintext != NULL );` assumes that if it gets NULL, it is out of memory. This isn't actually true. So, to fix that test assertion, as the comment says, we provide a non-NULL buffer in all cases. This provides the same test coverage as before. The API under test is still reached with the same conditions.

We could change that test assertion instead to `TEST_ASSERT( in_len == 0 || plaintext != NULL)` and gain additional test coverage, by making a null `plaintext` reach the API. This was previously never done, but I agree with you would be good to do.

This issue seems more about increasing test coverage than a possible bug. Unless the bug is pointed out (perhaps by failing when we increase test coverage), this is more an enhancement (to the test).
