### ISSUE TITLE
CI tries to run non-existent script in 2.1 branch

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#2010]
### Description
- Type: Bug
- Priority: Blocker

## Bug

**OS**  
Any.

**mbed TLS build:**  
Version: 2.1.x branch

**Expected behavior**   
The CI succeeds.

**Actual behavior**  
The CI fails due to trying to run non-existent test script `tests/scripts/doxygen.sh`
For example: https://jenkins-internal.mbed.com/job/mbedtls-restricted-pr/384/execution/node/293/log/

**Steps to reproduce**  
Was observed in this restricted PR: https://github.com/ARMmbed/mbedtls-restricted/pull/509

**Comment by mpg** [comment]
Suggested fix: let's backport that test script to the 2.1 branch!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2515

**Comment by sbutcher-arm** [comment]
PR #2011 has now been merged, so this issue is fixed and can be closed.

As an aside - this wasn't the only possible fix! We could have selectively chosen to execute `tests/scripts/doxygen.sh` based on which branch we were executing from. I think this was the best option, but it wasn't the only option, and we should be careful about backporting features for the sake of the CI.
