### ISSUE TITLE
`dec_empty_buf()` is not parameterized based on cipher

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbedtls#2014]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: 2.12.0  
Configuration: default

**Actual behavior**  
When a test suite like `cipher.chacha20` and `cipher.chachapoly` call the `dec_empty_buf()` test, to test that those ciphers work with empty buffers, AES-CBC is actually used as the cipher and no test is run that provides any additional testing of `cipher.chacha20` and `cipher.chachapoly`.

#2013 removes the call to `dec_empty_buf()` from these cipher test suites, but that means we are continuing to miss testing specific ciphers with empty buffers as appears to be the original intent (i.e. why `dec_empty_buf()` was being called outside the AES test suite in the first place.)

**Expected behavior**   
Ciphers aside from AES should also have empty buffer tests. This could be solved with the `dec_empty_buf()` test taking a cipher to use as a parameter.

**Comment by gilles-peskine-arm** [comment]
https://github.com/ARMmbed/mbedtls/pull/2679 addresses this by parametrizing `dec_empty_buf` on the cipher and calling it for ChaCha20_Poly1305. The issue is not fully resolved because calls to `dec_empty_buf` still need to be added for the other relevant ciphers. The relevant ciphers are the ones for which the ciphertext is longer than the plaintext (we already have tests to encrypt an empty plaintext and decrypt it): all supported block ciphers with CBC, and all 128-bit block ciphers with GCM and CCM.

**Comment by AndrzejKurek** [comment]
I created a PR that adds `AES-256 CBC`, `AES-128 GCM`, and `CAMELLIA-256 CBC` tests. CCM is not handled via `mbedtls_cipher_update`, so I have left it out. 
Pre-existing NULL buffer tests include:
- `MBEDTLS_CIPHER_CAMELLIA_128_GCM`
- `MBEDTLS_CIPHER_CAMELLIA_128_CBC`
- `MBEDTLS_CIPHER_ARIA_128_GCM`
- `MBEDTLS_CIPHER_ARIA_128_CBC`
- `MBEDTLS_CIPHER_ARC4_128`
- `MBEDTLS_CIPHER_DES_CBC`
- `MBEDTLS_CIPHER_DES_EDE_CBC`
- `MBEDTLS_CIPHER_DES_EDE3_CBC`
- `MBEDTLS_CIPHER_AES_128_CBC`
- `MBEDTLS_CIPHER_AES_128_XTS`
- `MBEDTLS_CIPHER_CHACHA20_POLY1305`
- `MBEDTLS_CIPHER_BLOWFISH_CBC`

**Comment by AndrzejKurek** [comment]
Introduced a separate issue for CCM, so that this issue can be closed.
