### ISSUE TITLE
No timeout check in ssl_read(), only in ssl_write()

### ISSUE THREAD

**Issue by hnrkp** [ARMmbed/mbedtls#205]
It seems that timeouts (for DTLS) are only checked in ssl_read(), but not in ssl_write(), which is somewhat inconvenient if the server goes away and one is using mbedtls and DTLS together with the LWIP raw api in which your integration layer with that only calls ssl_read() when a UDP packet has arrived from server.

**Comment by mpg** [comment]
(Your title is the opposite of what you meant, right?)

Just to be sure I understand correctly:
- This is happening during handshake I suppose? Otherwise I would tend to think handling timeouts is the responsibility of the application. Of course during handshake it is our responsibility.
- I'm not sure what is "your integration layer" you're referring to. Could you give a precise reference?

I think the new API for timers in the upcoming mbed TLS 2.0 will solve the issue. I am currently writing a knowledge base article about that, but an internal reviewer told me just today that he thinks the section on timers is not clear enough yet... I'll keep working on it and let you know when it's published.

**Comment by hnrkp** [comment]
Whops. Yes, the other way around than the title..

I'm referring to ssl->read_timeout, which is checked in ssl_read( https://github.com/ARMmbed/mbedtls/blob/mbedtls-1.4/library/ssl_tls.c#L6125 ). That's not checked in ssl_write() (and maybe it shouldn't.

Of course I mean *my* integration layer to mbedtls, to make it work with LWIP raw api. To be able to feed data into mbedtls I need to receive the data, save it somewhere, do ssl_read() which will call the net_read function that I've supplied which will then return that saved data and return the decrypted data if successful. Since ssl_read() is only called when data has arrived (and for UDP - no such thing as a closed connection) we can't know if read_timeout has passed unless calling ssl_read() periodically. In my integration layer I just call ssl_read() before every ssl_write(). A better solution might be to have something like ssl_check_timeout() or so which can return an error and tear down the session if any relevant timeout has been reached. Or something along those lines.

**Comment by mpg** [comment]
I don't see how a timeout ssl_write() makes sense, as ssl_write() has no way to know whether the server received the data. (Except if the application protocol says the server needs to acknowledge messages, but then the correct place for the timeout is ssl_read().)

Regarding ssl_read(), I think there are two kind of uses:
1. You know when you expect data from your peer, and then call ssl_read() at a pre-defined time in your application. That's the case where the ssl_read() timeout can be used.
2. You adopt an event-base strategy. In that case, it is expected that timeouts are handled by the application.

We had to add ssl_read_timeout to support use cases with non-event-based, blocking I/O, because in that case it cannot be done by the application alone, but the general philosophy remains that mbed TLS does not try to provide a full timeout solution for the application. We do one thing (crypto/TLS) and try to do it well and play well with other (provide hooks, callbacks, etc.)
