### ISSUE TITLE
Compile error on BSD

### ISSUE THREAD

**Issue by hsleisink** [ARMmbed/mbedtls#219]
When compiling mbed TLS (for Hiawatha webserver) on BSD, I get an error for the -Wlogical-op flag, as used in CMakeLists.txt at line 24.

**Comment by mpg** [comment]
Can you be a bit more specific? We regularly build on FreeBSD with cmake and GCC 4.8, as well as on Darwin with the latest version of GCC and didn't notice a problem so far.

**Comment by hsleisink** [comment]
I tested this on FreeBSD 9.0 and OpenBSD 5.5 (both in VirtualBox). For testing, please download https://www.hiawatha-webserver.org/files/hiawatha-9.14-beta.tar.gz. For compile instructions, see https://www.hiawatha-webserver.org/howto/compilation_and_installation.

The compile error I get is:
<img width="720" alt="error" src="https://cloud.githubusercontent.com/assets/2477525/8766011/93105f38-2e28-11e5-9193-91e27b37b6d9.png">

When I remove the -Wlogical-op flag, all compiles fine.

**Comment by mpg** [comment]
What's the compiler found by CMake and its version? I'd like to see this part of the cmake output:

    -- The C compiler identification is GNU 4.8.3
    -- Check for working C compiler: /usr/local/bin/gcc48
    -- Check for working C compiler: /usr/local/bin/gcc48 -- works

According to the [GCC 4.5 release notes](https://gcc.gnu.org/gcc-4.5/changes.html), -Wlogical-op has been supported since at least GCC 4.5, and according to the [OpenBSD 5.5 release notes](http://www.openbsd.org/55.html), it includes GCC 4.6.4 and 4.8.2, so I'm a bit surprised here.

Overall, I think we'll want to check the GCC version in CMake to only include this warning for versions that support it, but for that we need to be sure which versions to exclude.

**Comment by hsleisink** [comment]
Both FreeBSD 9.0 and OpenBSD 5.5 have GCC 4.2.1.

**Comment by mpg** [comment]
This should be fixed by this commit: https://github.com/ARMmbed/mbedtls/commit/bcb0460224ee4651fa5ecf77b2c3a784e10616c4 However, I'd appreciate if you could confirm that the fix works for you.

**Comment by hsleisink** [comment]
This fixes my issue. Thanks!

**Comment by mpg** [comment]
Cool, thanks for testing (and reporting in the first place)!
