### ISSUE TITLE
No RNG was provided to the SSL module

### ISSUE THREAD

**Issue by edsiper** [ARMmbed/mbedtls#225]
Hi Team, 

I am migrating monkey/monkey HTTP server TLS plugin from mbedtls 1.3.x to 2.0.0, but I am facing an issue when trying to read data from the socket, it fails and triggers the following error:

> No RNG was provided to the SSL module

the problem is triggered from here:

 https://github.com/monkey/monkey/blob/master/plugins/tls/tls.c#L583

I am sure I am missing something in the mbedtls runtime setup, would you please provide some hints to fix this ?

thanks for your help!

**Comment by mpg** [comment]
Hi,

You're most probably missing a call to `mbedtls_ssl_conf_rng()`. You'll need to create and initialize a DRBG context before that (and an entropy context before that, to (re-)seed the DRBG). I suggest you have a look at one of our examples in `programs/ssl`: 

* https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_client1.c#L109
* https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_client1.c#L172

Or our [tutorial](https://tls.mbed.org/kb/how-to/mbedtls-tutorial) for more explanations.

Some background: the design philosophy of mbed TLS is to keep modules  as loosely coupled as possible. That's why the doesn't directly depend on one of our DRBG modules, but lets you provide a callback function (and context) instead.

**Comment by edsiper** [comment]
thanks for the help. I migrated our TLS implementation to mbedtls-2.0 :)
