### ISSUE TITLE
Issues with "make install"

### ISSUE THREAD

**Issue by robotanarchy** [ARMmbed/mbedtls#232]
Hello mbed TLS developers,

I have experienced some issues with 'make install'.

- 1. Even when the `no_test` target was specified earlier, `make install` tries to build the test cases (because the `install` target depends on `all`):
```bash
make no_test
make install # tries to build test cases
```
- 2. At least with `busybox` as `ln`-implementation, `make install` will create symbolic link **loops** for all binaries. From the Makefile (line 36 in mbedtls-2.0):
```bash
 ln -sf $$f $(DESTDIR)/bin/$$o ; \
```
From what I understand, `$$o` is always empty?
(What happens is, that the binary gets overwritten by a symlink to itself!)

- 3. When compiling statically, only the `libmbedtls.a` file get copied. `libmbedx509.a` and `libmbedcrypto.a` are missing. When compiling against libmbedtls.a alone, lots of undefined reference errors pop up - because these functions are in the other .a files, so we definitely need them.

I've built mbedtls-2.0 on [sabotage linux](https://github.com/sabotage-linux/sabotage) ([my recipe](https://github.com/robotanarchy/sabotage/blob/hiawatha/pkg/mbedtls) with workarounds for these issues).

**Comment by mpg** [comment]
Hi, and thanks for your report!

I believe the third issue has been fixed in the meanwhile: https://github.com/ARMmbed/mbedtls/commit/52a5079cf243c029e480a0d7debc80c790a14495

Regarding the first issue, would you be happy with an option such as `make install NOTEST=1` for this case?

Regarding second issue, this is a remainder of the time when we installed under both name (polarssl and mbedtls), I'll remove the `ln` line.

PS: which name would you like us to use for attribution in the ChangeLog?

**Comment by robotanarchy** [comment]
Hi mpg,
the `make install NOTEST=1` sounds fine for me.

For attribution in the changelog, just use my username :+1:

**Comment by mpg** [comment]
Hi, in the meantime I noticed we don't even need `NOTEST=1`, since the tests are never installed, so we can just have install depend on no_test. Simpler for everyone.
