### ISSUE TITLE
Missing files during installation

### ISSUE THREAD

**Issue by hsleisink** [ARMmbed/mbedtls#237]
When I unzip the mbed TLS 2.0.0 tarball, do a make and make install, the only file I see in /usr/local/lib is libmbedtls.a. The files libmbedcrypto.a and libmbedx509.a are missing. Why is this?

The Hiawatha webserver has an option to use the mbed TLS library that is already installed on the system, instead of the one shipped with Hiawatha. But it won't compile, unless those two missing files are manually copied to /usr/local/lib.

Please, advice.

**Comment by mpg** [comment]
Sorry for that. I think this is a bug we fixed in the current development branch: https://github.com/ARMmbed/mbedtls/commit/52a5079cf243c029e480a0d7debc80c790a14495

Unfortunately, there was also a bug in our CMakeLists.txt that caused install to fail, so there is no obvious workaround except applying the above patch, using the development branch (which should be safe, it's only bug fixes for now), or copying those files manually.

**Comment by hsleisink** [comment]
Ah, great. Thanks!
