### ISSUE TITLE
Authenticated encryption example does not give any Output to serial

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/mbedtls#247]
Putty does not show anything.

OS = Ubuntu 14.04 LTS
Compiler Arm GCC (no issues with compilation)

authcrypt-example 0.0.0
┣─ mbed 3.0.4
┃ ┗─ mbed-core 0.0.1 yotta_modules/mbed-core
┃   ┣─ mbed-hal 0.2.1 yotta_modules/mbed-hal
┃   ┃ ┗─ mbed-hal-freescale 0.1.4 yotta_modules/mbed-hal-freescale
┃   ┃   ┗─ mbed-hal-ksdk-mcu 0.1.5 yotta_modules/mbed-hal-ksdk-mcu
┃   ┃     ┗─ mbed-hal-k64f 0.1.8 yotta_modules/mbed-hal-k64f
┃   ┃       ┣─ uvisor-lib 0.6.9 yotta_modules/uvisor-lib
┃   ┃       ┗─ mbed-hal-frdm-k64f 0.1.4 yotta_modules/mbed-hal-frdm-k64f
┃   ┗─ cmsis-core 0.2.3 yotta_modules/cmsis-core
┃     ┗─ cmsis-core-freescale 0.1.1 yotta_modules/cmsis-core-freescale
┃       ┗─ cmsis-core-k64f 0.1.2 yotta_modules/cmsis-core-k64f
┗─ mbedtls 2.0.4

**Comment by mpg** [comment]
You appear to be using https://github.com/ARMmbed/mbedtls-examples which is *not* the right source of examples for beta; it is an archive of the examples we used to alpha3.

The up-to-date examples for beta are now packages as test files inside the mbedtls yotta module.

**Comment by hasnainvirk** [comment]
oh alright. Then I think you should update the info in README.md. Also Readme.md seems to be in need of rewriting and careful re-consideration. And also Inform Bogdan about the new links to the test cases .. Because what he provided to OOB testers points to Archive Repository. Its confusing.

**Comment by mpg** [comment]
Which Readme.md? The readmes in the old mbedtls-examples all start with a boldfont note that it's an archive. Regarding "Readme.md seems to be in need of rewriting and careful re-consideration." can you be more specific?

Also, I don't understand what happened with the OOB instructions, because I'm 100% positive I updated them before OOB started, but apparently some changes were lost. Simon told me he updated them (again) a few days ago, so they should be correct now, but I'll triple-check that with Bogdan anyway.

Sorry for the time you lost testing the wrong repo.

**Comment by hasnainvirk** [comment]
Yeah, I have got the right repo now. I will test it now and keep you posted. Thanks for your prompt reply.

**Comment by mpg** [comment]
Ok, so I checked, and there is still outdated info in mbed OS's readme and examples.json files. I'll work with Hugo to get that fixed. Good that you ran into that issue, we wouldn't have noticed otherwise.
