### ISSUE TITLE
Issue with cross compilation? 

### ISSUE THREAD

**Issue by malmaud** [ARMmbed/mbedtls#271]
I'm running into the below error when trying to cross-compile for Windows on an openbuild service with [this spec file](https://build.opensuse.org/package/view_file/home:malmaud/mingw64-libmbedtls/mingw64-libmbedtls.spec?expand=1). Anyone have any insights? 

```
[  174s] ../library/libmbedtls.a(net.o): In function `mbedtls_net_connect':
[  174s] /home/abuild/rpmbuild/BUILD/mbedtls-2.1.0/library/net.c:140: undefined reference to `__imp_getaddrinfo'
[  174s] /home/abuild/rpmbuild/BUILD/mbedtls-2.1.0/library/net.c:145: undefined reference to `__imp_socket'
[  174s] /home/abuild/rpmbuild/BUILD/mbedtls-2.1.0/library/net.c:155: undefined reference to `__imp_connect'
[  174s] /home/abuild/rpmbuild/BUILD/mbedtls-2.1.0/library/net.c:161: undefined reference to `__imp_closesocket'
[  174s] /home/abuild/rpmbuild/BUILD/mbedtls-2.1.0/library/net.c:165: undefined reference to `__imp_freeaddrinfo'
```

**Comment by mpg** [comment]
Hmmm, sorry nothing obvious to me. I notice you're using `WINDOWS=1` in your make invocation, that should be `WINDOWS_BUILD=1` for cross-compilation, but I don't believe this is the source of your problem. (Also unrelated: I don't thing gcc-c++ is required, nor cmake since you seem to invoke make.)

Can you please tell me more about `%{_mingw64_make}`? What does it expand to, and if it's a specific command such as mingw64-make, what does this command do?

We're doing successful cross-compilation builds on a regular basis using the following make invocation:
https://github.com/ARMmbed/mbedtls/blob/development/tests/scripts/all.sh#L242

**Comment by malmaud** [comment]
Thanks for the tip!  After seeing a working make invocation, I'll be able to get it to work.
