### ISSUE TITLE
Condition always false

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#2718]
https://github.com/ARMmbed/mbedtls/blob/66b7edb10865809a972362ce362c62820075ade3/library/ssl_srv.c#L3833
`n > 65535` is always false, because it is calculated as an unsigned 16-bit value.

**Comment by RonEld** [comment]
Hi @irwir 
Yes, you are correct that it will always be false, because the value of `n` is a 16 bit value.
The check is taken from [RFC4279](https://tools.ietf.org/html/rfc4279#section-3):
~~~
 struct {
          select (KeyExchangeAlgorithm) {
              /* other cases for rsa, diffie_hellman, etc. */
              case diffie_hellman_psk:  /* NEW */
                  opaque psk_identity_hint<0..2^16-1>;
                  ServerDHParams params;
          };
      } ServerKeyExchange;
~~~
where `n` is the `psk_identity_hint`.
Do you get warnings on this condition? I think it is clearer to add this check for visibility and future compatibility, but if there are warnings from a compiler or a static analysis, it is worth reconsidering this.

**Comment by hanno-arm** [comment]
Hi @irwir,

I agree with @RonEld. It eases matching code to standard if we have this check, and when it comes to code-size, it has no impact because compilers will be able to optimize it away. 

Unless there are static analyzers complaining about the check, I prefer to leave the code as-is and close this as not-a-bug.

Regards,
Hanno

**Comment by irwir** [comment]
Yes, the warning came from static analysis.
The RFC explicitly tells that only 16 bits are necessary.
Using `uint16_t n` instead of `size_t n` might help to close the issue in the most natural way.

**Comment by irwir** [comment]
Additionally, for unsigned numbers `n == 0` or `!n` could be a tad better than `n < 1`.

**Comment by Patater** [comment]
Which static analysis tool has trouble with this?

**Comment by irwir** [comment]
@Patater

> Which static analysis tool has trouble with this?

[This one](https://www.viva64.com/en/pvs-studio/)

**Comment by irwir** [comment]
A related issue was spotted:
https://github.com/ARMmbed/mbedtls/blob/beec142010cd9f3a967a9a3a7b407b51841b542e/library/ssl_cli.c#L2359
Pointer difference is of `size_t`. Casting to `int` is a potential error and should be removed.
Here `len` also could be declared as `uint16_t`.

**Comment by hanno-arm** [comment]
Fixed by https://github.com/ARMmbed/mbedtls/pull/2856.
