### ISSUE TITLE
mbedtls_x509_crt_verify ignores max_pathlen on intermediate certificates

### ISSUE THREAD

**Issue by NWilson** [ARMmbed/mbedtls#280]
While writing unittests, I discovered that `mbedtls_x509_crt_verify` only enforces max_pathlen on the top (root) certificate. If it is set on any intermediate certificates, it doesn't appear to be enforced at all. (At least, that field isn't read anywhere I can see!)

I'm not an authority on how the basic constraints are used in practice, but this seems surprising. Note that JSSE's PKIXCertPathBuilder does apply the max_pathlen constraint on intermediate certs, which is how I found the bug, by applying our existing Java tests to mbedTLS.

Here are some certs generated using mbedTLS:

    pkey/gen_key type=rsa rsa_keysize=2048 filename=cert11.key
    pkey/gen_key type=rsa rsa_keysize=2048 filename=cert12.key
    pkey/gen_key type=rsa rsa_keysize=2048 filename=cert13.key
    pkey/gen_key type=rsa rsa_keysize=2048 filename=cert14.key
    x509/cert_write selfsign=1 issuer_key=cert11.key\
      issuer_name='CN=Test root 2' is_ca=1 output_file=cert11.crt
    x509/cert_write issuer_crt=cert11.crt issuer_key=cert11.key subject_key=cert12.key\
      is_ca=1 subject_name='CN=Test intermediate maxpath 1' max_pathlen=0 output_file=cert12.crt
    x509/cert_write issuer_crt=cert12.crt issuer_key=cert12.key subject_key=cert13.key\
      is_ca=1 subject_name='CN=Test intermediate maxpath 2' output_file=cert13.crt
    x509/cert_write issuer_crt=cert13.crt issuer_key=cert13.key subject_key=cert14.key\
      subject_name='CN=Test leaf invalid 3' output_file=cert14.crt

It gives you a path like this:

    "CN=Test root 2"
    -> "CN=Test intermediate maxpath 1", max_pathlen=0
       -> "CN=Test intermediate maxpath 2"
          -> "CN=Test leaf invalid 3"

Running the following pseudocode validates successfully (the code from our test harness is hard to extract):

    chain = "Test leaf invalid 3" -> "Test intermediate maxpath 2" ->
            "Test intermediate maxpath 1" -> NULL
    root2 = "Test root 2" -> NULL
    mbedtls_x509_crt_verify(chain, root2, ...)

As a fix, I would expect `x509_crt_check_parent` to take an `int pathlen` argument and check both the path length and CA bit of the certificate's basic constraints.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSSL-472

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSSL-515

**Comment by NWilson** [comment]
I'm sorry, I hate to say this, but I've only just got round to testing the changes for this when I saw mbedTLS 2.1.3 was released.

I think there's a bug in the fix, unfortunately, since the cert chain for google.com no longer validates! Janos added a check in `mbedtls_x509_crt_verify_with_profile` which breaks the following cert chain:

    Global CA -> intermediate (RFC pathLenConstraint=0 / mbedTLS max_pathlen = 1) -> leaf

There's a cryptic comment that tries to explain what looks like an off-by-one error.

Also, all the logic for "self-signed intermediate certificates" is surprising; at the least there should be a comment explaining how you can get a self-signed intermediate, given that it appears to be a logical impossibility! If it's self-signed, then it can't have a parent and must be at the top of the chain! Since pathLenConstraint only applies downwards, I conclude that the really wording from the RFC is there to allow for different path-building algorithms than the one that mbedTLS implements. For mbedTLS, the `self_cnt` checks appear to be misguided.

I want to go through this code again, scrutinising each line for off-by-one errors, in case there are any more in there.

**Comment by NWilson** [comment]
Woah! This is crazy, I've just worked out what @yanesca means by "self-signed certificates in the path". You've added a test which exercises a bug/quirk in mbedTLS, this is _not_ normal behaviour.

The behaviour that's just been added to mbedTLS 2.2.0/2.1.3 is to "fix" handling of this certificate chain:

    crt = subject:"Test leaf valid 3", issuer:"Test intermediate maxpath 1", CA=false
    crt->next = subject:"Test intermediate maxpath 1", issuer:"Test intermediate maxpath 1", CA=true
    crt->next->next = subject:"Test intermediate maxpath 1", issuer:"Test root 2", CA=true
    trust_ca = subject:"Test root 2", issuer:"Test root 2", CA=true
    mbedtls_x509_crt_verify( crt, trust_ca )

So the chain has two copies of the same certificate, the first of which is self-signed, the second which chains to the root. mbedTLS 2.2.0 builds a chain with three certificates in, but because there's a random extra self-signed copy of the intermediate in the chain, it reduces `path_cnt` by 1. Worse, the signature on the self-signed copy isn't even checked at all. This is a disaster, anyone can bypass the path-length constraints completely just by forging a few self-signed copies of the certificate.

mbedTLS has always had this quirky behaviour of searching for the self-signed parent of a certificate in the chain, which was odd but at least not exploitable. Now it's been made into an actual weakness (albeit a small one, since path length constraints aren't very important).

**Comment by NWilson** [comment]
@mpg, I'll wait to hear from you or someone else at ARM. I don't know what you want to do with the 2.1.3 and 2.2.0 releases, but I expect you'll have to do a bugfix release, since the original problem that made me notice this was that google.com's certificate chain no longer validates. I would have checked the release before it went out, if I'd realised it was coming, the first notification I got though was the release announcement in my inbox!

In the meantime, I've done a big fixup on a branch here:
https://github.com/NWilson/mbedtls/commits/path-fixes2

It's quite a large fix, probably bigger than you'd want to apply in a 2.1.4 minor release. Perhaps for 2.1.4 you could do the safe thing and just roll the code back to 2.1.2? Then think really carefully and get as many people as possible to review things before releasing to do the next round of fixes!

**Comment by mpg** [comment]
Hi Nicholas,

Thanks for your comments. I can't look into the details right now, but here are a few quick comments.

1. I'd have to check the RFC, but IIRC it has a notion of self-issued certificates, ie issuer == subject. I don't remember exactly the relationship with self-signed, but I *think* self-issued certs must indeed not be counted for pathlen checks. I'm not saying our current code is correct, just that I don't think ignoring self-issued/signed is just about of quirk of mbed TLS, I definitely remember the RFC saying something about that.

2. I'm not sure reverting the faulty fix is the best way to go, as it would re-introduce the issue with pathlen not being checked on intermediate CAs.

I'm obviously going to investigate ASAP and come back to you.

**Comment by mpg** [comment]
So, I think there are many issues here, and I'll try to address them one at a time.

**Allowing self-something certs in the chain and discarding them for max_pathlen checks.** I think the code is correct but the comments are wrong to call them self-signed: those are what RFC 5280 call self-issued certificates. See last [paragraph before section 3.3](https://tools.ietf.org/html/rfc5280#page-13) for the definitions. Usually the trusted root CA will be self-signed (though a cross-cert could be used as a trusted root too), most intermediate CAs will be cross-certs, though some of them could be self-issued (the RFC mentions key rollover and policy changes as possible reasons).

The RFC mentions in many places that self-issued certificates are not counted for pathLenConstraints enforcement purposes (or said otherwise, that this is a constraint on the number of non-self-issued certs in the chain): [section 4.1.2.9](https://tools.ietf.org/html/rfc5280#section-4.2.1.9) and [6.1.2 (k)](https://tools.ietf.org/html/rfc5280#page-80) for example.

So I think the `self_cnt` mechanism is indeed doing what the RFC says (or at least trying to do so), though the comments ought to be fixed to refer to self-issued rather than self-signed, and possibly cite the RFC too. I also believe the test case you mention is exercising a provision in the RFC and not a bug/quirck of mbed TLS.

**I don't think the change introduced any security issue.** More precisely, unless I'm seriously mistaken:

* When our implementation accepts a cert chain, there is indeed a chain of signatures from the bottom cert to a trusted root. I can't see how any signature verification can be skipped in our verification process.

* Every time `self_cnt` is incremented, so is `path_cnt`, so the difference `path_cnt - self_cnt` is always non-decreasing, so that an attacker cannot use self-issued certs in the chain to bypass pathLenConstraints.

If you think any of those two claims is wrong, or there is another security issue, I'd be unhappy that this is the case but happy to learn about it, so please provide a detailed example showing the issue.

**"mbedTLS has always had this quirky behaviour of searching for the self-signed parent of a certificate in the chain"** This is a bit of a side discussion, but... If you look at [RFC 5246's definition of `certificate_list`](https://tools.ietf.org/html/rfc5246#page-48) you'll see omitting the trusted root is only a MAY. There was a discussion on the TLS list recently about making that a MUST and Viktor Dukhovni correctly pointed out that in some cases (DANE-TA with anything but Cert/Full) the verifier does _not_ have the trusted root certificate (only a hash of it or its public key) so it _needs_ to be found in the chain transmitted by the peer. Admittedly, mbed TLS does not offer out-of-the-box support for that scenario, but I think it's possible to implement it using the `vrfy` callback, precisely thanks to our "quirky" behaviour of allowing the self-signed parent to be found in the chain.

Also note that in recent versions, we look for a parent in the `trusted_ca` list _before_ looking in the peer-provided list.

-----

I'm now going to investigate why we're incorrectly rejecting google.com's chain, how to fix that, and get back to you. I first wanted to clarify the situation regarding possible security or compliance issues, but obviously failing to validate a widely-used chain is also a problem we want to address sooner rather than later.

**Comment by NWilson** [comment]
Hi Manuel, that's a very helpful response, thanks!

----

Regarding **self-signed certs in chains**: the problem with the RFC is that it's too vague! There are tons of X.509 extensions and conventions, and different protocols use them in different ways. Just because the RFC allows the possibility of chains with self-signed intermediate certificates, that doesn't mean that a chain-building algorithm has to handle them.

After thinking about it more, I still think it sounds crazy to build a chain where an intermediate cert is self-signed! This is what the recently-added test does in "test_suite_x509parse: X509 CRT verify chain #7" (see the sketch of the certificates above).

It's really a logical impossibility to have a self-signed intermediate (in most chain-building algorithms): you need to have a cert with two parents. mbedTLS doesn't make any distinction between two certs with the same subject name (because it doesn't support AKID/SKID checking during chain building) -- but, even if you check the AKID, you then need to have two different certs with identical subject and identical SKID! I don't think a chain-building algorithm should ever construct such a chain.

I tried to validate the chain from the unit-test using OpenSSL, and it simply refuses to build any chain containing a self-signed intermediate: when it reaches a self-signed cert, it treats it as the end of the chain (as you'd expect!). For compatibility and sanity, I would suggest you consider doing the same in mbedTLS. We should check what NSS does here, since it uses the same exhaustive chain-building as JSSE, which is a bit different to OpenSSL. (However, JSSE refuses to put self-signed intermediates in a chain, after some experimentation this afternoon.)

----

Regarding any **new security risk**: I think you're right, I had a knee-jerk reaction when I saw what the code was doing. An attacker can cause some unique certificate chains to be created if he sends a long chain of TLS certificates containing lots of copies of the same cert. But, the chain building is probably "safe" in the sense that the bogus chains don't appear to help an attacker (I'd say I'm around 98% sure).

----

A note on your final paragraph: I think we're getting two things muddled here. Almost always the root of a chain is self-signed (agreed). It's OK to look for the root in the provided chain, if it's not in the trust_ca list (agreed). What's I'm saying is "quirky" is when we have a self-signed certificate, to look for its parent: it's self-signed, so it logically can't have a parent! We should be looking for a _copy_ of the certificate in the trust_ca list, but there are no more parents in the chain.

**Comment by NWilson** [comment]
...and finally a comment on Google's cert chain: the reason for that is fairly easy to see: in the top-level verify function, there's a "+2" with a comment trying to justify it. That's actually off-by-one, as can be seen by Google's chain:

    leaf: CN=*.google.com
    intermediate: CN=Google Internet Authority G2, pathLenConstraint=0
    root: GeoTrust Global CA

Now, it would be easy to just fix that bug and release a 2.1.4 -- but I'd personally be very afraid! This area of the code is really, really hard to reason about. I spent several hours this afternoon with a pen and paper trying to map out all the possible flows through the verify_child/verify_top functions, and the possible values of path_cnt and other variables in each branch of those functions.

It's basically impossible! There are simply too many branches to verify that code by hand. I personally would not want to take the responsibility of making any changes there without simplifying it down so that all the branches can be analysed.

I'm sure when you released 2.1.3, you must have gone through an internal review process for the code, but I think it's worth admitting is is just very complex, and this isn't the first bug in there I've reported.

In the branch I linked to above, I chopped out about two-thirds of the chain-building code, and then I was able to sketch out all the states on one sheet of A4. Obviously, you might well want to make a more conservative change, but for a stable branch the safest change is just reverting, since the 2.1.2 code is well tested and has been deployed for years without problems.

----

OK, I've done a lot of typing, thanks for your hard work Manuel, it's obviously up to the ARM team what decisions to make, so I won't get in the way and rush you. Thanks!

**Comment by mpg** [comment]
Thanks for your comments.

I think we agree on the complexity of the RFC (which is actually a simplification of the full X.509 spec). I seriously wish we didn't have to deal with such a complex (and IMO underspecified in some places) spec.

However in this particular case I think it was the right move to include that feature, as we were introducing a new check (enforcing pathlen on intermediate CAs) and it could have introduced false negatives (chains that we would start rejecting though they were valid according to the RFC), so doing what the RFC says about self-issued (let's use the precise terminology) certs avoided that risk.

I also read an argument recently on a mailing-list about why in some circumstances it might make sense to do present chains that I would have deemed unreasonable, and while I didn't have the time to follow the whole argument (that's the kind of argument requiring pen, papers and aspirin), the points I followed looked reasonable so I was left with the impression that sometimes X.509 _need_ to be more complex than I would think. I definitely wish it wasn't the case, but people to complex stuff with their X.509 chains, and sometimes for good reasons.

Now if OpenSSL and other common libraries reject all chains containing self-issued certs, then we can probably take that as an indication that nobody uses them, and then I agree that the right thing to do would be to avoid the complexity in our code.

-----

Regarding the bug, I currently *think* the issue is that the +2 is right in `verify_child()` but wrong in the top-level `verify_with_profile()` function. Unfortunately I had no opportunity to test that hypothesis yet, all I could do was think about it in my head... I'm now going to to some tests, but if that hypothesis is right, then the fix will be simple and I would be quite confident applying it after adding test cases. Let's wait and see.

-----

Regarding the complexity of our current implementation, I agree. If you look back in history, you might notice we factored a few things that were repeated (eg `check_parent()`), but yes, this kind of code tends to become more and more complex over time and needs refactoring from time to time in order to contain the complexity. I'm sure you'll understand we prefer such a refactoring to happen at a quiet time and not be mixed with a bug fix. Obviously it will need lots of review and possibly new tests to avoid any regressions, so while it would make things easier in the long run, it would also require a non-trivial initial amount of work.

I suggest you open a separate PR for that so that we don't lose track of it.

**Comment by mpg** [comment]
Here is my current analysis: in `verify_parent()` we are checking pathlen when looking for a grand-parent, ie the current intermediate (parent) is not yet counted in pathlen, so the `2 + ` is correct. In `verify_with_profile()` the current cert is the EE cert which does not count in pathlen validation, so the comment about unaccounted current step and `2 + ` are wrong.

Actually, thinking about it, there should not be any `max_pathlen` check here as any value on the first intermediate CA is valid. And indeed, since `path_cnt` is always `0` at this point, the fixed test with `1 + ` reads `if( parent->max_pathlen > 0 && parent->max_pathlen < 1 + 0 )` which is always false. (I'm surprised neither GCC nor Clang gives a warning about this.)

Some testing seems to go in that direction. If I change the `2 + ` to `1 + ` in `verify_with_profile()` but leave the `2 + ` in `verify_child()` then the connection to google.com succeed and all tests still pass. Changing to `1 + ` in `verify_child()` makes two tests fail: I re-reviewed those two test cases and they look correct to me.

Also, looking at the full list of test cases, none of them addresses the case where the max_pathlen constraint is on the first intermediate CA, which explains why the the issue went unnoticed. We're obviously going to add a test for that. OTOH, for the other cases, they still look quite complete to me and IMO are a good reason (in addition to the above analysis) to think that there is no other off-by-one error that the wrong test for the EE->first-intermediate link, which actually was more a test that shouldn't be here than an off-by-one.

Currently (this may change) I'm quite confident this is a correct fix suitable to apply to all current branches. Obviously more internal review and discussions will happen before we reach a conclusion, though.

-----

Regarding the possible security impact of ignoring self-issued cert for the purpose of pathlen checking, I think I now have a clear argument for why this is not a problem: the key point is, there are only two ways an self-signed intermediate CA can exist:

1. It was correctly issued by a valid CA, and then this hints we should support that case. (Yes, that attacker can then form arbitrarily-long valid chain, but I don't see what that would gain them, and we already have a compile-time limit on the number of intermediate CA we accept - and this check doesn't deduce self-issued certs from its count.)
2. It was issued by the attacker, which is only possible if the attacker controls the key associated with a valid CA cert, and then we have much more to worry about than arbitrarily long chains.

-----

Finally, regarding your remark about the "quirk": I misunderstood your first comment about that. Now that I understand you, I think we agree. To be sure we're on the same line: the quirk is only about the internal implementation, not a quirk in observable behaviour, right? It "only" makes analysis and testing more complex (which is especially undesirable for that part of the code), but does not result in wrong behaviour in any case, right?

**Comment by NWilson** [comment]
Hi Manuel, thanks for your careful analysis.

On a side note, if we want to allow people to build unusual chains with duplicate subjects, then we should support checking the AKID extension (which the RFC "RECOMMENDS" is used when building chains, and we've thought about this previously in #194). Now that I'm looking at the code again, I'll see about rebasing my branch from that issue.

---

I agree that refactoring should be kept out of bugfix releases, so _don't_ merge my refactoring until enough time has passed for a longer review. While going through the code yesterday, I noticed other bugs too: I'm convinced that there are some unreachable branches, and it also looks like we actually verify the self-signature on trusted self-signed end-entities which is wasted work.

I'll make a separate PR for my refactor and run gcov on it: I think it's really important that the tests have higher branch coverage in this code. This is the "Most Dangerous Code in the World", it shouldn't have chunks of dead code in and untested branches.

----

I reached the same conclusion about the +2 in the top-level verify function: the whole check is redundant. I also can't find any other bugs, but I wasn't able to exhaustively analyse all the paths through the code, which makes me afraid. If you're happy to release that fix, that's OK, but you'd have to take responsibility.

----

Regarding the security impact of the change: I'm not sure it's quite a simple as your analysis suggests. Here's an example scenario:

1. GeoTrust signs "ARM Internet Authority G2" with maxpathlen=0 (no further intermediates allowed). There are also some usage extensions or policy extensions on this intermediate.
2. Using the private key for "ARM Internet Authority G2", someone at ARM creates a self-issued (and self-signed) certificate with the same subject name, but different usage extensions.
3. Now mbedTLS will accept the chain: EE → self-issued intermediate → original intermediate (pathlen=0) → GeoTrust.

Even though the original intermediate was only supposed to sign EE certificates, the chain _might_ be OK because the RFC allows us to discount self-issued intermediates. However, usage and policy checks may be bypassed! Long after the GeoTrust signature was issued, someone who controls the intermediate can just decide to make a new intermediate.

Now, it's hard to guess what sort of policy checking different mbedTLS client software uses. If the client looks at the usage for second certificate in the chain, to see if the intermediate is authorised to issue the usage extensions on the EE, then there could be a problem. The ability of an intermediate to re-issue itself (with any extensions whatsoever) is a bit hard to analyse. As we said, it's hard to know for sure what X.509 properties people are using, especially in embedded systems which might use their own certificate system.

----

About the "quirk": I there is an observable difference in behaviour, since mbedTLS successfully validates this contentious chain that OpenSSL fails to validate, and JSSE builds a different (shorter) chain. I was trying to say that searching for the "parent" of a self-issued certificate is itself a "quirk".

Obviously that's not precise language, I was trying to find a polite way of saying "something that feels really wrong, but it's hard to say it's definitely a bug".

**Comment by mpg** [comment]
I'm preparing a branch with fix and a test for that case. I think I'm more confident than you in that fix, because while I agree that part of the code is hard to reason about, I'm probably more familiar with it than you are. We're obviously taking responsibility for the fix we'll apply.

-----

Regarding the security impact:

* We currently don't implement policies, name constraints, etc. so this can't possibly be an issue right now. 
* I'm less familiar with those parts of the RFC than others, but my understanding is that self-issued intermediates can't be used to bypass policies or other constraints, one reason being that the RFC explicitly special-cases them in the way many policies/constraints are handled.

However I do agree that complexity is generally the enemy of security, and that the RFC is generally more complex than what we'd like to implement. If self-signed certs inside a chain are accepted by neither OpenSSL, NSS nor GnuTLS, then I take that as a strong indication that this is not used in the wild, so I'm inclined to remove support for that in order to remove unnecessary complexity, even if I still don't think there is a security issue.

-----

Regarding AKID: I'm not sure which way you meant it, but it IMO it makes more sense implement AKID after the refactoring. I'll comment on your refactoring PR just after I'm not preparing a branch with the fix for the current bug.

-----

About the "quirk" a you politely put it: OK, I definitely misunderstood you, I thought you were referring to a more specific case (when the trusted root is included in the peer-provided chain, instead of checking for equality against a member of trust_ca we still check for "being a child" of a member of trust_ca). What you don't like is more general than that (looking for a parent of _any_ self-signed cert, not just at the top of the chain), I think I now finally get it. Well, then that's basically the discussion we just had about RFC vs complexity, then.

Again, I'm not opposed to rejecting RFC-compliant chains if it can reduce the complexity of our code or of analysing it, _if_ we have good reasons to think that nobody uses such chains. I'll try to check myself what other libraries do with such chains, as if they indeed all reject them, then this will be a good reason to think they're not used.

**Comment by NWilson** [comment]
Thanks! You've worked hard on this, and I think we agree now.

With policies, what I was more thinking of is customers who apply policies themselves, rather than built-in mbedTLS support. In our application, we check for the existence of particular certificate extensions ([1.2.826.1](http://www.asvang.org/dokka/html/alvestrand/objectid/1.2.826.1.html).04446945.XXX) when we connect to our own closed CA system, where the extensions denote various policies that we enforce. In our code we're OK, because we immediately reject connections if the chain is the wrong length.

Re: AKID, yes, it's better to come back to that after everything's done on the core chain-building code.

I'll let you follow your priorities, there's no rush to look at my pull requests immediately.

**Comment by mpg** [comment]
Good point on policies being possibly applied by users even if not in the mbed TLS core.

For the rest, glad we've reached agreement. Thanks for the time and effort you've invested in that discussion and the associated PR.

**Comment by yanesca** [comment]
I am terribly sorry about the bug and the mess I caused, I should have tested more thoroughly. I also had a difficulty accounting for every possible call path, but I didn't even attempt such a systematic approach at testing that @NWilson mentioned. I should have. Although I didn't see (and didn't look for) a lot of other test cases for longer certificate chain verification, for some reason I made the very unjustified assumption that there are other test cases and bugs like this would be caught immediately.

About the intermediate self-issued certificates: I think in theory these happen when hierarchies are getting integrated into each other and updating the trusted certificates in some or all of the devices is too expensive or not even possible. In this case cross certificates are issued, but the self-issued ones remain on board of the mentioned devices. Furthermore if someone in one of the hierarchies wants to verify a chain of an object in the other hierarchy, it may have the old self-issued certificate as an intermediate certificate in it. This issue certainly can be addressed when constructing the certificate chain, but as far as I know, that particular standard does not say anything about certificate chain construction it only addresses certificate chain verification. I am not sure how practical this scenario is, but at least this was what I thought of when I read the corresponding part in the standard.

**Comment by mpg** [comment]
@NWilson @yanesca if any of you feels like reviewing PR #354, that would be appreciated (of course it will be reviewed internally as well, but more eyeballs are always better).

**Comment by NWilson** [comment]
@yanesca Don't worry about it, bugs are always a team effort, not one person's fault. Thankfully, it was "safe" and rejected good chains, rather than the other way around, so it all worked out OK in the end, rather than being a vulnerability.

Regarding how self-issued certs get in the chain: my understanding of cross-signing is that it results in two copies of a certificate, each with the same name. But, only one of them is included in the chain that's built: one version of the devices will build the chain with one of the certificates, the newer devices will use the other copy. It's not normal to have both of them somehow end up in a chain. Perhaps the RFC is giving you rules on how to validate a chain that you didn't build, but was just passed to you? The JSSE API allows for that, but OpenSSL and mbedTLS don't, they always build and validate the chain in one pass without letting the user specify the exact chain. Hmm.

@mpg Thanks for asking, I think the fix is safe, I can't see how that check could ever be needed in the top-level function. Looks good to me.

**Comment by mpg** [comment]
@yanesca forgot to tell it, but +1 to what Nicholas said.
