### ISSUE TITLE
Coding standards and opening parenthesis spacing

### ISSUE THREAD

**Issue by irwir** [ARMmbed/mbedtls#2869]
### Description
- Type: Enhancement
- Priority: Minor

As coding standards article says, 
> mbed TLS uses a non-standard space placement throughout the code

After spotting a suspicious case, all  `*.c *.h` files in `mbedTLS` and `mbedTLS-crypto` files were searched with the patterns like: space - C keyword - space - open parenthis.

There were 43 files found with the string " if (", 11 files with " for (" string, 5 files with " while (".

The existing cases could be fixed with `sed`, for example.

Should something be done to prevent future issues of this kind?
Possibilities are:
1. Manual checks from time to time.
2. Add a simple script to the existing checks (grep?), though false positives are possible.
3. An automatic formatting of source code.

**Comment by gilles-peskine-arm** [comment]
We're aware that whitespace isn't completely consistent. Our approach is to review it manually in pull requests (which, as a reviewer, I find less than ideal). If something has slipped in, we prefer to modify it only if we're changing the code for other reasons, because any code change has a cost (space in the history, conflicts with any other pending change to the same part of the code).

We've looked into automatic formatting, but we haven't found one that would understand our exact rules (e.g. `f( foo )` vs. `#if defined(FOO)`). Our current plan is to change the rules one day and then start enforcing them with a tool like astyle or clang-format, but at the moment we think that the disruption to pending PRs and third-party patches wouldn't be worth it.

So for the time being, this is a won't-fix.

**Comment by gilles-peskine-arm** [comment]
Closing as wontfix (for the moment).

**Comment by irwir** [comment]
@gilles-peskine-arm 
Thanks for the answer.
The mentioned inonsistencies are minor and do not break readability, but from time to time do complicate searching in files.

I remember seeing a project in Github with a configuration file for `uncrustify` in the root of repository. The tool is highly customizable, and it might be possible to set up for your specific needs.

**Comment by gilles-peskine-arm** [comment]
FYI, we'll be [changing the coding style to a more standard format](https://github.com/orgs/Mbed-TLS/projects/1#column-19169231), which will be enforced by the CI. We will provide a script to adjust existing work in progress. We haven't worked out the details of the new format, but we have a consensus that it will have not have spaces inside parentheses. We plan to do the switchover around the 2022-2023 new year lull.
