### ISSUE TITLE
Handshakes with some HTTPs sites do not work with mbedtls.

### ISSUE THREAD

**Issue by neoniousTR** [ARMmbed/mbedtls#2915]
Handshakes with some HTTPs sites do not work with mbedtls.
These include fh.xrpl.ws and api.delion.io .

I tried to figure out the problem in my code, but even with everything reduced to a simple connect + handshake, it did not work.

Now, I tried it with the mbedtls ssl_client2 program itself:

mbedtls thomas$ ./programs/ssl/ssl_client2 server_name=api.delion.io server_port=443

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the client cert. and key... ok (key type: RSA)
  . Connecting to tcp/api.delion.io/443... ok
  . Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x2700
    Unable to verify the server's certificate. Either it is invalid,
    or you didn't set ca_file or ca_path to an appropriate value.
    Alternatively, you may want to use auth_mode=optional for testing purposes.

Last error was: -0x2700 - X509 - Certificate verification failed, e.g. CRL, CA or signature check failed 

So it seems like mbedtls does not support some websites. The problem is, I do not know why and what I have to change.

Any idea?

**Comment by RonEld** [comment]
Hi @neoniousTR 
The error message tells you "Unable to verify the server's certificate. Either it is invalid,
or you didn't set ca_file or ca_path to an appropriate value."
The reason for the failure you are receiving is because the default ca certificates used in Mbed TLS are some test certificates, and you should set the trusted root CA certificate by calling `mbedtls_ssl_conf_ca_chain()` or `mbedtls_ssl_conf_ca_cb()`.
If you run the `ssl_client2` with `debug_level=4` parameter as well, yo uwill see that the root certificate of the server certificate chain is signed by `Starfield Class 2 Certification Authority`
You should set this CA's certificate (assuming you trust this CA), as a trusted certificate in the API.
In the sample application, it is done with the parameter `ca_file` or `ca_path`

**Comment by RonEld** [comment]
As the library targets embedded platforms, I wouldn't recommend you use all trusted CA certificates out there, as i
I would suggest you use only the trusted entities that your device will connect to. You should probably consult your security experts.
If you don't have memory constraints, you could consider using `/etc/ssl/certs/ca-certificates.crt` set by `openssl`

**Comment by neoniousTR** [comment]
I am asking for lowjs (www.lowjs.org), we have quite comfortable memory situation - and people expect the software to work just like Node.JS.

Thank you very much. This helps a lot.

**Comment by Dibyajyoti-08** [comment]
Sorry for a late reply but it will help people who are facing the problem right now that the CN is set to default local host(which the CN of the default certificate present in the mbedtls)so when you connect to the server you need to mention there certificate's CN hard-coded in order to work I was working for specific server so for me it's no issue but if need to visit multiple sites go to inspects of your browser and get the CN and mention it in the code
