### ISSUE TITLE
Updated schedule for mbedtls 3.0?

### ISSUE THREAD

**Issue by ffontaine** [ARMmbed/mbedtls#2951]
### Description
- Type: Question
- Priority: Minor

## Question

Do you have any updated schedule for the mbedtls 3.0 release that should have landed in June (https://tls.mbed.org/tech-updates/blog/working-towards-mbed-tls-3)?

The only updated information that I could find so far was from @Patater in https://github.com/ARMmbed/mbedtls/issues/2844: 
> the only split that has been made so far is to split the repos

I can fully understand that a change of this magnitude takes longer than originally planned but it would be nice to have an updated schedule. I'm especially interested in the possibility for mbedtls to have secure element supported out of the box (i.e. `MBEDTLS_PSA_CRYPTO_SE_C` integration).

**Comment by Patater** [comment]
Thanks for your interest in Mbed TLS. `MBEDTLS_PSA_CRYPTO_SE_C` is available for evaluation in https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.19.1 or our latest `development` branch.

An example tool using the ATECC608A secure element with Mbed OS is available at https://github.com/ARMmbed/mbed-os-example-atecc608a/

**Comment by ffontaine** [comment]
Thanks for these links and for your prompt answer, it is very much appreciated :-)

**Comment by ffontaine** [comment]
After checking these links and trying to update the ssl_client2 program, I find out that most of the SE operations including key derivation are not implemented yet in mbed-crypto (as it can be seen by the usage of `psa_get_transparent_key` instead of `psa_get_key_from_slot` in `psa_key_derivation_input_key`). It seems that this enhancement is already traced in https://github.com/ARMmbed/mbed-crypto/issues/219. Do you know when it will be implemented?

**Comment by gilles-peskine-arm** [comment]
Hi @ffontaine,

Since Mbed TLS is now a TrustedFirmware project, we have a public [roadmap](https://developer.trustedfirmware.org/w/mbed-tls/roadmap/).

The meaning of “Mbed TLS 3.0” has always been a bit fuzzy, but secure element support is not directly related to any of the definitions of Mbed TLS 3.0. It's something we've been working on for a while.

In the past few months, we've worked on a new interface for secure element drivers (partly to bring them closer to accelerator drivers). The latest version of the specification at this time is in https://github.com/ARMmbed/mbedtls/pull/3542. We're also working on implementing this interface. You can track our progress under [“Unified driver interface: API design and prototype” on our epic board](https://github.com/ARMmbed/mbedtls/projects/2#column-8543266).

It will take a long time to support secure elements everywhere. We're prioritizing partly based on what people are asking us, and partly based on what people are willing to contribute. So if some feature is particularly important to you, let us know, or even better, help us make it. Key derivation is currently low on the priority list, partly because it isn't fully clear how to design it, and we don't have a date for that feature at the moment.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because it isn't a bug or a feature request. We can continue the conversation even on a close issue.
