### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by Prostyle1337** [ARMmbed/mbedtls#2959]
Hey currentlich a Memory leak is occuring at  

fix_negative()->
mbedtls_mpi_sub()->
mbedtls_mpi_free

it tries turn return pointer, which have not been allocated. 

**mbed TLS build:**  
2.11.3
FreeRTOS
STM32 CortexF7

**Comment by Prostyle1337** [comment]
Okay updated mbed tls to newest version, problem ist still there!

**Comment by RonEld** [comment]
Hi @Prostyle1337 
Thank you for your information!

I have a couple of questions:
1. What is this `fix_negative()` function?
2 What pointer is being freed? Do you have a full flow?
3. Could you share a sample code of your failure?

In addition, note that the `bignum` module is part of the crypto project, and this should be tracked in the [crypto repository](https://github.com/ARMmbed/mbed-crypto/issues)

**Comment by gilles-peskine-arm** [comment]
We test our code with ASan, MSan and Valgrind, so we know that for our test code, there is neither a memory leak nor a use after free. It is of course possible that something bad happens with data or call sequences that don't arise in our test. But to identify and fix the problem, we need to know how to reproduce it.

I'm closing this issue because it contains no information on how to reproduce the problem. If you can reproduce it on your end, please include **complete source code and input files** so that we can run the code and reproduce the problem.
