### ISSUE TITLE
Controlling DTLS session duration

### ISSUE THREAD

**Issue by endian-benjamin** [ARMmbed/mbedtls#2990]
## Question

Is there a config option/session init parameter for requesting a particular session keepalive/timeout duration or is this up to the server? We're getting timed out very quickly by the server and I am wondering if there is anything we can do to control this on the device side.

**Comment by hanno-arm** [comment]
Hi,

Could you provide more details please? What's the context and the intended/desired vs. observed behavior? 

It's not clear to me e.g. whether you're looking at handshake timeouts, timeouts after handshake completion, or lifetime of sessions after connection closure for the purpose of session resumption.

Regards,
Hanno

**Comment by endian-benjamin** [comment]
Apologies -- what I'm referring to is the time after which the server discards the session following an idle period after its been established via a successful handshake. I.e. `HANDSHAKE -> BULK MESSAGE -> IDLE PERIOD -> DISCARD SESSION`

**Comment by hnrkp** [comment]
I would guess that's up to the server. Since it's DTLS you'll need to do your own keepalive from the application side, since UDP doesn't have much in the concept of connection states.

**Comment by endian-benjamin** [comment]
@hnrkp Thanks! So the keepalive duration isn't something that is negotiated between server/client during the handshake at all? It's a server config?

**Comment by hnrkp** [comment]
Keepalive is not part of DTLS afaik. So generally, no. Your application might negotiate something with the server. And if you've set the mbedtls_ssl_conf_read_timeout() to something non-zero (might sometimes be needed if you have clients that are somewhat slow during handshake) you might want to keep that timeout high and handle timeouts from your application. But it's impossible to give a general answer to your question without knowing more about your particular setup.

Usually though I would expect that it's the application implementation rather than mbedtls that would drop the session, and be responsible for any keepalives. Usually, if this is a real-world application (and especially so if by 'device' you mean some IoT device between some cable router or such) on the ipv4 internet then you probably want something like a 28s ping/pong keepalive to keep NAT states alive in router(s) along the way. But that's no different from any other UDP application.

**Comment by endian-benjamin** [comment]
It makes perfect sense now that you frame it like that, thanks a ton Henrik
