### ISSUE TITLE
AES 128-bit GCM from mbedtls library truncates randomly

### ISSUE THREAD

**Issue by ONLYstcm** [ARMmbed/mbedtls#3039]
### Description
- Type: Bug
- Priority: Blocker

---------------------------------------------------------------
## Bug

**OS**  
ESP32

**mbed TLS build:**  
Arduino OS version: 1.0.4
Additional environment information: Implemented from this [library](https://github.com/espressif/arduino-esp32)

**Expected behavior**   
```
Original: I come from @ tribe 0f head-hunters, so ! will n3v3r need @ $hrink.
Encrypted: :t4i⸮⸮⸮⸮⸮*⸮q٬8>⸮⸮⸮J⸮⸮>⸮⸮[E⸮o⸮a⸮⸮:⸮_⸮lu⸮ۡ⸮jh2h@⸮⸮⸮⸮⸮6
Decrypted: I come from @ tribe 0f head-hunters, so ! will n3v3r need @ $hrink.
```

**Actual behaviour**  
```
Original: I come from @ tribe 0f head-hunters, so ! will n3v3r need @ $hrink.
Encrypted: ⸮⸮⸮=_+<⸮⸮6⸮⸮⸮⸮⸮_4⸮⸮&6⸮@W⸮⸮Q⸮Lr.u⸮
Decrypted: I come from @ tribe 0f head-hunters, so !
```
**Arduino Code**  
```
// Reference for this:  https://tls.mbed.org/api/gcm_8h.html
#include "mbedtls/gcm.h"

mbedtls_gcm_context aes;
char * key = "cRfUjWnZr4u7x!A%";
char tag[17], tag2[17];
  
void setup() {
  Serial.begin(115200);
  while(!Serial);
}

void loop() {
  delay(2000);
  
  char *text = "I come from @ tribe 0f head-hunters, so ! will n3v3r need @ $hrink.";
  Serial.print("\n\nOriginal: ");
  Serial.println(text);
  
  
  char iv[13];
  for (uint8_t i = 0; i < 12; i++) {
    iv[i] = random(1,255);
  }
  iv[12] = 0;

  int ret = 0;

  
  char encrypted[256] = {0};
  mbedtls_gcm_init(&aes);
  mbedtls_gcm_setkey(&aes, MBEDTLS_CIPHER_ID_AES, (const unsigned char*) key, strlen(key) * 8);
  Serial.println(mbedtls_gcm_starts(&aes, MBEDTLS_GCM_ENCRYPT, (const unsigned char*) iv, strlen(iv), NULL, NULL));
  Serial.println(mbedtls_gcm_update(&aes, strlen(text), (const unsigned char*) text, (unsigned char*) encrypted));
  Serial.println(mbedtls_gcm_finish(&aes, (unsigned char*) tag, 16));
  //int ret = mbedtls_gcm_crypt_and_tag(&aes, MBEDTLS_GCM_ENCRYPT, strlen(text), (const unsigned char*) iv, strlen(iv), NULL, 0, (const unsigned char*) text, (unsigned char*) encrypted, 16, (unsigned char*) tag);
  mbedtls_gcm_free(&aes);
  Serial.print("Encrypted: ");
  Serial.println(encrypted);
  Serial.print("Tag: ");
  for (uint8_t i = 0; i < strlen(tag); i++){
    Serial.print(tag[i], HEX);
    Serial.print(",");
  }
  Serial.println();

  
  char decrypted[256] = {0};
  mbedtls_gcm_init(&aes);
  mbedtls_gcm_setkey(&aes, MBEDTLS_CIPHER_ID_AES, (const unsigned char*) key, strlen(key) * 8);
  Serial.println(mbedtls_gcm_starts(&aes, MBEDTLS_GCM_DECRYPT, (const unsigned char*) iv, strlen(iv), NULL, NULL));
  Serial.println(mbedtls_gcm_update(&aes, strlen(encrypted), (const unsigned char*) encrypted, (unsigned char*) decrypted));
  Serial.println(mbedtls_gcm_finish(&aes, (unsigned char*) tag2, 16));
  //ret = mbedtls_gcm_auth_decrypt(&aes, strlen(encrypted), (const unsigned char*) iv, strlen(iv), NULL, NULL, (unsigned char*) tag, strlen(tag), (const unsigned char*) encrypted, (unsigned char*) decrypted);
  mbedtls_gcm_free(&aes);
  Serial.print("Decrypted: ");
  Serial.println(decrypted);]
  Serial.print("Tag2: ");
  for (uint8_t i = 0; i < strlen(tag2); i++){
    Serial.print(tag2[i], HEX);
    Serial.print(",");
  }
  
}
```

## Issue
I'm trying to use AES 128-bit GCM from mbedtls library for string encryption. The IVs are random but I noticed that some of the encrypted strings are truncated, even if I use the same text and key. I've tried looking into the ESP32 arduino mbedtls library but strangely I can't find the source code only header files?

**Comment by yanesca** [comment]
Hi @ONLYstcm , `strlen()` works on `\0` terminated strings, but might truncate binary data. You can calculate the ciphertext length from the length of the plaintext: it is the length of the plaintext rounded up to the next multiple of 16.

**Comment by gilles-peskine-arm** [comment]
Hi @ONLYstcm,

You're using `strlen` on binary data: `strlen(key)`, `strlen(encrypted)`. But `strlen` can only work on text strings, not on binary data. When you pass it on binary data, it stops at the first null byte. Since each byte in the encrypted data has a 1/256 chance of being null, varying randomly depending on the IV, the call to `mbedtls_gcm_update` stops at some random position.

You need to keep track of the size of binary data. For GCM, the size of the output to `update` is equal to the size of the input. You need to remember this size alongside the encrypted data.

You need to fix the same issue with the key and IV, otherwise they may be truncated depending on the output of the random generator.

Note also that you should never use non-cryptographic randomness in cryptography code. Don't use the standard library `random`. Mbed TLS provides a random generator that's suitable for cryptography, see the [knowledge base entry](https://tls.mbed.org/kb/how-to/add-a-random-generator) for how to use it.

I assume that this is just an example. In the real world, the key should be generated randomly as well, and then stored securely, not embedded in the code.

If you're learning how to write code that uses cryptography, I recommend the [Cryptopals challenges](https://cryptopals.com/). They're little programming exercises that let you discover things progressively. Start at the beginning and stop (or pause) when things go beyond what you need.
