### ISSUE TITLE
Inconsistent use of priority dependencies in library/Makefile

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#3109]
### Description
- Type: Bug
- Priority: Minor

## Bug

**mbed TLS build:**  
Version: after the merge of https://github.com/ARMmbed/mbedtls/pull/3085
Build system: (GNU) make

In `library/Makefile`, in the section about `libmbedcrypto` we have this line:
```
libmbedcrypto.$(DLEXT): | libmbedcrypto.a
```
that has no equivalent for the other libraries (x509, tls). This inconsistency should be resolved one way or the other.

Note: this line was introduced in 8af3923

**Comment by gilles-peskine-arm** [comment]
As far as I understand, this line was needed because the rule to build `libmbedcrypto.$(DLEXT)` built a file called `$(CRYPTO)libmbedcrypto.$(DLEXT)`. Now that there is no `$(CRYPTO)` anymore, we can get rid of this complication.

**Comment by mpg** [comment]
@AndrzejKurek Since you introduced that line, perhaps you remember more details and could chime in about whether you think it's still needed or not, now that there is no `$(CRYPTO)` anymore?

**Comment by AndrzejKurek** [comment]
This problem was present when building shared targets with parallel jobs enabled. The mentioned line made it so that the .o files weren't built twice due to two potentially different dependencies ( `libmbedcrypto.$(DLEXT)` vs `$(CRYPTO)libmbedcrypto.$(DLEXT)`). The easiest way to test it now would be just to run these shared builds with parallel jobs enabled, without these lines, and see how it behaves (it was quite consistent in reproduction). I'll do that today and let you know.

**Comment by AndrzejKurek** [comment]
I tested it locally and it works fine. 
Created a PR here: https://github.com/ARMmbed/mbedtls/pull/3131
We'll see how the CI handles it (for example with Windows shared targets).
