### ISSUE TITLE
SSLv3 failing in basic-build-tests.sh on development

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3179]
In the `development` branch, `basic-build-test.sh` runs `compat.sh -m ssl3`. This makes sense since SSLv3 is deprecated but still a tested feature and the job of `basic-build-test.sh` is to measure test coverage.

`basic-build-test.sh` uses `config.py full`, which since https://github.com/ARMmbed/mbedtls/pull/2236 no longer includes `MBEDTLS_SSL_PROTO_SSL3`. So all the `ssl3` compat test cases fail.

I think that the job of `config.py full` is to include everything that fits together, even deprecated modules. For example we still include MD4 in that configuration.

**Comment by mpg** [comment]
> I think that the job of config.py full is to include everything that fits together, even deprecated modules.

I think that definition makes sense, but the fact that we're currently leaving `MBEDTLS_DEPRECATED_WARNING` enabled in `config.py full` seems to indicate otherwise.
(IIRC, I removed SSLv3 from full because before I did I got CI failures from `DEPRECATED_WARNING`.) So we should agree on a definition and document it explicitly instead of relying on an implicit definition though the fact that `DEPRECATED_WARNING` is _not_ listed in the things excluded from full...

> For example we still include MD4 in that configuration.
I don't think MD4 and SSLv3 are in the same situation: MD4 is "deprecated" as is "there's a doxygen warning against using it, but no compiler warning, and it's going to stay in future versions", while SSLv3 is deprecated as is "there might be a compiler warning or error, and the code will be removed in Mbed TLS 3.0".

Note: I'm not saying this difference means we should keep excluding SSLv3 from full, I'm just saying the parallel seems relatively weak to me - but there might stronger arguments for including SSLv3 in full.

**Comment by mpg** [comment]
I just realised, the current implicit definition is inconsistent: I don't see how it makes sense to exclude `DEPRECATED_REMOVED` from `config.py full` but leave `DEPRECATED_WARNING`... it means that if you also include deprecated stuff in config-full then you'll be able to build, but no with `-Werror`? That's really not something we want.

**Comment by gilles-peskine-arm** [comment]
> I don't think MD4 and SSLv3 are in the same situation

With respect to users of the library who just care about their code continuing to run, they are in different situations. But with respect to users who wonder whether they should keep using the feature, not really. Both are obsolete, weak cryptography. The only reason we're keeping MD4 is that it's zero maintenance.

**Comment by mpg** [comment]
> The only reason we're keeping MD4 is that it's zero maintenance.

**Comment by gilles-peskine-arm** [comment]
> I just realised, the current implicit definition is inconsistent

Yes. I think we have several ideas about what “full” means, and we should probably split it. There are at least two:

* Enable all the features, even ones that break API compatibility or that most users would consider bloat. But don't enable things that users shouldn't be using (scheduled for removal, weak or experimental).
* Enable all the features that can fit together, just to test that they all work together.

**Comment by mpg** [comment]
I did some archeology but unfortunately the commit that excludes `DEPRECATED_REMOVED` from `config full` while leaving `DEPRECATED_WARNING` - ea0920f0799272ca9c5cc7e76fe525d78d55d170 - gives no explanation (and worse, it does so in a commit that's ostensibly about something else...) so history won't help us here. Perhaps I just forgot to exclude `DEPRECATED_WARNING` as well because we didn't have any build with full and `-Werror` at that time.

I agree that there are (at least) those two possible meanings of "full", but I'm not sure the first one would be really useful. We have never provided something like that, never heard someone asking for it, and creating and maintaining it would take a small but non-zero amount of effort. Also, except for things that break compatibility (of which CMAC is I think the only example, and I'm not even convinced it couldn't have been avoided, but that's a different discussion), this would be very close to the default config, so would probably provide very little value.

I'm inclined to just define from now on that `full` means all the features that can fit together, just for testing. And perhaps (in the development branch) rename it to `test_full` to make it even more explicit (and as a side-effect, if someone was using it, they'll probably complain and then we can then have a discussion to learn why they we using it, and if we should provide something like full-for-users).

**Comment by mpg** [comment]
Just noticed while reviewing an PR that we have an `all.sh` component that tests with "full config + DEPRECATED_WARNING" even though it's already in full config, so apparently we were really confused about that.

**Comment by gilles-peskine-arm** [comment]
Fixed by [explicitly enabling `MBEDTLS_SSL_PROTO_SSL3` in `basic-build-test.sh`](https://github.com/ARMmbed/mbedtls/pull/3181), at least for the time being. We may change `config.py full` later.
