### ISSUE TITLE
Relicense the LTS branches

### ISSUE THREAD

**Issue by yanesca** [ARMmbed/mbedtls#3212]
## Background

Eventually we would like to move to Apache 2.0 licence, but for now we still have a commitment to ship the LTS branches under GPL licence as well. Historically the library used to be relicensed during release process and both versions were published on the website. As we move away from the old website we would like to be able to release fully on github.

## Task breakdown

- [x] Write a script or modify the release script to change the licence of LTS branches to dual Apache/GPL, raise PRs with the relicensed library and get them merged.
- [x] When done, update the library download pages with a link and an announcement to direct visitors to the new location. (On editing the website see the Release Process confluence page.)

**Comment by danh-arm** [comment]
Strictly speaking, the LTS branches have already been re-licensed so this task is really about updating the source files to reflect that re-licensing.

**Comment by yanesca** [comment]
@bensze01 I have just noticed that the source code is available on the website as well. Since we won't be updating it, this could potentially cause some confusion and difficulties for users. Do you think you could raise a PR to remove the page and the references to it?

Here is the page in question:
https://tls.mbed.org/source-code

**Comment by bensze01** [comment]
@yanesca The source code pages already link to the github, although the source code itself that is displayed does get loaded from the server itself. I could very easily change it, so that the source gets loaded from github, or just remove the source display entirely and leave everything else as-is.

**Comment by bensze01** [comment]
[Some pages](https://tls.mbed.org/pbkdf2-source-code) seem to be broken though, I guess the algorithms they cover may have been removed

**Comment by danh-arm** [comment]
I think it's probably easiest to leave the page there but remove everything below "Browsing the library source" so that no source from the website is displayed. Anyway, I see this as nice to have and out of scope of this task. If it takes any significant time then please create a new task.

**Comment by yanesca** [comment]
I agree, removing everything below "Browsing the library source" should be enough and it is probably the easiest way to do it.

**Comment by bensze01** [comment]
@yanesca The source of the headers also seems to be available [through the doxygen documentation](https://tls.mbed.org/api/files.html)

**Comment by yanesca** [comment]
@bensze01 Nice catch! The generated documentation itself is version dependant too and we have no intention to update the website for each release.

I suggest we remove the doxygen documentation from the site and leave instructions on generating them from source on the documentation page.

**Comment by dsommers** [comment]
Just so you're aware of this move, it is quite GPL unfriendly.  In the OpenVPN project we have had PolarSSL and later moved to mbed TLS support since OpenVPN 2.3.  This move makes it basically impossible to continue providing mbed TLS as an alternative SSL/TLS library backend, due to [license incompatibilities between GPLv2 and Apache 2.0 licenses](https://www.gnu.org/licenses/license-list.en.html#apache2).

I don't know how many other GPLv2 projects which depends on mbed TLS, but this move puts also these projects in a difficult position.

The OpenVPN project has already started to look into how to best support the mbed TLS library.  Unless this changes again, at some point this will result in OpenVPN removing support for mbed TLS completely.

The [OpenVPN-NL](https://openvpn.fox-it.com/) project run by Fox-IT is now probably the most widely used OpenVPN version shipping with mbed TLS by default.
