### ISSUE TITLE
need another version of mbedtls_x509_crt_ca_cb_t for verify cert only

### ISSUE THREAD

**Issue by okhowang** [ARMmbed/mbedtls#3339]
### Description
- Type: Feature Request
---------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
we have to bundle a hardcode CA list in app which is too bigger (200KB+)
because we can't read system root cacerts on iOS currently

**Suggested enhancement**  
provide another version callback for ca, for example
```c
typedef int (*mbedtls_x509_crt_ca_cb_t)( void *p_ctx,
                                         mbedtls_x509_crt const *child);
```
when cert is verified, return 0.
callback is only input certs and output verify result.
just like openssl's [verify_callback](https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_set_verify.html)
we can use it to wrapper ios API for verify ca with system's cacerts without bundled cacerts

**Comment by hanno-arm** [comment]
Hi @okhowang,

The CA callback was introduced precisely to handle situations like the ones you describe, in which storing the set of trusted CAs in the linked list format used by Mbed TLS isn't acceptable.

Instead, you can now use the callback 
```c
typedef int (*mbedtls_x509_crt_ca_cb_t)( void *p_ctx,
                                         mbedtls_x509_crt const *child,
                                         mbedtls_x509_crt **candidate_cas );
```
to offload the _search_ for a CA signing a given certificate. The verification itself is still done in Mbed TLS, which is intentional.

Please consider using this feature to search through your 200Kb+ of CA CRTs and only return the only that is deemed suitable to sign the given child CRT.

There are two further alternatives, which both involve more work and are more error prone:
1. Use optional verification and verify yourself. This should be the last resort. 
2. Stick to mandatory verification, but don't register any trusted CAs and instead use the verification callback concept (https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/x509_crt.h#L664-L670) to manually search for a trusted CA for the top of the CRT chain _after_ Mbed TLS has completed its verification. 

Cheers,
Hanno

**Comment by okhowang** [comment]
```c
typedef int (*mbedtls_x509_crt_ca_cb_t)( void *p_ctx,
                                         mbedtls_x509_crt const *child,
                                         mbedtls_x509_crt **candidate_cas );
```
using this callback has a condition that we HAVE certs. but on iOS, there is no way to get system's root certs. so we must hardcode some third-party root certs (like mozilla's) in out program. It's a little different with Apple's.
It can be resolved if there is a callback for verify peer cert only(not provide root certs for mbedtls to verify peer cert).

**Comment by hanno-arm** [comment]
Hi @okhowang,

Have you considered the other options I mentioned?

Regards,
Hanno

**Comment by okhowang** [comment]
the other options means this?
> 1. Use optional verification and verify yourself. This should be the last resort.

does it means that I will do as below ? 
1. connect tls with authmode `MBEDTLS_SSL_VERIFY_OPTIONAL`
2. after handshake, call `mbedtls_ssl_get_peer_cert` to get peer cert
3. call system's cert verify function with peer cert from `mbedtls_ssl_context`

**Comment by danh-arm** [comment]
In general questions like this should be asked on the list (https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls). Given Hanno has not responded for 10 days, I'm closing here.
