### ISSUE TITLE
DTLS handshake does not queue out of order messages

### ISSUE THREAD

**Issue by brycekahle** [ARMmbed/mbedtls#335]
I'm using mbedtls to implement both a DTLS client and server. I just experience the scenario where two Handshake messages arrived out of order. The server rejected the message instead of queuing the message as required by the spec (https://tools.ietf.org/html/rfc6347#section-3.2.2).

Because the client does not currently support combining handshake messages of the same flight into a series of DTLS fragments (#334), this is a critical issue.

I'm happy to help with a PR, but some direction on implementation would help.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-530

**Comment by mpg** [comment]
This is on our roadmap. Help would be appreciated since you're offering it :)

Some ideas on how to implement that (just off the top of my head, I might be wrong):

- In `ssl_prepare_handshake_record()` at `dropping out-of-sequence message`, the test should be refined to check if the message is from the future or the past: messages from the past will still be dropped, but messages from the future need to be copied in some area before
- We want to be able to set a limit on the memory used for storing future messages, and drop them when this limit is reached. Otherwise this gives attackers an obvious DoS vector.
- In `ssl_read_record()` near the top, after we check if `in_hslen` is zero, we should also check if we have the next expected handshake message (not just any one, the expected one) in our temporary storage area, and if so, copy it to the input buffer, remove from the list, and move on as if we just read those bytes from the network.

I hope it makes sense. Feel free to ask for clarifications, disagree about the design, etc. :)

Also, I'd like this whole feature to be optional controlled by a flag in `config.h` (as usual).

**Comment by mpg** [comment]
For the record, let me clarify one point about the spec: the section you cite (3.2.2) is part of the overview and is not using normative language to specify requirements. The last paragraph of section 4.2.2 has more explicit text on what is required and what is not:

    If the sequence number is greater than
    next_receive_seq, the implementation SHOULD queue the message but MAY
    discard it.  (This is a simple space/bandwidth tradeoff).

So our current behaviour, while suboptimal in your particular use case, it explicitly allowed (though not recommended) by the DTLS specification.

**Comment by sbutcher-arm** [comment]
A series of PR's by @hanno-arm and @mpg to introduce this feature was recently merged, which is described in #1951. This PR can now be closed and the feature was shipped in [`mbedtls-2.13.0`](https://github.com/ARMmbed/mbedtls/releases/tag/mbedtls-2.13.0).

Thanks to @brycekahle for your efforts! I'm not sure how much of your work was used in what because a much bigger feature than just this PR, but it certainly helped and took us forwards!
