### ISSUE TITLE
Configurations required for AWS connection

### ISSUE THREAD

**Issue by ahmedwahdan** [ARMmbed/mbedtls#3356]
I'm using LwIp with mbedTLS (generated by STMCubeMx)
I have two issues:
1- Server certificate verification error.
I set authmode to optional to bypass this point for now, but I don't know what cause the fail.
2- Key exchange step fails
The Key exchange step fails because of key decrypt error.
mbedtls_pk_verify() returned -17040 (-0x4290)

**OS**  
windows

**mbed TLS build:**  
Version: 2.16.2

https://gist.github.com/ahmedwahdan/8237567d5593d278a74e5d8a6b842772

What is the actual configuration required to connect to AWS IOT for mutual authentication.

**Comment by gilles-peskine-arm** [comment]
Please use the `strerror` utility from the Mbed TLS source tree to look up the meaning of error codes.
```
programs/util/strerror -17040
Last error was: -0x4290 - RSA - The public key operation failed : BIGNUM - Memory allocation failed
```
So it looks like unfortunately you don't have enough memory on this platform for what you want to do. If you can, switch from RSA to ECDSA: elliptic curve operations tend to use less memory.

There's no way to know why the certificate verification is failing without seeing detailed logs. You can enable detailed logging in SSL with `mbedtls_debug_set_threshold(3)`. The most obvious thing to check is: did you configure the root CA correctly (`mbedtls_ssl_conf_ca_chain`)?

Note that Mbed TLS 2.16.2 is old and we have made bug fixes since then. Please upgrade to the latest 2.16.x release (currently 2.16.6).

Regarding the configuration to connect to AWS IOT, I'm afraid the Mbed TLS team can't help you with that. We aren't particularly knowledgeable about AWS. You can ask on the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls) where other users of the library may be able to answer you. Do post as much information about your system as you can.
