### ISSUE TITLE
Make master the default branch

### ISSUE THREAD

**Issue by danh-arm** [ARMmbed/mbedtls#3370]
### Description
- Type: Enhancement

---------------------------------------------------------------
## Enhancement

Currently the default branch is `development`. The `master` branch points to the last release (actually the last LTS release - see #3231). There no longer seems to a good reason for this distinction so this task is to make the `master` branch the default.

A migration plan is needed to ensure `development` is not immediately broken/removed.

Possible solution:

- [ ] Announce plan on list.
- [ ] Write script to regularly fast forward `development` to `master`.
- [ ] Wait for a release so that `master` and `development` are the same.
- [ ] Block any PRs from being merged to `development`.
- [ ] Update CI to use `master` instead of `development` everywhere.
- [ ] Make `master` the default branch.
- [ ] Enable above script.
- [ ] Manually update target branch of in-flight PRs to `master` (or ask owner to).
- [ ] After agreed time, remove `development`.

**Comment by mpg** [comment]
Note: if it turns out there is indeed a need for a branch that tracks releases (as Gilles suspects in #3231), it doesn't need to be called 'master' and could have a more specific name such as 'latest-release'. I'm not saying I think it's needed (I don't really have an opinion on that), I'm just saying even a release-tracking branch was needed, it still wouldn't prevent us from making 'master' the default branch.

**Comment by gilles-peskine-arm** [comment]
@mpg You'd know this better than me, but the mbedtls branch structure looks like [Git flow](https://nvie.com/posts/a-successful-git-branching-model/), which suggests `master` as the branch for releases and `develop` as the branch for new stuff.

The author of Git flow suggests to use [GitHub flow](https://guides.github.com/introduction/flow/) instead for code that is continuously released. I'm not sure what the differences are, really, other than the absence of a “release” branch in the GitHub flow. Both flows are based on merging feature branches anyway.

We maintain `development` in a releasable state, but we still have formal releases which, in principle, are tags on `development`. I think it makes sense to keep the Git-flow-like model with `master` as the branch for the latest formal release, and `development` for the latest stuff.

One reason to keep a distinction between `development` and `master` is that if we introduce an API into `development` and then realize that the API should change, we do allow ourselves to change it: until something has been in a numbered release, we don't feel bound by backward compatibility. A user of the library who wants to get the latest version should follow the release branch, not the daily-merges branch, regardless of how we call them.

Therefore:

* I strongly disagree with removing the “latest numbered release” branch. We _accidentally_ removed this branch when we made `master` follow 2.16 instead of the latest releases. There was a semi-good reason not to update `master` in that it introduced a dependency on a submodule which broke a lot of automation, but since 2.22 this reason is no longer relevant. So regardless of the names, we should fix #3231 ASAP.
* I weakly disagree with changing the branch names because it seems like a gratuitous change from our historical practice, and because it would deviate from the still fairly popular Git-flow convention.

**Comment by mpg** [comment]
> You'd know this better than me

Actually I don't. Though I'm familiar with the general thinking behind those flows, I wasn't aware of the specific branch names they recommended.

While following documented flows has value, I don't think we should make a decision based purely on that. Perhaps we should take a step back and make it clear what problem we're trying to solve here - every migration has a cost and we should make sure the upsides are enough to justify that cost.

Here I think the problem we're trying to solve is to reduce the amount of surprise for new contributors. Intuitively I tend to think that most contributors nowadays are more used to the default branch for their contributions being named 'master'. However, I'm not sure there is evidence supporting this: recently when I surveyed old PRs, out of about 100 community PR only 1 was mistakenly based on 'master' rather than 'development'. That's a fairly low error rate. Of course what's harder to quantify than the error rate is the amount of confusion that didn't result in a mistake but still created friction for contributors.

At this point I no longer really have a clear opinion about whether we should make master the default where PRs are merged, or keep names as they are.

**Comment by gilles-peskine-arm** [comment]
I think most contributors don't pay attention to the target branch name when they make a pull request, and thus end up with the default branch selected by GitHub, which we've configured to be `development`.

It's true that `master` is the most common default branch for development, which is an argument to switch to `master`+`release`. But is it a strong enough argument to 1. change the status quo 2. away from the less-relevant-than-it-used-to-be-but-still-somewhat-relevant Git-flow names?

**Comment by danh-arm** [comment]
If we accept the need for a branch that tracks the latest release, then I agree it's not worth changing the status quo. I'm not convinced of that need but we have more important stuff anyway so let's park this for now.

**Comment by gilles-peskine-arm** [comment]
@danh-arm I think we've decided not to do this, right?

**Comment by danh-arm** [comment]
Yes, I'll close this. I still think there's a case for renaming master to something that more clearly indicates what it is and is more BLM friendly, but let's keep development as-is.
