### ISSUE TITLE
PSA: psa_aead_set_lengths 

### ISSUE THREAD

**Issue by kotegowder** [ARMmbed/mbedtls#3406]
What would be return value for psa_aead_set_lengths when ad_length=plainttext_length=0 ?

**Comment by gilles-peskine-arm** [comment]
`ad_length=plainttext_length=0` is not a special case. All algorithms support this length, so this function always returns `PSA_SUCCESS` in normal operation. Possible errors include `BAD_STATE` if the operation object was misused, and operational error such as `COMMUNICATION_FAILURE`.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue since it isn't a bug report or feature request. We prefer to direct support questions to the mailing list https://lists.trustedfirmware.org/mailman/listinfo/psa-crypto (for issues specifically about PSA crypto, there's also https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls for Mbed TLS in general).
