### ISSUE TITLE
Padding for ECB mode

### ISSUE THREAD

**Issue by malmaud** [ARMmbed/mbedtls#342]
I understand ECB is and should be rarely used, but is there a reason it still couldn't support padding as the other modes do, just for consistency? Some of my users have played around with the different modes just for pedagogical purposes and are left confused by why one mode should act differently than the others.

**Comment by mpg** [comment]
I'd be inclined to say that ECB acts differently because it is different: it shouldn't be used in real life to encrypt more than one block. IMO is shouldn't even be exposed in the cipher layer, except that we need it for build other modes on top of it (GCM, CCM, that are built on top of the cipher layer).

Does that make sense?

**Comment by malmaud** [comment]
Sure.

**Comment by RonEld** [comment]
I believe this question was answered, therefore closing it.
If you think it was wrongfully closed, please reopen
