### ISSUE TITLE
Mbedtls won't compile against Mbed 6.0

### ISSUE THREAD

**Issue by tatyanavolkova** [ARMmbed/mbedtls#3491]
- Type: Bug
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS | windows |

**mbed TLS build:**  
Version: 2.16.7 or git commit id  
OS version: 6.1.0  
Compiler and options:  standard Mbed Studio ARM compiler
Additional environment information:  

**Expected behavior**   

I expect the libraries to compile

**Actual behavior**  

During the compile I get such a weird error:

[Error] error.c@561,26: use of undeclared identifier 'MBEDTLS_ERR_SSL_BAD_CONFIG'
[ERROR] .\mbedtls\library\error.c:561:26: error: use of undeclared identifier 'MBEDTLS_ERR_SSL_BAD_CONFIG'
if( use_ret == -(MBEDTLS_ERR_SSL_BAD_CONFIG) )
^
1 error generated.

**Steps to reproduce**  

Try to complie Mbedtls on MBed OS 6

**Comment by gilles-peskine-arm** [comment]
If you're using the default configuration provided by Mbed OS and getting a compilation error on some platform, this would typically be an Mbed OS bug, not an Mbed TLS bug. If you're using a custom configuration, you need to post it. But either way, as far as I know, Mbed OS doesn't guarantee compatibility with older Mbed TLS versions. So this is not a bug at all: the version of Mbed TLS you're using is too old. Mbed OS 6 ships with Mbed TLS 2.22.0, and you should use the latest released version (2.23.0) since it includes security fixes. Mbed TLS 2.16 is a long-time support branch, which doesn't include all the features that current versions of Mbed OS need.
