### ISSUE TITLE
Cannot open include file: 'psa_constant_names_generated.c': No such file or directory

### ISSUE THREAD

**Issue by kks010** [ARMmbed/mbedtls#3524]
- Type: Bug
- Priority: Blocker | Major

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: 2.23.0

**Expected behavior** 
After taking the latest code and targeting the code to use updated build tools. I was expecting it to run after I build using (ctrl+shift+B).

**Actual behavior**  
I am facing an error after the build(ctrl+shift+B).

**Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'psa_constant_names_generated.c': No such file or directory	psa_constant_names	C:\Users\U376361\Documents\Visual Studio 2017\Projects\mbedtls-mbedtls-2.23.0\programs\psa\psa_constant_names.c	142**	

**Steps to reproduce**  
1. Just download the latest version 2.23.0.
2. Open visual studio 2019.
3. Open mbedtls solution file.
4. Retarget solution
5. After success, run the command **ctrl+shift+B**  while keeping the solution configuration as the release.
![image](https://user-images.githubusercontent.com/17687603/88773090-51c39980-d19f-11ea-8efa-a6fce254f184.png)

**Comment by kks010** [comment]
The main reason for using mBedTLS is I want to generate new CA Certs Verification Cert via using the following utilities:

**gen_key and cert_write**

Please help for the same.

**Comment by gilles-peskine-arm** [comment]
The Visual Studio solution is missing a call to `scripts/generate_psa_constants.py`. Note that you need Python 3.

Since `psa_constant_names_generated.c` doesn't depend on the configuration, and we've decided not to require Python as a build tool (only as a configuration and test tool), we should include it in the repository, like we already do for other generated files. It's somewhat similar in purpose to `error.c`.

**Comment by gilles-peskine-arm** [comment]
If Visual Studio lets you exclude `programs/psa/psa_constant_names.exe` from the build, this would be a workaround: `psa_constant_names_generated.c` is only needed to build `psa_constant_names.exe`.

**Comment by kks010** [comment]
Oh! Okay. 

Can you help me guide how to exclude **programs/psa/psa_constant_names.exe** from the build?

**Comment by gilles-peskine-arm** [comment]
Sorry, I have no idea. I do all my development on Linux... Each sample program is a separate `.vcxproj` file. Maybe you can exclude the `psa_constant_names` project?

**Comment by gilles-peskine-arm** [comment]
I'm labelling this "bug" because we have decided not to require Python for the build. So it's not just that the VS script doesn't do the whole build: the extra step is something we've decided not to require at all.

**Comment by kks010** [comment]
That's great! Good to hear about the fix.

Do you have any timeframe when the fix will be deployed?

**Comment by kks010** [comment]
Hi, I just tried with excluding psa_constant_names. I was successful in creating the build now.

The issue is now I need to use the gen_key and cert_write to run commands and create a new CA Certs Verification Cert.
But I am confused about how to execute them? 

As the executable file gen_key does not accepts commands and just closes.
![image](https://user-images.githubusercontent.com/17687603/88780426-9bfd4880-d1a8-11ea-9d01-eb54438553e9.png)

Can you help me with this as well?

**Comment by kks010** [comment]
It worked! You can ignore the above comment. Thanks for the help. 💯

**Comment by gilles-peskine-arm** [comment]
The programs in `programs` are mostly sample programs designed to show how to use the library. They aren't really designed for production use. They work, but they may not be convenient and may lack features.

All the tools use the command line to pass parameters, they don't read interactive input. You'll want to open a console window and type there.

Honestly I recommend OpenSSL tools to manage a CA, if only because you'll find a lot of tutorials on the web to do what you want.

**Comment by kks010** [comment]
Yeah! Actually I wanted it for the IOTHUB verification and mbedtls utility seems easier to use as compared to others for this. Just the setup part made me crazy. The rest is great! :)

**Comment by CameronNemo** [comment]
@gilles-peskine-arm I took the action you described in your comment and made a PR (#3709). Looks like Windows needs some special care.
