### ISSUE TITLE
Break the dependency of psa_crypto on software AES

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3675]
Currently `MBEDTLS_PSA_CRYPTO_C` depends on `MBEDTLS_CTR_DRBG_C` which depends on `MBEDTLS_AES_C`. The goal of this task is to remove or work around this dependency in order to allow using the PSA API with an AES accelerator.

Allowing the use of an alternate DRBG in PSA crypto is one way to do it, and is a desirable, but it is not a requirement of the present task. Note that [using HMAC_DRBG](https://github.com/ARMmbed/mbedtls/issues/3354) is not a solution for the present task: the goal here is to leverage an AES accelerator.

Some possible ways:

* Define a PSA DRBG abstraction and allow the PSA code to use it.
* Provide a way to plug an AES accelerator under `MBEDTLS_AES_ALT` that is at least sufficient for `ctr_drbg.c`.
* Allow `psa_generate_random` to call an RNG driver (not an entropy driver), which has the advantage of not going through the software CTR_DRBG, but the downside that it only benefits PSA interfaces (including symmetric key generation), not mbedtls implementations that use a DRBG (asymmetric key generation, blinding, non-deterministic algorithms).

**Comment by jdurkop** [comment]
@gilles-peskine-arm After looking into this some I think I am leaning toward an initial approach that provides a mechanism to use an AES accelerator under the MBEDTLS_AES_ALT. I agree that overall it seems like a better long term strategy to create a completely new DRBG for PSA, but I think for the initial task of allowing the use of AES accelerators it is a larger task that is not required. My plan for implementing the AES accelerator support is to create a flag called PSA_WANT_ALG_AES_DRBG, MBEDTLS_PSA_ACCEL_ALG_AES_DRBG, MBEDTLS_PSA_BUILTIN_ALG_AES_DRBG. Then in ctr_drbg.c making sure to place the BUILTIN guards around the software AES implementation pieces. This will allow the build tests to validate that if the accelerator is enabled, the core library can still be built. What type of support should this task provide under the MBEDTLS_AES_ALT that the accerlator will use?

**Comment by gilles-peskine-arm** [comment]
Sounds good. If you use the `MBEDTLS_AES_ALT` route, no change should be needed in `ctr_drbg.c`. The accelerator needs to support AES-128 and AES-256 (not AES-192) in the encryption direction (not decryption), in ECB mode (nor CBC, CTR, etc.). Or more prosaically: `grep mbedtls_aes_ library/ctr_drbg.c`

**Comment by jdurkop** [comment]
Ok, that's helpful. So if I define MBEDTLS_AES_ALT if the ACCEL_AES_DRBG is defined, and if that is not defined I just ensure that MBEDTLS_CTR_DRBG and MBEDTLS_AES_C are defined and do not worry about the BUILTIN_ALG_AES_DRBG usage. Then in aes.c I add in the skeleton versions for the mbedtls_aes_ functions used in ctr_drbg.c that can be filled in by the accelerator code when it is ready to be implemented.

**Comment by jdurkop** [comment]
@gilles-peskine-arm Just checking to see if my last comment was accurate.

**Comment by gilles-peskine-arm** [comment]
I'm not completely sure what you want to do. What driver entry point(s) would `MBEDTLS_PSA_ACCEL_ALG_AES_DRBG` enable? I actually thought you were starting from `psa_cipher_encrypt` and `psa_cipher_decrypt` for ECB, but then that wouldn't require a separate `ALG_AES_DRBG`.

**Comment by jdurkop** [comment]
I was approaching it from the point of what AES functionality is required for CTR_DRBG so that those functions could eventually have accelerated versions used instead of the current ones that exist in crt_drbg.c. It looks like the ctr_drbg.c uses mbedtls_aes_crypt_ecb, mbedtls_aes_free, mbedtls_aes_init, and mbedtls_aes_setkey_enc. I was thinking of guarding those calls in aes.c with MBEDTLS_PSA_BUILTIN_ALG_AES_DRBG. Then have alternate versions if MBEDTLS_PSA_ACCEL_ALG_AES_DRBG is defined. 

I am also unclear on an approach around psa_cipher_encrypt / decrypt. Those functions just use psa_cipher_setup() which does make a call into the psa_driver_wrapper but it seemed very generic and not tied to any specific algorithm. Not sure what items I would be trying to guard in this function that would help reduce code size based on an algorithm selection.

**Comment by gilles-peskine-arm** [comment]
Since the functionality would be specific to what CTR_DRBG needs (only one key size, only ECB, only encryption), it seems to me like it would be easier to add just enough supporting code inside `ctr_drbg.c`, rather than have to implement the exact interface in `aes.h`, even if it's a subset of the functions.

But whether the code is in `aes.c` or `ctr_drbg.c`, how would you implement (for example) `mbedtls_aes_crypt_ecb`? By calling `psa_cipher_encrypt`? Making a direct call into the driver is not possible since you don't know the function name: it's currently hard-coded in `psa_crypto_driver_wrappers.c`, but will soon be generated at compile time from the JSON driver description instead.

**Comment by jdurkop** [comment]
@gilles-peskine-arm Since it seems that the acceleration calls should be in the psa_crypto library, we might be better suited to find a solution that only requires changes to that file. Perhaps the other suggestion of creating a PSA wrapper for the crt_drbg funcdtionality in that file would give the appropriately flexibility and provide a guided path to the overall transition to the newer model. I could create a new psa_ctr_drbg_random() that will use the mbedtls_ctr_drbg_random() if no accelerator is present, and if one is present it can make the appropriate calls to the driver code in there.

**Comment by gilles-peskine-arm** [comment]
You'd need to replace `mbedtls_ctr_drbg_{init,seed,free}` as well. In terms of the number of functions to replace, I think all approaches will end up being roughly equivalent. I haven't looked deeply at which functions are easiest to replace. In terms of future-proofness, being able to use a different DRBG inside PSA is something we definitely want, independently of AES acceleration, so if it's as easy as another solution, replacing the DRBG in `psa_crypto.c` is preferable.

**Comment by gilles-peskine-arm** [comment]
I don't understand why merging #3882 closed this issue: I don't see a magic keyword in its description. #3882 is only the specification. The implementation that will resolve this issue is https://github.com/ARMmbed/mbedtls/pull/3895.
