### ISSUE TITLE
enable/disable ciphers on runtime

### ISSUE THREAD

**Issue by edsiper** [ARMmbed/mbedtls#371]
Is there a mechanism to enable/disable certain ciphers on runtime ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-578

**Comment by edsiper** [comment]
ping ^

**Comment by mpg** [comment]
If you're talking about SSL/TLS ciphersuites, I think the function is called `mbedtls_ssl_conf_ciphersuites()` in current version of mbed TLS. We also have functions to set the range of supported SSL/TLS version, and you can even set the list of ciphersuites per TLS version. Since 2.0.0, all relevant security parameters (list of elliptic curves, min size of RSA keys, hashes for signatures, etc) are configurable at runtime.

You might want to check the full list in [ssl.h](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h) or the HTML version generated by [doxygen](https://tls.mbed.org/api/ssl_8h.html). There are also [example programs](https://github.com/ARMmbed/mbedtls/tree/development/programs/ssl) that demonstrate how to use those functions; the most complete are `ssl_client2.c` and `ssl_server2.c` (because we use them for our automated tests).
