### ISSUE TITLE
Add a hook for vendors to declare pre-existing keys

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#3745]
System vendors may want to declare pre-existing keys, for example a root key in fuses or a factory-provisioned key in a secure element. The PSA API reserves a key id range for “the implementation” (`PSA_KEY_ID_VENDOR_MIN`..`PSA_KEY_ID_VENDOR_MAX`). Mbed TLS currently doesn't have a way to declare keys in this range. The goal of this task is to add a way for a system vendor to declare keys in this range and dispatch operations to these keys.

There is a mechanism for dynamically registering keys in a dynamically-registered secure element (`mbedtls_psa_register_se_key`). This mechanism overlaps with the intended use case for pre-existing keys: you can call `mbedtls_psa_register_se_key` during device provisioning. But for keys that are pre-existing (as in, no Mbed TLS code sees the device before these keys exist), this mechanism is often more complex than needed since it requires creating a provisioning step that only runs once to declare the pre-existing key.

The goal of this task is to define an interface that allows a system vendor (what Mbed TLS calls a platform) to define a small, generally static set of keys. Implementing this interface will be a separate task.

**Comment by stevew817** [comment]
How do you see this interface materialise? Any guidance from the team?

As far as I can see, `mbedtls_psa_register_se_key` is too resource-heavy to fulfill this purpose. If we change it to be able to register on compiled-in lifetimes in addition to dynamically-registered lifetimes, we'd be eating up non-volatile storage to declare it.

The other way I see to do this, would be extending the driver definition JSON for opaque drivers to declare those factory-provisioned keys in JSON, and subsequently convert them to static data structures in the wrappers file. But that would still require adding a hook to be able to somehow get a handle based off of which key from which driver you want to use. Or somehow convert that information directly into a handle/id (since the PSA spec went away from handles and is now openless).

Thoughts?

**Comment by stevew817** [comment]
I believe this issue was resolved by #4160 and thus can be closed. @gilles-peskine-arm ?

**Comment by gilles-peskine-arm** [comment]
Resolved by https://github.com/ARMmbed/mbedtls/pull/4160.
