### ISSUE TITLE
mbedtls_x509_crt_parse_der mishandles trailing data

### ISSUE THREAD

**Issue by inestlerode** [ARMmbed/mbedtls#377]
This started in the forum here:
https://tls.mbed.org/discussions/bug-report-issues/mbedtls_x509_crt_parse_der-mishandles-trailing-data

In mbed TLS 2.2.0 the mbedtls_x509_crt_parse_der function does not correctly handle a valid input followed by extra trailing data. It returns success (and a parsed structure), but then it includes the trailing data as part of the DER of the structure (it keeps the entire input buffer in the 'raw' field).

Then when the SSL stack uses this certificate to write out a Certificate handshake message it writes the extra trailing data out onto the wire.

The parsing function should be fixed to shrink the raw.len field down to the actual length of the X.509 DER (to not include the trailing data). (Actually it should probably hit the extra bytes with mbedtls_zeroize before the shrink since this is a private copy, we will lose knowledge of how many extra bytes there were, and the data might even be sensitive.)  This would prevent the SSL stack from sending out trailing junk onto the wire.

This can be reproduced by taking a valid DER X.509 certificate and appending extra data to it. Then using this certificate in the SSL stack you should be able to see the extra junk bytes on the wire in a packet capture

The motivation for fixing this:

I know of some embedded devices which store X.509 credentials in a fixed region of their flash (not in a file system) without separately tracking the length of the X.509 certificate since the ASN.1 is self describing in terms of its length. It just goes in the beginning of the region, and the whole region is then passed to the X.509 parser with no regard to the length of how much DER was actually written there.

Other libraries (OpenSSL) can do this round trip properly: parse the entire fixed region, extract the X.509 structure at the beginning, and reserialize it on the wire during the handshake correctly with only the DER (not any trailing data from the initial parser call).

The parser function in this case should trim the input buffer down if the library is counting on being able to use it verbatim to reserialize the object. The parser knows how long the outer SEQUENCE-OF is, so it clearly has enough information to make this adjustment. The caller cannot figure this out so easily (requires a fair amount of complexity of ASN.1 parsing to even extract the length of the outer tag).

Thanks,
Ivan

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-581

**Comment by NWilson** [comment]
Hi,

This sounds sensible.

Would it be possible also to add a corresponding  comment to the
documentation in the header file: "The returned certificate may not have
fully consumed the input buffer; if trailing data is not expected the
caller must check for this case by testing whether the x509_crt's length is
less than the input buffer." Otherwise, the requirements on the caller
might not be clear, for the common case where the input buffer is believed
is to be an exact certificate.

**Comment by sbutcher-arm** [comment]
This issue has now been fixed in the development branch and in the mbedtls-2.1 branch.

**Comment by NWilson** [comment]
That's great!

Would it be possible to add the requested comment to the header file, since I personally would find it helpful to be reminded that the parser doesn't validate for trailing data. And, the PEM parser should arguably have that check added, to make sure that there aren't trailing bytes in the base64-encoded blob.
