### ISSUE TITLE
test.com is flagged as MBEDTLS_X509_BADCERT_NOT_TRUSTED because child is top of the chain

### ISSUE THREAD

**Issue by sithglan** [ARMmbed/mbedtls#380]
Hello,
current HEAD of mbedtls flags https://test.com and https://terminal.arbeitsagentur.de/ as BADCERT_NOT_TRUSTED. After adding a few debug messages I found out that according to a comment in the source code it is because the child is top of the chain. Could you please elaborate what is going on here? See attachment for commands to reproduce.
[reproduce.txt](https://github.com/ARMmbed/mbedtls/files/74217/reproduce.txt)

Cheers,
     Thomas

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-585

**Comment by mpg** [comment]
This might be a duplicate of #280 (the second bug in that issue, which came with the fix for the original issue). Can you check if this branch fixes it? https://github.com/ARMmbed/mbedtls/tree/iotssl-541-pathlen-bugfix Thanks!

**Comment by sithglan** [comment]
Hello,
I tried, but with the branch I get the same error:

(x1) [~/work/vlconnect/local/linux/bin] ./curl -sS https://test.com
Child is the top of the chain
curl: (51) Cert verify failed: BADCERT_NOT_TRUSTED

Cheers,
      Thomas

**Comment by jay** [comment]
For reference [here is a link](http://curl.haxx.se/mail/lib-2015-12/0113.html) to our discussion on the libcurl mailing list about this. As noted I get `BADCERT_NOT_TRUSTED` with most websites I try to access via https (chase, citibank, yahoo, example, etc) while using the curl [ca-bundle](https://github.com/bagder/ca-bundle), which is root CAs extracted from Mozilla.

Concerning test.com specifically, I monitored the 'Certificate' handshake protocol in Wireshark and I can see the certificates are coming in bottom up as one would expect. However note one of the server-sent intermediates is a legacy that has since transitioned to a root CA. The server sends these certs in this order:

'www.test.com' (issuer: Network Solutions DV Server CA 2)
'Network Solutions DV Server CA 2' (issuer: USERTrust RSA Certification Authority)
'USERTrust RSA Certification Authority' (issuer: AddTrust External CA Root)

We have in our root CA bundle the self-signed '[USERTrust RSA Certification Authority](https://github.com/bagder/ca-bundle/blob/86347ec/ca-bundle.crt#L3603)'. This is the root that was an intermediate. I mention this because we had an issue with OpenSSL not recognizing alternate chains, now [fixed](https://github.com/bagder/curl/commit/b8673bb). In that case though I could follow the server-sent chain as a workaround. In this case I cannot and therefore I do not know if that is the issue here. For example if I try to verify with the certificate 'AddTrust External CA Root' it still fails.

Perhaps it would be easier to first take a look at something less complex like example.com which has two server-sent certificates, in this order:

'www.example.org' (issuer: DigiCert SHA2 High Assurance Server CA)
'DigiCert SHA2 High Assurance Server CA' (issuer: DigiCert High Assurance EV Root CA)

We have in our root CA bundle the self-signed '[DigiCert High Assurance EV Root CA](https://github.com/bagder/ca-bundle/blob/86347ec/ca-bundle.crt#L1057)' but it returns with `BADCERT_NOT_TRUSTED`.

**Comment by sithglan** [comment]
Hello Manuel,
this morning the branch iotssl-541-pathlen-bugfix was merged which fixes the bug for me. I assume that it should have worked yesterday as well but because I had hardcoded my cert into curl I overwrote the normal ca certificate list which caused my test to fail. But now with plain mbedtls and plain curl it works. That is for sure.

Cheers,
     Thomas

**Comment by tangente-roja** [comment]
Hi @sithglan

I was just in the process of rebuilding curl to reproduce your problem and confirm the issue is fixed for you.

After studying the behaviour, I think this issue is a duplicate of #280 and as such the branch iotssl-541-pathlen-bugfix is the fix you need.

Thanks for confirming the fix works for you!

regards

Simon

**Comment by sbutcher-arm** [comment]
Hi @sithglan,

I was just in the process of rebuilding curl to reproduce the problem and confirm the fix for you.

After analysing the issue, I think the problem is a duplicate of bug #280 and the fix is the same - iotssl-541-pathlen-bugfix. Thanks for confirming this resolves your issue.

regards

Simon

**Comment by mpg** [comment]
@jay can you please confirm if you're still observing issues? If you do, could you open another bug about it? Thanks!

**Comment by jay** [comment]
@mpg I've built the version 2.2.1 that you released today in MinGW-w64 32-bit and everything appears to be working again. I've also sent an e-mail to the maintainer of their [PKGBUILD](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-mbedtls/PKGBUILD) script. Thanks guys!
