### ISSUE TITLE
cmake 3.19 will be a problem for mbedtls

### ISSUE THREAD

**Issue by peter-toft-greve** [ARMmbed/mbedtls#3801]
cmake (https://cmake.org/download/) is about to release version 3.19 
In https://github.com/ARMmbed/mbedtls/blob/development/CMakeLists.txt#L19 we have
cmake_minimum_required(VERSION 2.6)

That will soon be a problem - and with cmake 3.19 the user will get

```
CMake Deprecation Warning at CMakeLists.txt:19 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

```
I suggest to update e.g. to cmake_minimum_required(VERSION 3.15)
since 3.14 has "issues" and later releases are available in general.

**Comment by peter-toft-greve** [comment]
I have suggested https://github.com/ARMmbed/mbedtls/pull/3802

**Comment by peter-toft-greve** [comment]
and if you are into cmake ssues join the band in https://github.com/ARMmbed/mbedtls/pull/3790 which is also a problem :)

**Comment by d3zd3z** [comment]
#3788 demonstrates that 2.8.12 already doesn't work. I see two possibilities here:

1. Update the minimum cmake version to 3.15. This makes it clear that the 2.8.12 doesn't actually work, but we more explicitly lose support for these targets.
2. Work around the `target_sources` issue. If this can be solved, it would continue to be able to support platforms with cmake 2.8.12.

I suggest if we decided to do 2, CI should include a build done with cmake 2.8.12, otherwise, it will be fairly easy to keep introducing changes that break with this version of cmake.

**Comment by gilles-peskine-arm** [comment]
Our CI currently mostly runs Ubuntu 16.04, which has CMake 3.5.1, so switching to CMake 3.15 as the minimum supported version would be a pain for us maintainers as well as for users of the library. We aim to maintain compatibility with [popular long-time support distributions](https://github.com/ARMmbed/mbedtls/issues/2896#issuecomment-603471273), and for RHEL/CentOS 7 this means CMake 2.8.12.2 until June 2024.

**Comment by peter-toft-greve** [comment]
@gilles-peskine-arm  I would then encourage you to update the CI chain e.g. to Ubuntu 20.04.
CMake 3.14 and earlier have odd errors - especially for Windows. I foresee that you will - at some point - before June 2024 have a conflict beween long term support and supported Cmake. I will happily give a beer in Copenhagen if I am wrong :)
