### ISSUE TITLE
Compile on 16 bit gcc on 8086

### ISSUE THREAD

**Issue by toncho11** [ARMmbed/mbedtls#3810]
Hi,

What are the chances that mbedtls compiles with 16 bit GCC?
In partucluar this one: https://github.com/tkchia/gcc-ia16

mbedtls will be very helpful because old computers even if they manage to execute an old (console) web browser that is not enough because the world switched to https.

**Comment by gilles-peskine-arm** [comment]
No. ([We should document this more clearly](https://github.com/ARMmbed/mbedtls/issues/3323).)

I looked into this a couple of years ago.

1. The library doesn't build out of the box.
2. The library does build with a few minor changes.
3. Most parts of the library are functional.
4. **Some parts of the library are insecure**. There's a lot of code that assumes that `int` and `size_t` are 32 bits or larger and will cause integer overflows otherwise.

So you should not use Mbed TLS on a 16-bit platform, even if you manage to get the library to compile. More precisely, the I think the crypto and X.509 parts are ok with minor tweaks, but the TLS part would require a lot of work.

Making a 16-bit version of Mbed TLS would require a lot of work. The code needs to be reviewed, and non-16-bit-safe parts need to either be fixed or disabled. Furthermore, new work done in Mbed TLS would need to be reviewed for 16-bit-safety — we review new code under the assumption that the platform is 32-bit or wider. This won't happen unless someone contributes significant effort, and Arm isn't interested in contributing this effort.

Note that it's 16-bit `int` and `size_t` that are problematic. 16-bit pointers aren't a problem in themselves, and it should be possible to get a useful subset of the library to fit in 64kB code + 64kB data (but probably not 64kB of code+data). Fitting Mbed TLS plus a browser in 64kB+64kB is probably not realistic, however.

If you want to access the web from a 16-bit computer, consider using a proxy that translates HTTPS to HTTP.

**Comment by toncho11** [comment]
Last comment: security is not an issue in this case. I mean who would hack a 16 bit machine with such a limitted network and CPU speed? So it will be a bit easier I suppose.

**Comment by gilles-peskine-arm** [comment]
A 16-bit processor could be part of some ancient (or modern — there are still plenty of 16-bit microcontrollers) industrial control system. Security is definitely an issue.
