### ISSUE TITLE
armcc makefile build fails

### ISSUE THREAD

**Issue by terhei** [ARMmbed/mbedtls#386]
When building library with makefile using armcc and armar:
`make CC=armcc AR=armar WARNING_CFLAGS= lib`

following error is received:
 `AR    libmbedcrypto.a `
`Error: L6839E: One of the actions -[dmpqrtx] must be specified`

**Comment by mpg** [comment]
Apparently this is due to us not invoking tar with `-` in front of the options. I checked and both GNU ar and BSD ar (at least the one provided by OS X) accept the `-` syntax, which is (the only one) specified by [POSIX](http://pubs.opengroup.org/onlinepubs/009695399/utilities/ar.html), so I think adding a `-` would be a safe move.

I'll do that unless someone with more `ar` portability experience than me objects.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-593
