### ISSUE TITLE
Ed25519

### ISSUE THREAD

**Issue by blizzardplus** [ARMmbed/mbedtls#388]
Any plans to include Ed25519 in addition to Curve25519?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-594

**Comment by mpg** [comment]
It's not faster. Actualy Ed25519 and Curve25519 are two ways to look at the same curve, and the main difference is, Ed25519 is more suited to signing, while Curve25519 is more suited for Diffie-Hellman.

**Comment by carlescufi** [comment]
+1 on this one, would be great to have Ed25519/EdDSA support.

**Comment by nuket** [comment]
+1, would be nice to have alternatives to the NIST curves.

**Comment by H3ik0** [comment]
+1 Please do for hiawatha-webserver, and also ChaCha20-Poly1305 for better [mobile performance](https://blog.cloudflare.com/do-the-chacha-better-mobile-performance-with-cryptography/)

**Comment by MalteJ** [comment]
+1

**Comment by willderness** [comment]
+1 would be great to see Ed25519 as part of mbedTLS

**Comment by MalteJ** [comment]
I'd love to see support for TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256

**Comment by samrg472** [comment]
+1

**Comment by utzig** [comment]
+1

**Comment by d3zd3z** [comment]
+1 This indeed would be useful, not only for TLS, but for MCUboot and in general for signature verification.

**Comment by concatime** [comment]
Please, stop adding +1, it's not helpful at all. There's a button for that, or a pull request if you're able.

**Comment by xicilion** [comment]
So, is there any plan now?

**Comment by JamesTheAwesomeDude** [comment]
Is there anything worth stealing in [dunkelstern/mbedtls](https://github.com/dunkelstern/mbedtls) or [dunkelstern/mbedtls-esp8266](https://github.com/dunkelstern/mbedtls-esp8266)?

**Comment by agarwalrounak** [comment]
.

**Comment by agarwalrounak** [comment]
.

**Comment by agarwalrounak** [comment]
.

**Comment by 532910** [comment]
Is any update there, through 4 years?
ed25519/ed448 are modern and widely supported schemes, it's strange to see the lack of support in mbedtls.

**Comment by gilles-peskine-arm** [comment]
[An external contributor has kindly volunteered to contribute an implementation of EdDSA](https://github.com/ARMmbed/mbedtls/issues/2452). Unfortunately review bandwidth is a bottleneck, so it'll take us a few months to integrate the feature. You can track our progress through the milestone field of the pull requests (of which there is currently [one](https://github.com/ARMmbed/mbedtls/pull/3245) of a planned 4).

Given that all the recent discussion on the topic is happening on #2452, I think this issue is no longer useful, so I'm closing it.
