### ISSUE TITLE
Has anyone ported the email client to arduino platform

### ISSUE THREAD

**Issue by kapyaar** [ARMmbed/mbedtls#389]
This is not a bug, rather a question. Has anyone ported the ssl/ssl_email_client.c to an arduino platform? or could someone help me with it? platform is Arduino Due, with arm cortex m3 processor.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-595

**Comment by sbutcher-arm** [comment]
If your question is very simply, "has anyone ported mbed TLS to the Arduino Due", than [this has come up in the forum before](https://tls.mbed.org/discussions/generic/rsa-on-arduino-due), and people have done that. 

When porting to a new platform, as long as you [meet the dependencies documented here](https://tls.mbed.org/kb/development/what-external-dependencies-does-mbedtls-rely-on), the email sample should work for you.

If you'd like help or support, I suggest you post a more specific question to [the mbed TLS forum here](https://tls.mbed.org/discussions) or to a similar Arduino forum. Normally, people will be very helpful if they have a specific question, but broad, very open questions get less response because they're much more difficult to answer. 

I'm closing this issue because it's a question I think I've answered, but if you need some specific help, please pose a question that is more specific, either here, or in [the forum](https://tls.mbed.org/discussions) and you may get more help.
