### ISSUE TITLE
HELLO_VERIFY_REQUEST - Protocol Version

### ISSUE THREAD

**Issue by boaks** [ARMmbed/mbedtls#3914]
I currently try to clarify the usage of the protocol version in the HELLO_VERIFY_REQUEST [RFC 6347 - Section 4.2.1](https://tools.ietf.org/html/rfc6347#section-4.2.1).

It seems, that RFC6347 is ambiguous about that. I wrote a e-mail to the IETF TLS mailing list, 
see [RFC 6347 - Section 4.2.1 - used version in a HelloVerifyRequest](https://mailarchive.ietf.org/arch/msg/tls/rQ3El3ROKTN0rpzhRpJCaKOrUyU/).
There is a conflict in `SHOULD` 1.0 and `MUST` negotiated version.

I read in your "ssl_srv.c", around line 2520

> The RFC is not clear on this point, but sending the actual negotiated
> version looks like the most interoperable thing to do.

I guess, that's based on your experience, right?
Or do you have further references on the intentions of the RFC6347 according that?

**Comment by mpg** [comment]
Unfortunately I don't have more information about the intentions of the RFC. I think the reasoning behind what we do is that respecting a MUST at the expense of a SHOULD seems the logical thing to do. Perhaps digging in the archives of the IETF TLS mailing-list around the time that draft was actively discussed would shed light on this, but I'm not sure it would be worth the effort.

So far I've not heard any report of actual incompatibilities. In Mbed TLS, client-side we accept any version between 1.0 and our maximum supported version, in order to avoid punishing other implementations for the RFC's ambiguity. I didn't check, but I suspect other implementations do the same.

On a different note, the [Mbed TLS](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls) would be a better place to have this kind of discussion - github issues are for bug reports or feature requests that need tracking. So I'm closing this issue, but feel free to continue the discussion anyway (for example, if you check what other implementations are doing client-side, I'd be happy to know about it).

**Comment by boaks** [comment]
Thanks for the answer and the link to the mailing list!

**Comment by boaks** [comment]
I didn't receive an answer from the TLS list. My personal interpretation/conclusion about that definition is, that it may try to prevent sending alerts (wrong version) to not verified addresses. Therefore Eclipse/Californium now uses the version of the client_hello for the hello_verify_request, and after the address verification, it send the alert with the wrong version.
[Eclipse/Californium-HelloVerifyRequest](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/HelloVerifyRequest.java#L50)
