### ISSUE TITLE
The way of mbedtls_ssl_conf_verify can't verify cross certificate

### ISSUE THREAD

**Issue by timothy110** [ARMmbed/mbedtls#3989]
### Description
- Type: Bug
- Priority: Blocker

Because memory is limited, we have to use the way of mbedtls_ssl_conf_verify to verify certificate, **not mbedtls_ssl_conf_ca_cb or mbedtls_ssl_conf_ca_chain**. But this way has a bug that cannot verify cross certificate. For Example,  the certificate chain is that **r1** issued by r0, **r2** issued by r1, **r3** issued by r2. On device It only has r1 trust certificate but not r0. In this case, it cannot verify successfully because it must verify r0.

---------------------------------------------------------------
## Bug

**OS**  
freertos

**mbed TLS build:**  
Version: 2.16.8

**Expected behavior**   
verify ok

**Actual behavior**  
verify fail

**Steps to reproduce**  
With mbedtls_ssl_conf_verify , register verify callback function. the certificate chain is that **r1** issued by r0, **r2** issued by r1, **r3** issued by r2. On device It only has r1 trust certificate but not r0. In this case, it cannot verify successfully because it must verify r0.

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
Cross certification is common， But the way of verify callback (mbedtls_ssl_conf_verify ) cannot verify ok.
**Suggested enhancement**  

-----------------------------------------------------------------

**Comment by hanno-arm** [comment]
Hi @timothy110,

Thank you for your report.

Note that the verification callback is not a replacement for CRT verification. Instead, it is called after Mbed TLS has performed the X.509 verification. The primary aim is to allow the user to selectively clear some expected failure flags. The introduction of a feature which would allow users to offload CRT verificiation entirely is currently under [discussion in the mailing list](https://lists.trustedfirmware.org/pipermail/mbed-tls/2021-January/000278.html), to which I'd encourage you to subscribe.

However, coming back to your original motivation to offload verification: You mentioned that you're facing memory issues. Could you elaborate? We are aware that the X.509 module is quite memory intensive and have implemented a large number of memory optimizations which significantly reduce the memory usage during CRT verification, e.g. https://github.com/ARMmbed/mbedtls/pull/2478 However, some of those improvements are currently only available in the `baremetal` branch. If you'd benefit from having those optimizations on `development`, please send an email to the mailing list, so we can take this into account when planning the potential upstreaming.

Thank you,
Hanno

**Comment by timothy110** [comment]
@hanno-arm We need preset 19 trust certificates, If we load all of trust certificates in mbed via mbedtls_ssl_conf_ca_chain, it will cost 30~40KB heap ram size. Our Embedded device has no enough heap ram size to support it. If we use mbedtls_ssl_conf_verify, We only load one trust certificate into mbed in one time.

**Comment by hanno-arm** [comment]
Hi @timothy110, 

I suppose those 19 trusted certificates _are_ stored / accessible somewhere, but you don't want to also pass them to Mbed TLS because that (currently) involves duplication?

If so, then the CA callback should solve your problem: It allows you to offload the CA storage and pass only the one trusted certificate to Mbed TLS for verification that matches the certificate at hand.

Does that make sense?

Regards,
Hanno

**Comment by timothy110** [comment]
@hanno-arm We need to verify these 19 trusted certificates every time，But we have not enough  heap ram size to support loading all  trusted certificates into MBED at one time. The CA callback need loading all trusted certificates as same as mbedtls_ssl_conf_ca_chain.

**Comment by hanno-arm** [comment]
Hi @timothy110,

Could you explain your problem in more detail please? In particular, how come you need all 19 trusted CRTS for _every_ verification? For each certificate that's being verified, I'm expecting precisely _one_ of your trust anchors to apply, and only that needs loading.

Again, it would help if were a bit more detailed in your explanaations.

Regards,
Hanno

**Comment by mpg** [comment]
Having read the discussion so far, I agree with Hanno that `mbedtls_ssl_conf_ca_cb()` should fill your needs: it can examine the peer-provided chain, determine that it ends up at `r1`, then look into your list of 19 trusted certs (loading only 1 at a time), find `r1` and set it as the root of trust for the current handshake; then verification will succeed. (Verification shortcuts: if `r1` is locally trusted, there's no need to verify or even have a copy of `r0`.)

Since I believe the current discussion does not show a gap or bug in our API, and a month passed since the last time Hanno asked you for more details, I'm closing this ticket.

If you're still interested in this issue, please re-open and provide more details about what you tried and why you think the approach we suggest wouldn't work for you.
