### ISSUE TITLE
Remove deprecated things

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4029]
Remove code that is marked with MBEDTLS_DEPRECATED_WARNING or \deprecated.

**Comment by ShobhitSamuelSingh** [comment]
Hi, can I work on this issue?

**Comment by yanesca** [comment]
@ShobhitSamuelSingh Thank you for volunteering! It's a bit early though: we haven't yet started the 3.0 branch.

**Comment by ShobhitSamuelSingh** [comment]
@yanesca 
The changes that I made, were they correct?
Can you please guide me about what should I do, because I am new to open source and contributions?
Thank you

**Comment by yanesca** [comment]
@ShobhitSamuelSingh As I mentioned above, we haven't started the 3.0 branch yet. We need to create that first, because that is where this change should go in. For now we need to wait and once the 3.0 branch is created, we can redirect your PR. At this point we will review it and leave comments on the PR if we think that it could be improved.

Meanwhile you could look at the output of the failing tests in the Travis CI and try to fix them, because that will be the first thing that the reviewers will ask you to do.

**Comment by ShobhitSamuelSingh** [comment]
Okay, thank you for the advice.

**Comment by yanesca** [comment]
If you need help with locating or interpreting the logs in Travis CI, just let me know.

**Comment by ShobhitSamuelSingh** [comment]
Okay sure.

**Comment by mpg** [comment]
Note: this includes removing the file `net.h` as the whole file it deprecated.

**Comment by mpg** [comment]
The task description is not clear (because I think none of us clearly considered this) on one point: when there's a deprecated function `xxx` and a new function `xxx_ext` of `xxx_ret`, when removing the deprecated function should we also rename the new function to remove the suffix? I'm inclined to say yes, but I'd like to hear other opinions. @yanesca @gilles-peskine-arm @daverodgman I'd appreciate if (at least) one of you could share your opinion on this.

**Comment by yanesca** [comment]
I agree, we should rename the new function to remove the suffix.

**Comment by gilles-peskine-arm** [comment]
First, I think regardless of what we do, we should do it in a separate pull request. Let's get rid of the things to remove first, to minimize conflicts with other work.

Second, I'm not sure we want the same treatment for every case: `_ret` vs `_ext`, new parameter necessary for security (e.g. RNG) vs for functionality (e.g. passing 0 as the new parameter is safe and common). Please file a separate issue to discuss this.

**Comment by mpg** [comment]
Ok, let's do one thing at a time and keep this issue about removing things - I've created #4212 to evaluate which functions we want to rename later. We need to keep track of which functions we're removing here, but that's somethings we had to do anyway (ChangeLog entry), so there's no additional work created by splitting this up.

**Comment by mpg** [comment]
It appears that this issue is:

- not very well-defined, as it was unclear to some team members whether it included what's now #4278 for example
- as it's currently defined, overlapping with several other issues, notably #4031 and #4078
- probably too big for optimal scheduling and execution.

I'm going to split it into a series of smaller, well-defined, non-overlapping issues. I'm keeping it open until this is done, then I'll close it with links to the newly-created issues.

**Comment by mpg** [comment]
Closing as this is now covered by the following list of issues:

- #4031 Remove obsolete TLS features
- #4078 Remove PKCS11 module
- #4278 Remove 'mode' parameter from RSA functions
- #4280 Remove deprecated functions from hashing modules
- #4283 Remove deprecated error codes
- #4284 Remove deprecated types and constants in PSA
- #4281 Remove deprecated things - misc/remainder
- #4285 Final check for deprecated things
