### ISSUE TITLE
Remove obsolete TLS features

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4031]
(Edited by Manuel)

List of features to be removed:

- [x] support for parsing SSLv2 ClientHello (MBEDTLS_SSL_SRV_SUPPORT_SSLV2_CLIENT_HELLO).
- [x] support for SSLv3 (MBEDTLS_SSL_PROTO_SSL3).
- [x] support for compatibility with our own previous buggy implementation of truncated HMAC (MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT).
- [x] support for TLS record-level compression (MBEDTLS_ZLIB_SUPPORT).
- [x] RC4 ciphersuites.
- [x] the single-DES ciphersuites.
- [ ] Support for SSL record hardware acceleration (MBEDTLS_SSL_HW_RECORD_ACCEL).

**Comment by yanesca** [comment]
Features that need to be removed:
- support for parsing SSLv2 ClientHello (MBEDTLS_SSL_SRV_SUPPORT_SSLV2_CLIENT_HELLO).
- support for SSLv3 (MBEDTLS_SSL_PROTO_SSL3).
- support for compatibility with our own previous buggy implementation of truncated HMAC (MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT).
- support for TLS record-level compression (MBEDTLS_ZLIB_SUPPORT).
- RC4 ciphersuites.
- the single-DES ciphersuites.
- Support for SSL record hardware acceleration (MBEDTLS_SSL_HW_RECORD_ACCEL).

Some or all of these could be moved to their own issue for the ease of tracking.

**Comment by daverodgman** [comment]
There was some discussion on the mailing list here: https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000022.html

**Comment by yanesca** [comment]
Manuel recorded the summary of discussions on the TF.org wiki:
https://developer.trustedfirmware.org/w/mbed-tls/tech-plans-3.0/

**Comment by mpg** [comment]
I'm doing an attempt at a definition of done for this task, or more precisely for each of its sub-tasks:

- `git grep MBEDTLS_SSL_SRV_SUPPORT_SSLV2_CLIENT_HELLO` should find no result except in historical files (see below), the library must always behave as it currently does when this macro is undefined, and the CI must pass - this might involve removing tests that relied on this option being set.
- same for `MBEDTLS_SSL_HW_RECORD_ACCEL` - this wasn't tested AFAIK so perhaps no changes to tests here
- same for `MBEDTLS_SSL_PROTO_SSL3` - this will likely involve changes in `compat.sh`
- same for `MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT`
- same for `WITH_DES` - but `WITH_3DES` 
- same for `MBEDTLS_ZLIB_SUPPORT` - support in the build system should be removed as well
- Regarding RC4, things are a bit more subtle: `grep -i 'ARC4' library/ssl_*.c include/mbedtls/ssl.h` and `git grep MBEDTLS_REMOVE_ARC4_CIPHERSUITES` should return no result (except in historical files), the TLS library must always behave as it currently does when `MBEDTLS_ARC4_C` is undefined (the value of MBEDTLS_REMOVE_ARC4_CIPHERSUITES` then becomes irrelevant), and the CI must still pass - this will involve removing SSL tests that relied on `MBEDTLS_ARC4_C` being set and may involve removing command-line options in `programs/ssl/ssl_*2.c`. However, the crypto library is left unchanged, in particular `MBEDTLS_ARC4_C` is still available in `config.h`, `arc4.[ch]` and `test_suite_arc4.*` are untouched (as part of this task, their fate is being discussed in #4084 though).

_Historical files_ are defined as: `ChangeLog` and files in the `ChangeLog.d` directory, plus `include/mbedtls/compat-1.3.h` and `scripts/data_files/rename-1.3-2.0.txt` (though those last two are being removed as we speak, see #4150).

If during the removal of one option, it appears that having it always unset opens the door simplifying or refactoring the code, this can either be done in the same PR (if small/easy enough) or recorded in an issue for later.

Since this task is actually a list of sub-tasks, it could be executed either in one of multiple PRs (or group the most simple sub-tasks to a single PR and give the more complex one(s) their own PR), whatever is preferred. (Smaller PRs might converge more quickly, but too many PRs augment the risk for conflicts between PRs.)

**Comment by mstarzyk-mobica** [comment]
Can I close this issue or should I wait for the #4285 ?

**Comment by mpg** [comment]
I think this issue can be closed as it was fully resolved by merging #4156 - #4285 is more about double-checking that the list of issues I have created was indeed complete, than about checking that each issue was executed fully - in principle that should be ensured during PR review. So I'm closing this.

**Comment by mstarzyk-mobica** [comment]
ok

**Comment by TRodziewicz** [comment]
This PR will also close #4285
