### ISSUE TITLE
Make more function parameters const

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4033]
Change the public interface function parameters to be const, where appropriate.

Adding const to some internal functions is not part of this task, as it can be done at any time after 3.0.

It's recommended to submit PRs for individual modules or areas of code rather than one large PR.

**Comment by mstarzyk-mobica** [comment]
I'll take it as my first task

**Comment by mpg** [comment]
There were other github issues on the same theme, I'm linking them here for the sake of completeness:

- https://github.com/ARMmbed/mbedtls/issues/1485 (links to 3 other issues + has contents of its own, some of it invalid IMO)
- https://github.com/ARMmbed/mbedtls/issues/396 
- https://github.com/ARMmbed/mbedtls/issues/803 (invalid IMO)

I'll comment directly on the relevant issues why I think some of them are invalid, but first I wanted to add the links here to make sure this is tracked.

**Comment by mpg** [comment]
Ok, I've now commented on the issues and PRs linked directly or indirectly from the above comment. The only one I didn't think was invalid or unwanted to other reasons was https://github.com/ARMmbed/mbedtls/issues/396 for which you might want to create a PR (the existing PR addressing it also contains changes that I don't think we want, as I commented there).

**Comment by mpg** [comment]
Note: once the PRs for each module have been merged*, it would be good to add a ChangeLog entry (perhaps under "API changes") describing the changes briefly. I'm suggestion a single ChangeLog entry as this is relatively low-impact and we don't want to overwhelm users with details (especially as the 3.0 ChangeLog will contain more important things).

*Alternatively, a PR for the ChangeLog entry can be created before the other PRs are merged, but labeled "needs: preceding PR" (with references in the description) in order to reduce latency.

**Comment by gilles-peskine-arm** [comment]
@mpg Good point about changelogs. https://github.com/ARMmbed/mbedtls/issues/4114

**Comment by mpg** [comment]
I think the following PRs collectively resolve this issue: #4063 (aria), #4063 (asn1), #4066 (asn1write), #4102 (PK parse), #4115 (ChangeLog), unless anyone sees any more work to do here?
