### ISSUE TITLE
Convert negative to positive options

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4034]
Convert negative options in config.h to positive style, e.g.

MBEDTLS_NO_64BIT_MULTIPLICATION becomes MBEDTLS_HAVE_64BIT_MULTIPLICATION (and uses of this need to be inverted)

**Comment by olifshitz** [comment]
I would like to work on this. Could you please assign it to me and  refer me to the relevant files?

**Comment by gilles-peskine-arm** [comment]
`MBEDTLS_NO_64BIT_MULTIPLICATION` is not really a “negative option” except in wording. It changes the way some parts of the code behaves, it doesn't just turn something off.

A typical example of a negative option is `MBEDTLS_SHA512_NO_SHA384`. The reason we have this negative option is backward compatibility: since `MBEDTLS_SHA512_C` turned on both SHA-512 and SHA-384, if an application had its own standalone `config.h` with `#define MBEDTLS_SHA512_C`, we had to preserve this meaning of MBEDTLS_SHA512_C`.

**Comment by gilles-peskine-arm** [comment]
@olifshitz Thank you for volunteering! It's a bit early though: we haven't yet started the 3.0 branch. Also we'll first need some discussion to identify the options to change.

**Comment by yanesca** [comment]
> MBEDTLS_NO_64BIT_MULTIPLICATION is not really a “negative option” except in wording. It changes the way some parts of the code behaves, it doesn't just turn something off.

That is true, but I guess we still could change it for consistency.

**Comment by mpg** [comment]
I review existing options that have `_NO_` or `_REMOVE_` in their name, and found that `MBEDTLS_SHA512_NO_SHA384` is currently the only one that needs to be changed from negative to positive.

However I think we should go a bit further and also preemptively add positive options (that initially do nothing, then it will be a further backwards-compatible improvement that disabling the option will actually reduce the code size). The following is a list of negative options that we introduced in the `baremetal` branch and for which we probably want to introduce a positive option now:

- `MBEDTLS_SHA256_NO_SHA224`, see  [r621](https://github.com/ARMmbed/mbedtls-restricted/pull/621) -> introduce `MBEDTLS_SHA224`? (similar to SHA384 that should be introduced too)
- `MBEDTLS_SSL_PROTO_NO_TLS`, see [r585](https://github.com/ARMmbed/mbedtls-restricted/pull/585) -> introduce `MBEDTLS_SSL_PROTO_TLS` (similar to the existing `MBEDTLS_SSL_PROTO_DTLS`)
- `MBEDTLS_SSL_NO_SESSION_CACHE` [r601](https://github.com/ARMmbed/mbedtls-restricted/pull/601) -> introduce `MBEDTLS_SSL_SESSION_CACHE`
- `MBEDTLS_SSL_NO_SESSION_RESUMPTION`, see [r601](https://github.com/ARMmbed/mbedtls-restricted/pull/601) -> introduce `MBEDTLS_SSL_SESSION_RESUMPTION`
- `MBEDTLS_X509_REMOVE_VERIFY_CALLBACK`, see [r609](https://github.com/ARMmbed/mbedtls-restricted/pull/609) -> `MBEDTLS_X509_VERIFY_CALLBACK` - and should we introduce similar ones for the CA callback that was introduced in the meantime?
- `MBEDTLS_X509_REMOVE_SET_HOSTNAME`, see [r642](https://github.com/ARMmbed/mbedtls-restricted/pull/642) -> `MBEDTLS_X509_VERIFY_HOSTNAME`?
- `MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH`, see #2890 -> do we want to add that now, or just wait for `PSA_WANT` and/or the driver interface to provide better options? @gilles-peskine-arm @ronald-cron-arm 
- `MBEDTLS_AES_ONLY_ENCRYPT`, see #2891 -> same as above

I'm linking to the baremetal PRs as I believe we can re-use some of the documentation for those new options (which in some cases was not trivial, for example to explain how multiple options related to SSL session resumption interact), with the obvious changes required by moving from negative to positive.

**Comment by gilles-peskine-arm** [comment]
I don't think we should preemptively introduce options. We're sure to miss some, and to overshoot with others. Instead, we should make sure that our configuration mechanism supports backward compatible evolution better than the current one. That's the intent of https://github.com/ARMmbed/mbedtls/issues/3960.

For example, if we want to add a SHA256-but-no-SHA224 build mode, we can introduce an option `MBEDTLS_SHA224` and instruct users to put `#undef MBEDTLS_SHA224` in their config file if they don't want SHA224. In `includable-config.h`, we'd put:
```
#define MBEDTLS_SHA224_
#include "editable-config.h"
```
`MBEDTLS_SHA224` would enable SHA224 if SHA256 is enabled and does nothing otherwise.

**Comment by mpg** [comment]
@gilles-peskine-arm That's an excellent point. I already liked #3960 but didn't realise yet that it solves this problem too. So, I withdraw my proposal to preemptively add options.

**Comment by mstarzyk-mobica** [comment]
@gilles-peskine-arm @mpg 
Please confirm that this task in actually only about changing MBEDTLS_SHA512_NO_SHA384 (negative to positive).
Should I modify task's title?

**Comment by gilles-peskine-arm** [comment]
We discussed the design of hash options today and concluded that we should take the opportunity of the major version bump to change the meaning of hash-related options to be more intuitive: `MBEDTLS_<hash>_C` means enabling `<hash>`, regardless of whether this hash algorithm is implented in `<hash>.c` or not.

This means:

* Create an option `MBEDTLS_SHA384_C`, and change the meaning of `MBEDTLS_SHA512_C` to be “I want SHA-512” (instead of “I want SHA-512 and SHA-384”).
* Create an option `MBEDTLS_SHA224_C`, and change the meaning of `MBEDTLS_SHA256_C` to be “I want SHA-256” (instead of “I want SHA-256 and SHA-224”).
* Change all places that have a dependency on both `MBEDTLS_SHA512_C` and `MBEDTLS_SHA512_NO_384` to just having a dependency on `MBEDTLS_SHA384_C`.
* Change `check_config.h` to reject the following configurations, which are not yet supported but will become supported when we get around to it:
    * SHA-384 without SHA-512
    * SHA-256 without SHA-224
    * SHA-224 without SHA-256
* Change test scripts that enumerate dependencies to ensure we don't try to test the rejected configurations. This means changes to `depends-hashes.pl`, and also perhaps to some PSA-related scripts (`tests/scripts/generate_psa_tests.py` and auxiliary scripts, perhaps some `all.sh` components).
* Remove any remaining trace of `MBEDTLS_SHA512_NO_SHA384`. It's referred to indirectly in `depends-hashes.pl` and mentioned explicitly in `set_psa_test_dependencies.py`.

@mstarzyk-mobica Please start working on the creation of the new options, the dependency changes and `check_config.h`. Don't hesitate to ask for help on the Perl and PSA scripts.
