### ISSUE TITLE
Change config.h defaults

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4036]
Enable `MBEDTLS_CMAC_C`, and `MBEDTLS_NIST_KW_C` (maybe nothing else to change).

This task excludes X.509 changes, which are covered in #4037

**Comment by mpg** [comment]
I'd like to suggest we consider disabling smaller curves by default. That is, 192-bit and 224-bit curves (we have two of each: secp-r1 and secp-k1 families) would be disabled by default in config.h (but still supported in the code base if someone wants to enable them).

**Comment by mpg** [comment]
I quickly reviewed which module are currently not enabled by default, and in addition to CMAC and NIST-KW, there's also `MBEDTLS_ARIA_C` which I think should be enabled by default.

Currently `MBEDTLS_ECJPAKE_C` is disabled by default because when it was added the standard was potentially not final yet. @yanesca since you're currently investigating PAKEs, do you happen to know what the status of EC J-PAKE is? If the standard is mature enough, we should remove the warning in `config.h` and enable it by default.

All the other modules that are currently disabled by default are so for a good reason (such as: broken crypto / deprecated, alternative / OS-dependent features).

**Comment by yanesca** [comment]
[RFC 8236](https://tools.ietf.org/html/rfc8236) is not standard track, it is just informational. About ECJPAKE in TLS I only could find an old expired draft:
https://tools.ietf.org/html/draft-cragie-tls-ecjpake-01

Based on this I think we could enable `MBEDTLS_ECJPAKE_C` by default, but `MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED` should remain disabled.

**Comment by mpg** [comment]
Thanks for the info, I wasn't aware there was an RFC about (EC) J-PAKE. Even if it's just informational, that's the case for a lot of things we implement (for example, all the PKCS RFCs are informational), and I think what matters here is the distinction between draft and final RFC.

However, since the implementation was based on the Thread spec, not this RFC (or draft of it), perhaps it would be good to check if it also conforms to the RFC at some point?

**Comment by gilles-peskine-arm** [comment]
If `MBEDTLS_ECJPAKE_C` is enabled but an application doesn't explicitly use any of its features, does this increase the application's attack surface? If not I think we should enable it in the default configuration.

**Comment by yanesca** [comment]
> However, since the implementation was based on the Thread spec, not this RFC (or draft of it), perhaps it would be good to check if it also conforms to the RFC at some point?

That is a good idea, but I don't think it should block enabling `MBEDTLS_ECJPAKE_C` as default.

> If MBEDTLS_ECJPAKE_C is enabled but an application doesn't explicitly use any of its features, does this increase the application's attack surface? If not I think we should enable it in the default configuration.

As far as I can tell it is not included in any abstraction layer or other feature and the TLS code calls it directly. If it is not enabled in the TLS module it shouldn't be possible to call it accidentally or to trick an application into calling it.

**Comment by mpg** [comment]
So far our (unwritten...) policy was to enable everything in the default config unless there was a specific reason not to (experimental, obsolete, insecure unless that's really what you want (I'm thinking NULL ciphersuites here), backwards compat issues...). I'm not necessarily against changing that policy to also include the generic reason of "might increase the attack surface", but in that case I think (1) it would be good to have a discussion about the policy first (and write down the result) and (2) I don't see why only ECJPAKE would be on the line.

Now regarding this specific case, I agree with Janos that I don't see a way to trick an application into calling it if the associated key exchange remains disabled. Now, in general, having more code in the executable portion of the process address space might still be a risk as it provides more gadgets for ROP or similar techniques. (This doesn't apply to constrained devices that presumably use link-time garbage collection, and probably shouldn't use the default config anyway.)

**Comment by mpg** [comment]
Summary of work to do:

- enable `MBEDTLS_CMAC_C`, `MBEDTLS_NIST_KW_C` and `MBEDTLS_ARIA_C`
- enable `MBEDTLS_ECJPAKE_C` but leave `MBEDTLS_KEY_EXCHANGE_ECJPAKE` disabled
