### ISSUE TITLE
Change X.509 default config

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4037]
Changes to defaults in config.h.

**Comment by yanesca** [comment]
I don't remember what we wanted to achieve with this.

@gilles-peskine-arm, @mpg do you remember by any chance some more background on this task?

**Comment by mpg** [comment]
I don't remember anything that we wanted to change in config.h regarding X.509... I looked on our [previous internal wiki](https://confluence.arm.com/display/BSGSoftware/Plans+for+Mbed+TLS+3.0) and couldn't find anything there either.

I had a look at the code and could find one thing: we currently have a config.h option named `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES` which is disabled by default, and that we probably want to remove altogether (leaving it off permanently). However since this is a removal I think it's already captured in #4058 

So unless @gilles-peskine-arm or someone else can think of anything else, we can probably just close this issue.

**Comment by mpg** [comment]
Since I asked 26 days ago whether anybody could see a reason to keep this open, and nobody spoke up, I'm closing it.
