### ISSUE TITLE
Review PRs for items relevant to Mbed TLS 3.0

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4039]
Review outstanding PRs for item which would be suitable for Mbed TLS 3.0.

**Comment by mpg** [comment]
Note: obvious candidates would be issues or PRs with the label "api-break", but there's only [one issue](https://github.com/ARMmbed/mbedtls/issues?q=is%3Aopen+is%3Aissue+label%3Aapi-break) and [no PR](https://github.com/ARMmbed/mbedtls/pulls?q=is%3Aopen+is%3Apr+label%3Aapi-break) with this label.

I'm not sure if looking individually at each of the 594 open issues and 249 open PRs that we have in order to identify if some of them might be blocked by requiring an API break is worth it, considering (1) it's not clear that this review would turn up anything at all and (2) if it does, it's not even clear that we'll want to prioritize the results.

It looks like we never really used the `api-break` label consistently, but OTOH we used to write down on Confluence things that we wanted to remember for 3.0, and we were more consistent there. So the risk of having forgotten something important is perhaps no as low as we'd like, but it still seem relatively low to me compared to the cost of going over a few hundred PRs and issues.

**Comment by gilles-peskine-arm** [comment]
@mpg We should at least expand the search to issues and PR that mention “API break” or similar words in a comment, e.g. https://github.com/ARMmbed/mbedtls/pulls?q=is%3Apr+is%3Aunmerged+base%3Adevelopment+-base%3Adevelopment_3.0+%22api+break%22+

**Comment by mpg** [comment]
Review completed.
