### ISSUE TITLE
Review configuration options for Mbed TLS 3.0

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4058]
In Mbed TLS 3.0, we want to shed weight. One aspect of shedding weight is getting rid of as many compilation options as possible. Compilation options increase the code complexity and the testing burden. The goal of this issue is to review the existing compilation option.

For each existing option in `config.h`:

* If the option should obviously stay (e.g. `MBEDTLS_xxx_C`, platform capabilities), record this and move on.
* Otherwise, start a discussion on the mailing list to gauge who is using it, who wants it, and weigh that against the burden of supporting the option. (A few options have been discussed already, see https://developer.trustedfirmware.org/w/mbed-tls/tech-plans-3.0/.) If the option is removed, discuss how this would work: always on or always off?
* Once the discussion settles, record the outcome: if it should stay, justify why (this includes explaining how it is tested). If it should go away, is it always on or always off? What are the migrations for applications that were making use of the option?

My personal opinion on configuration options is that platform capabilities and is-it-supported options (mostly `MBEDTLS_xxx_C`, also a few like `MBEDTLS_PKCS1_Vxx and the new `PSA_WANT_xxx`) should stay unless there's a good reason. Other configuration options 

This task can be split between many people since most options are independent.

As a preliminary, we need to have a central place to track progress. This is more suited to a wiki-like setup. We've started to put [3.0 plans on the TrustedFirmware wiki](https://developer.trustedfirmware.org/w/mbed-tls/tech-plans-3.0/), but we want to move this kind of information to the [Mbed TLS documentation repository](https://github.com/ARMmbed/mbedtls-docs).

**Comment by mpg** [comment]
See also #4035

**Comment by mpg** [comment]
Note: it's probably time for `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES` to go. (This is just a default, if there are still people who really want to allow SHA-1 in certs - including us in tests if we still rely on a few legacy certs - they can still create a custom X.509 verification profile.)

**Comment by gilles-peskine-arm** [comment]
@mpg I agree. But let's please not discuss individual options on this issue or else it'll become impossible to follow. I've created https://github.com/ARMmbed/mbedtls/issues/4171 for `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES`.

**Comment by chris-jones-arm** [comment]
A list of config options and the decisions made on them is being made here https://docs.google.com/spreadsheets/d/1Jc0IV0Q2q8-b7gMEJfyZZsUwhakhojZvYNpv2KDZIbQ/edit?usp=sharing.

Please feel free to review and add comments to these options for any that you want to keep/remove.

**Comment by mpg** [comment]
Thanks for sharing the sheet! Some initial thoughts:

Regarding RC4, so far only the ciphersuites in SSL (line 56) are being removed for sure, the crypto primitive itself is still under discussion: #4084 - I suggest referencing that discussion for `ARC4_C`, `MD2_C`, `MD4_C` and their `_ALT` counter-parts (plus `_PROCESS_ALT` for MD2 and MD4), which should have the same fate as the `_C` one.

Regarding `MBEDTLS_MPI_WINDOW_SIZE`: this is one of the main ways to tune RAM usage for people using RSA or Finite-Field DH. For RSA-4096, the default setting uses a table that consumes 16kB of heap, while the minimal value is 0.5kB. (Double those numbers if `RSA_NO_CRT` is set.) This is a very significant difference for constrained devices, for a lot of them that's the difference between usable and unusable. Arguably in the future instead of a plethora of specific (and often cryptic) options we should have more general ones such as `TRADE_RAM_FOR_SPEED` or `TRADE_CODE_SIZE_FOR_SPEED` that would apply to multiple modules. However I'm afraid it would be more design effort than what we can afford for 3.0, so might have to wait for 4.0.

Regarding `PLATFORM_xxx_MACRO`: I seem to remember these were introduced for experiments in running the test suites in a baremetal environment. In that use case, compile-time substitution was key to have the code build (including linking the executables) with a baremetal toolchain such as `arm-none-eabi-gcc`. So it would appear that we need to do be able to do this at compile-time. I think the ability to do this at runtime too is useful in some tests too. So perhaps we need both indeed (if so, this should be documented somewhere). Also, off-hand I don't remember what the difference is between `PLATFORM_STD_CALLOC` and `PLATFORM_CALLOC_MACRO`, even less why we apparently thought we needed both. Really this should be better documented.

Regarding `MBEDTLS_SSL_MAX_CONTENT_LEN`: I think it should go, it was kept only for compatibility reasons after the more precise IN/OUT versions were introduce.

Regarding `MBEDTLS_REMOVE_3DES_CIPHERSUITES`: I vote we remove this and the library should always behave as it it was enabled.

**Comment by yanesca** [comment]
> Regarding `MBEDTLS_REMOVE_3DES_CIPHERSUITES`: I vote we remove this and the library should always behave as it it was enabled.

+1 vote on that.

**Comment by chris-jones-arm** [comment]
Now that the spreadsheet has been created, options have been discussed and issues have been created for each option we wish to remove I am closing this issue as it is finished.
