### ISSUE TITLE
mbedtls rejects a certificate with a critical policyConstraints while OpenSSL accepts it

### ISSUE THREAD

**Issue by GOODPWDCETCSZ** [ARMmbed/mbedtls#4060]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug 
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS linux

**mbed TLS build:**  
Version: 2.25.0
OS version: 18.04, 20.04  
Configuration: no
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  gcc 9.3.0
Additional environment information:  no

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  OpenSSL 1.1.1f

**Expected behavior**   
Consistent verification result between OpenSSL and mbedTLS.

**Actual behavior**  
```
  . Loading the CA root certificate ... ok (0 skipped)

  . Loading the certificate(s) ... failed
  !  mbedtls_x509_crt_parse_file returned -9570
```

**Steps to reproduce**  

`./cert_app mode=file ca_file=ca.pem filename=seed-16s31-255s21-363s29.pem`

[ca.zip](https://github.com/ARMmbed/mbedtls/files/5870658/ca.zip)

[seed-16s31-255s21-363s29.zip](https://github.com/ARMmbed/mbedtls/files/5870661/seed-16s31-255s21-363s29.zip)

**Comment by gilles-peskine-arm** [comment]
This certificate contains a Name Constraints extension. Mbed TLS does not support this extension, and it's a critical extension, so Mbed TLS does not support it.

I do wonder why the library explicitly returns `MBEDTLS_ERR_X509_INVALID_EXTENSIONS + MBEDTLS_ERR_ASN1_UNEXPECTED_TAG` rather than `MBEDTLS_ERR_X509_INVALID_EXTENSIONS + MBEDTLS_ERR_OID_NOT_FOUND` which would both simplify the code and be more intuitive. I would suggest changing this in 3.0 (perhaps at the same time we remove the compile-time option `MBEDTLS_X509_ALLOW_UNSUPPORTED_CRITICAL_EXTENSION` which is dangerous and is now useless thanks to the possibility of using a callback).

**Comment by mpg** [comment]
@gilles-peskine-arm could you create an issue in the 3.0 epic explaining what you have in mind? And then I think we could close this one.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because the error is due to an attempt to use a feature of X.509 that Mbed TLS doesn't support. I filed https://github.com/ARMmbed/mbedtls/issues/4167 about the misleading error code.
