### ISSUE TITLE
Remove module: certs

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4080]
Move the certs module (certs.c, which is enabled by MBEDTLS_CERTS_C in config.h) out of the library into a part of the tree that is available for test code and example programs, but isn't compiled into libmbedx509.

Mailing list discussion: https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000050.html

This is part of #4030

**Comment by mstarzyk-mobica** [comment]
Please assign this task to me

**Comment by mstarzyk-mobica** [comment]
Regarding function` mbedtls_x509_self_test` in x509.c, the referenced certificates (`mbedtls_test_cli_crt` and `mbedtls_test_ca_crt`) point to the variables, which contents vary depending on the definition of `MBEDTLS_RSA_C`
Also - these variables are referenced outside of x509.c, example: https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_client2.c#L1618

**Question 1**
For x509.c, should I keep both variants of the `mbedtls_test_cli_crt` and `mbedtls_test_ca_crt` variables depending on the definition of `MBEDTLS_RSA_C` ?

**Question 2**
If the certs module were to be removed from the library, then files outside of the library (like mentioned ssl_client2.c) would have to contain a modified copy of currently used certs files. x509 would then have to have it's own copy of `mbedtls_test_cli_crt` and `mbedtls_test_ca_crt` variables (along with `MBEDTLS_RSA_C` if/else condition). Is my understanding correct?

**Comment by gilles-peskine-arm** [comment]
@mstarzyk-mobica Generally speaking, move the code to the `tests` directory, and don't change the content.
```
git mv library/certs.c tests/src
git mv include/mbedtls/certs.h tests/include/test
```
Then adjust all the build paths, include directives, etc. Maybe rename identifiers. And whatever else it takes to pass CI.

No hard-coded certificate or key should be present under `programs`.

**Comment by mpg** [comment]
Regarding programs, unless I'm mistaken they should have access to things defined in the `tests` directory, so after following the suggestion in Gilles's message, you shouldn't need to change anything in `ssl_client2.c` or any other program: they will keep getting there test certs from `certs.c` which will just live in a different location.

The problem indeed as you raised in the meeting is with the self-test function in `x509.c`, which no longer has access to that data once it's moved outside `library`. Here I'm conflicted between two options:

1. Duplicate just the two certs used for testing - in DER form, in order to avoid a dependency on the PEM module. If we go with that, we can either just used RSA certs and make the selftest function depend on RSA (just like it currently depends on SHA-256) or provide two pairs of certs, one for RSA and the other one for ECC.
2. Remove the X.509 selftest altogether. I'm really not sure what purpose it serves, it doesn't even have a single negative test. We don't have a self-test for SSL, do we need to have one for X.509? (I understand some people care about self-tests for crypto primitives for compliance reasons, but I don't think this extends to X.509 and hopefully the current positive-only selftest in X.509 wouldn't be considered sufficient for any kind of compliance anyway.)

I said I'm conflicted, but the more I think about it the more I like the idea of removing this self-test unless someone can come up with a good reason we should keep it.

**Comment by mstarzyk-mobica** [comment]
As discussed on slack thread, selftest will be removed from x509.c
