### ISSUE TITLE
Investigate removing module: memory_buffer_alloc

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4081]
Some users may want to use a security-focused allocator rather than the toolchain default, so removing it would be disruptive. The mailing list discussion seemed to agree that this would ideally be better as a separate project, but that's out of scope for this task.

As a first step, explore this issue and determine the best course of action for Mbed TLS 3.0. Options could include:

- do nothing
- deprecate these functions as a step towards removing them in a future major version
- move into a separate part of the tree, compiled into a separate library. This would be a step towards making a separate project.
- remove memory_buffer_alloc.

Mailing list discussion: https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000026.html

This is part of #4030

**Comment by mpg** [comment]
> do nothing

I vote for this option.

I don't think deprecating is the right thing if the intention is to move rather than remove this.

I'm not sure making it into a separate library now is the right time. For example, we'd have to work out a name, which implies defining a purpose for this library (is it meant to include other things in the future?). Also, if (as seems to be the long-term plan) this is moved to a separate project later, that means two successive disruptions for users. Finally, I don't see much to be gained by just making it build to its own library now (it's not easier for users nor for maintainer - the initial question of whether we could/should drop it was meant to decrease the maintenance burden).

**Comment by tom-daubney-arm** [comment]
Based on conversations that have occurred it has been largely agreed that "do nothing" is the correct approach for now.
It has also been noted that this sort of investigative task should probably not really be assigned to one person, as a general consensus is needed in order to properly make a decision.

Due to the above, this issue is now being closed.
