### ISSUE TITLE
Remove MD2, MD4, RC4, Blowfish and XTEA

### ISSUE THREAD

**Issue by daverodgman** [ARMmbed/mbedtls#4084]
### Proposal                                                                        
Remove the obsolete and niche cryptographic primitives from Mbed TLS 3.0, namely MD2, MD4, RC4, Blowfish and XTEA.                                               
                                                                                
### Rationale                                                                       
Every feature in the code base has a maintenance and operational(CI testing) cost. It is better to remove features that are barely used.                     
Remove security risks as MD2, MD4, RC4 and Blowfish are not considered secure anymore.                                                                        
                                                                                
### Work to do
Remove md2.[ch], md4.[ch], arc4.[ch], blowfish.[ch] and xtea.[ch] and any reference to them.

Remove the following configuration options:
MBEDTLS_MD2_ALT, MBEDTLS_MD2_PROCESS_ALT, MBEDTLS_MD2_C
MBEDTLS_MD4_ALT, MBEDTLS_MD4_PROCESS_ALT, MBEDTLS_MD4_C
MBEDTLS_ARC4_ALT,MBEDTLS_REMOVE_ARC4_CIPHERSUITES, MBEDTLS_ARC4_C
MBEDTLS_BLOWFISH_ALT, MBEDTLS_BLOWFISH_C
MBEDTLS_XTEA_ALT, MBEDTLS_XTEA_C

Remove the related error codes and test suites.        

"grep -i" of all occurrences of md2, md4, arc4, blowfish and xtea and remove, update them as appropriate.

### Notes
The removal of RC4 ciphersuites from TLS was proposed earlier on the mailing list here: https://lists.trustedfirmware.org/pipermail/mbed-tls/2020-April/000022.html.
This is part of #4030.
Email sent to the mailing list the 19th of April 2021: https://lists.trustedfirmware.org/pipermail/mbed-tls/2021-April/000333.html.

**Comment by mpg** [comment]
I'm quite strongly in favour of disabling in the default config.h but keeping it in the codebase.

So far we had an (unwritten, as is too often the case) policy of removing from the code base obsolete things about _data in transit_ (mostly TLS options) but keeping things that might apply to _data at rest_ (mostly crypto primitives, some X.509/PK things). The rationale is that data at rest might have been created a while ago, using algorithms that have been deprecated in the meantime, but you might still want to be able to access/verify it, if you're doing some sort of archeology for example; this does not apply to data in transit where algorithms are selected dynamically. Additionally, modules for crypto primitives tend to be self-contained and relatively easy to test, as opposed to TLS options which tend to interact more with the rest of the TLS code and impose a higher maintenance burden.

I think the current policy is adequate (and should probably be documented somewhere), but if we want to change it, we should do so consistently: currently MD2 and MD4 (and unless I'm mistaken, support for using them in X.509) are still part of the codebase, and it would make little sense remove RC4 but keep those.

**Comment by daverodgman** [comment]
That's a fair point, but we should consider whether people using RC4/MD2/MD4 on data at rest are sufficiently served by Mbed TLS 2.x, which will continue to support these for another three years. Is it likely that users of Mbed TLS 3.0 will have this requirement?

**Comment by mpg** [comment]
> Is it likely that users of Mbed TLS 3.0 will have this requirement?

I'm not sure, and asking on the mailing list would probably be a good way to know more (though of course it can't rule out that users not on the list might have this requirement, at least it's way better than just us taking guesses). (By the way, the mailing-list discussion you linked to only mentions removing RC4 ciphersuites from TLS, not removing RC4 entirely.)

Note: so far we've kept old crypto primitives around for much longer than 3 years after they've been deprecated/broken. For example, according to wikipedia, MD4's collision resistance was badly broken in practice (collisions generated in seconds) as early as 1995, and its pre-image resistance got theoretically broken in 2008. OTOH, wikipedia also says MD4 is still used for NTLM in windows 10...

Ok, while I'm looking up uses of old crypto primitives on wikipedia, it looks like RC4 was the only encryption algorithm in PDF up to 1.5, and it does not seem inconceivable to me that someone may want to open an encrypted PDF <= 1.5 in more than 3 years... now it could be argued they'll just have to use something other than a supported version of Mbed TLS...

In terms of cost/benefit analysis, I think the benefit of keeping old crypto primitives is relatively low, but the cost is also pretty low, which is why I think keeping them makes sense. Now if it turns out that the benefit is very low to non-existent, then it might indeed not justify even a low cost.

I'm curious to hear other opinions (also on the cost side of the equation, which I might be underestimating).

PS: if we go with removing old crypto algorithms, we might consider adding blowfish and xtea to the list.

PPS: MD2 and MD4 are already disabled in the default config.h.

**Comment by gilles-peskine-arm** [comment]
Until last week, I'd been saying that the maintenance of MD2 and MD4 is negligible. But we've finally seen a bug that only applies to MD2 and not to MD5 and the others: https://github.com/ARMmbed/mbedtls/issues/4267.

The maintenance of RC4 is somewhat higher because its interface is not like the others (RC4 doesn't take an IV).

**Comment by mpg** [comment]
> I'm quite strongly in favour of disabling in the default config.h but keeping it in the codebase.

For the record, following discussions here and elsewhere, I've changed my mind. I'm happy with removing obsolete/niche crypto primitives from the code base as long as we check on the list and nobody objects.

Summary of primitives considered for removal on those grounds:

- RC4: currently enabled by default, multiple weaknesses, deprecated in all standards that used to use it
- MD2: disabled by default since a long time, broken
- MD4: disabled by default since a long time, badly broken
- blowfish: currently enabled by default, only known weakness is that the block size (64 bits) is too small (see sweet32), not very mainstream
- xtea: currently enabled by default, apparently no attacks known against full-round versions, but pretty niche, and there are probably better replacements nowadays (Chacha20, winners of NIST lightweitgth crypto competition...)

**Comment by mpg** [comment]
Note: for each module that's removed, the corresponding `_ALT` options will be removed as well.

**Comment by mpg** [comment]
There has been no objection on the list, so I'm marking this as approved.
