### ISSUE TITLE
time() replacement for older windows CE

### ISSUE THREAD

**Issue by kattassen** [ARMmbed/mbedtls#411]
When using MBEDTLS_HAVE_TIME and MBEDTLS_HAVE_TIME_DATE in mbedTLS builds it is stated that the functions time() and gmtime() (in time.h) must be supported by the OS. My issue is that the described functions does not exists in my OS. Time.h exists with defines for time types.

This is not a not a problem with gmtime() since mbedTLS is using windows specific implementation for this using the windows function GetSystemTime() instead of gmtime() (example: x509_get_current_time).

Is it possible to use a similar approach with time() as well?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-618

**Comment by sbutcher-arm** [comment]
Hi

If you'd like to make the change yourself, we can accept a contribution to make such a change, and that may be the quickest way to resolve the issue.

Otherwise, can you please describe the exact variant and version of Windows you are using, and if possible include links to the appropriate SDK? 

Thanks

**Comment by kattassen** [comment]
I am using windows CE (5.0 and 7.0), i don't know if time() exists in later versions. With my current configuration (client only) it is only an issue in ssl_cli.c and we managed to get around this with a small patch by not using time() in that specific case (by not using time as part of random number in client hello).

I will see if can produce an actual fix for this.

**Comment by kattassen** [comment]
I have made a pull request for a fix for this problem. #413

It seems that Windows CE team has made the decision to not include time() in any versions up to today. So this fix is valid for all Windows CE (#if defined(WINCE)).

**Comment by sbutcher-arm** [comment]
Users of the library now have the ability to provide their own platform specific `time()` function by providing an implementation of `mbedtls_time()`.  Therefore, for for anyone porting to Windows CE, it's possible to provide their own `time()` which should address this issue.

Unfortunately, within the resources of the Arm Mbed TLS project team, we don't have a development environment to build Windows CE, so it's hard for us to provide an 'out of the box' implementation of `mbedtls_time()`, as we have no means to test it.

Nonetheless, because it's now possible to get the library running on Windows CE without further changes to the library, I think this issue can be closed.

If anyone in the community would like to provide a Windows CE implementation of `mbedtls_time()` for inclusion in the library, we would welcome the contribution.
