### ISSUE TITLE
API/ABI Backward Compatibility Report

### ISSUE THREAD

**Issue by aponomarenko** [ARMmbed/mbedtls#415]
Hello,

Thank you for taking care of API/ABI backward compatibility of the library. It's very important for Linux maintainers like me.

I've prepared the ABI structure compatibility report for recent versions of the library and seems that backward binary compatibility is perfect: https://abi-laboratory.pro/tracker/timeline/mbedtls/

Hope this information may help you to continue maintaining binary compatibility and all other Linux maintainers of the library to be aware of ABI changes and SONAME bumps.

Thank you.

![mbedtls-1](https://cloud.githubusercontent.com/assets/1382645/24090824/0804b8ce-0d5d-11e7-9d3b-6c97c8c84cf7.png)

![mbedtls-2](https://cloud.githubusercontent.com/assets/1382645/24090836/12cab4b6-0d5d-11e7-848f-14cfa6421b43.png)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-626

**Comment by sbutcher-arm** [comment]
Thank you very much for this report. It is really good to see the report, and it reinforces to me the importance of trying to maintain the ABI/API and to do breaks only in a planned, structured way when necessary.

I've marked this as a question (although really it's informational) and will leave the issue open for a bit, to anyone interested in the project, as closing it will filter it out and prevent others seeing the report.

Thanks for your support in the project!

**Comment by sbutcher-arm** [comment]
Since this report has been introduced, we've added our own script, [abi_check.py](https://github.com/ARMmbed/mbedtls/blob/development/scripts/abi_check.py) to the library to verify the API and ABI of the library on each release.

So far we've been able to maintain compatibility on LTS branches consistently, but avoiding ABI breaks on the development branch has been a continual challenge.

Anyway, I don't see any need to keep this issue open any longer, so am closing it. If you want to know what the current status of the ABI/API is:
```
cd mbedtls
./script/abi_check.py -o <old version> -n <new version>
```

Where the version can be a tag (or I think a commit id).
