### ISSUE TITLE
3DES CMAC and supported key sizes

### ISSUE THREAD

**Issue by uglym8** [ARMmbed/mbedtls#4195]
Hey guys,

I'll be very grateful if you could clarify one thing for me:

I added 3DES CMAC support to OP-TEE some time ago (almost everything was already
there actually, in tomcrypt and mbedTLS respectively):
https://github.com/OP-TEE/optee_os/pull/4381

I was recently challenged by my fellow engineer about the supported key
sizes and I don't have enough data to back up my point.

Let me explain (I'll use key sizes with parity bits from now on).

My current understanding is that TDEA CMAC supports 3 keys (K1-K2-K3) and 2 keys
(K1-K2-K1).
If, for instance, I need to use 2 key TDEA CMAC what I'm doing (as a consumer of
this implementation not as an author) at the moment is just copying K1 to K3 and
have K1-K2-K1 192 bit long 3DES key.
My fellow engineer challenges this implementation by saying that he should not
be obliged to do it himself and that this implementation of 3DES CMAC is wrong
(not wrong, but incomplete).
Unfortunately, I don't have any sound proof that this is not the case.

I checked mbedTLS implementation and it also supports only 192-bit 3DES keys, so
for my case I need to do exactly the same (copying K1 to K3) before I'm able to
calculate 3DES CMAC.

I also checked Nettle, which states in its documention that
"As a 112 bit key is large enough to make brute force attacks impractical, some
applications uses a “two-key” variant of triple-DES. In this mode, the same key
bits are used for the first and the last DES box in the pipe, while the middle
box is keyed independently. The two-key variant is believed to be secure, i.e.
there are no known attacks significantly better than brute force. "

I've got two options atm:
1) modify TDEA CMAC implementation in a way that if 128 bit keys are supplied,
	it will transparently copy K1 to K3 by itself without requiring a user
	to do anything at all.
	It could be implemented by I don't think that this is the right thing to
	do tbh.
2) allow only 192 bits keys to be used for TDEA CMAC.
Right now a user can pass 128 bit keys but he gets incorrect result as keys are
not automatically transformed to 192 bit representation.

But as I said I can't prove that this is the right choice (limiting the key
size) as my opponent states that this would be incomplete solution as he 
thinks that he doesn't have to copy anything in case of 128 bit keys.

What was your rationale for allowing only 192 bit keys when you added TDEA CMAC support?

Thanks in advance.

**Comment by gilles-peskine-arm** [comment]
The world has pretty much stopped using any form of DES years ago outside of banking and people who want to implement all NIST-compliant algorithms. Mbed TLS isn't commonly used in banking, so DES has been a low-priority concern in Mbed TLS for a while. It was before my time, but I would guess that 2-key 3DES was never important enough to both with.

NIST stopped accepting 2-key 3DES except for legacy use a few years ago. (At least since 2017, with [SP 800-67 rev2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-67r2.pdf): see §3.1.)

If OP-TEE needs 2-key 3DES, I don't see anything wrong with copying K1 into K3. That's what `psa_cipher_setup` does. We'd accept a patch to make `psa_mac_setup` work for 2-key DES, if it currently doesn't (it probably doesn't since it has no special handling). But we'd probably accept a patch to remove single-key DES and 2-key 3DES support, too: I only added them because it validated that the interface and the implementation could handle quirks such as DES's.

(What I wrote here about the importance of DES is my personal opinion, not an official position of Arm.)

**Comment by uglym8** [comment]
@gilles-peskine-arm, thanks a lot for you reply.

> If OP-TEE needs 2-key 3DES, I don't see anything wrong with copying K1 into K3. 

Ok, I also asked OP-TEE guys what they think and I guess it could be the way to go if there's no strong objection:)
I don't think that OP-TEE really needed that implementation tbh, but I had to make sure that it gets to upstream due to different reasons.
