### ISSUE TITLE
mbedtls_ssl_conf_alpn_protocols copies only the pointer

### ISSUE THREAD

**Issue by bagder** [ARMmbed/mbedtls#420]
The `mbedtls_ssl_conf_alpn_protocols` function accepts a 'char **protocols' argument as its second parameter, as [documented](https://tls.mbed.org/api/ssl_8h.html#ae21135dddd89b2ef273c13e140097f5a).

What it doesn't say, is that it will only store that pointer and later iterate through the array assuming it remains in memory. If thus an array was stack-based when the mbedtls function was called, it will then traverse through illegal memory. This behavior was surprising to me (and us really) and caused a [segfault in curl](https://github.com/curl/curl/issues/642).

You should at least make it *very* clear in the documentation about such an assumption, or even better remove that need.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-635

**Comment by sbutcher-arm** [comment]
I agree the documentation fell short of what you should expect. We'll fix this as a documentation issue, and I've just created a topic branch 'iotssl-635-alpn-docfix' to address this.

Because one of the key uses of the library is in embedded applications and extremely memory constrained microcontrollers, I can see we could take a copy and persist the data it to avoid this API problem, but because in some uses every byte counts, I'd prefer just to have very clear documentation.

Sincere apologies we tripped you up on this, and thanks for the feedback.

**Comment by sbutcher-arm** [comment]
Branch and commit 8c4472af397c58c0a28416881f31229d554bdecd merged, so this can now be closed.
