### ISSUE TITLE
RSA sign "SIGSERV fatal error" Android5.0

### ISSUE THREAD

**Issue by icefrog** [ARMmbed/mbedtls#427]
Hi,

I built mbedtls in Android5.0, but RSA signing functions breaks down as "SIGSERV fatal error". RSA signing/verify works fine in Android4.0 and iOS.

The function caused break-down is` mbedtls_rsa_check_privkey()`, and `mbedtls_rsa_pkcs1_sign()`.

Need urgent help! Thanks.

**Comment by jcowgill** [comment]
Any more information - like the code for the program which segfaults, or a stacktrace? When you say "porting", did you modify mbedtls? Did you change the default config.h?

**Comment by icefrog** [comment]
I added a simple wrapper of rsa sign and did not change config.h. Basically I only need AES, bf, SHA256, and RSA sign/verify, and with all generate .o in /library, I manually linked necessary .o files into a .so.   Here is the make rule: ` gcc ../../library/aes.o ../../library/aesni.o ../../library/blowfish.o ../../library/xtea.o ../../library/sha1.o ../../library/sha256.o ../../library/rsa.o ../../library/bignum.o ../../library/md.o ../../library/oid.o ../../library/md_wrap.o ../../library/md5.o ../../library/sha512.o ../../library/ripemd160.o ../../library/asn1parse.o  ../../library/pkparse.o ../../library/padlock.o -fPIC -shared -o libmycrypto.so`

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-645

**Comment by icefrog** [comment]
Hi guys,

Please let me know if there are workrouns to do RSA sign/verify using mbedtls in Android 5.0

**Comment by jcowgill** [comment]
Instead of manually linking objects, you should edit config.h to disable the bits you don't need. In any case we need to see some code to be able to help you.

**Comment by NWilson** [comment]
There must be something specific to your configuration or toolchain (or application!) that's causing the problem, because I use all mbedTLS on Android 5.0, including RSA sign/verify/encrypt/decrypt, and all our tests pass for both RSA padding types.

**Comment by sbutcher-arm** [comment]
Hi @icefrog. I think it should be possible to compile and run the mbed TLS sample programs for Android, and to execute them in the Android shell using ADB. I suggest you try something like `rsa_sign`. That should work - and if it does, I'd look for the differences between your application and the sample program to identify the fault. And if `rsa_sign`doesn't work, we likely have a bug in mbed TLS to work on.

I don't think we're at the point we can call this a bug in mbed TLS yet, so I'm closing the issue, but if you find more information as to what's going wrong, please feel free to reopen the issue.

You may also be unaware, but we also have a forum for [mbed TLS over here](https://tls.mbed.org/discussions), that you may find helpful to discuss your issue.

**Comment by icefrog** [comment]
Hi @sbutcher-arm,

Thanks for the detailed suggestion, and we have solved it --  it is not a bug actually, which was caused by Java NDK mis-configuration(thanks @NWilson). This issue should be closed.

I have to say the code and makefiles in mbedtls are very clean, which is convenient for us to modify and build a "minimum" crypto library.  (we write a new makefile to link all _necessary_ .o files,  instead of modifying config.h, as we add a wrapper on mbedtls; I think more people prefer to modify config.h.)

So far, the library, contains AES, TEA, Blowfish, RSA sign/verify, has 180 kilo-bytes, and it seems to be difficult to minimum its size. Any advice to get a slimmer library is appreciated.

**Comment by sbutcher-arm** [comment]
There are definitely things you can do to reduce your code size by careful configuration of `config.h`, and link options. 

The first think to do to reduce the code size is to have a look at `config.h` (and possibly each source file you're using) and see what features you don't need. You may want to consider what bock modes you need, and maybe you don't need all of them. Depending on your application, you may not need the self-test functions, and maybe those too could be removed. Have a look because careful consideration of the options can dramatically reduce the code size more than just selecting what object file to link to.

Next, you may want to check your compiler and linker are not linking in code which you're not using. If you're using `gcc` for instance, you may want to ensure the `--gc-sections` option is passed to `ld` to strip out unused code, together with the compiler options `-ffunction-sections -fdata-sections`. There may be something similar for your compiler.
