### ISSUE TITLE
SAN issue in creating self-signed certificate

### ISSUE THREAD

**Issue by Sunil-jain1980** [ARMmbed/mbedtls#4364]
_Note:_ this is a template, please remove the parts that are not
applicable (these initial notes, and the "Bug" section for a Feature request
and vice-versa).

**Note:** to report a security vulnerability, see
[SECURITY.md](../SECURITY.md). Please do not use github issues for
vulnerabilities.

_Note:_ to get support, see [SUPPORT.md](../SUPPORT.md). Please do not use
github issues for questions.

---------------------------------------------------------------
### Description: This issue is related to web server communication, Our device is supporting web server, when we are trying to connect using any browser (Chrom, IE), we are getting malformed certificate with issue on SAN and handshake is aborted with error NET::ERR_CERT_INVALID. 

In our code, we are adding the SAN with mbedtls_x509write_crt_set_extension() to the self-signed certificate. 

- Type: Bug 
- Priority: Blocker 

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.16 

Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
Chrome   
Version:  89.0.4389.128

**Expected behavior**   : Certificate should not have any issue, while working with chrome

**Actual behavior**  : Chrome is discarding the certificate as Invalid certificate and communication aborted.

**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement / Feature Request

**Suggested enhancement**  

**Justification - why does the library need this feature?**

**Comment by gilles-peskine-arm** [comment]
I'm afraid it's impossible to help you with so little information. Maybe your code to generate the certificate is incorrect. Maybe your code to sign the certificate is incorrect. Maybe you're hitting a bug in Mbed TLS. Maybe you're configuring your server incorrectly.

It appears that you need support with Mbed TLS. We only use GitHub for bugs, not for support. You can ask for help with Mbed TLS on the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls). If you decide to post on the mailing list, make sure to post a **complete program** that creates the certificate that you have trouble with. People who read your message must be able to compile and run your program and run tests with the certificate.

I am closing this issue because there is no information regarding a bug in Mbed TLS.
