### ISSUE TITLE
Handshake with data connection on FTP server is failing with recv error

### ISSUE THREAD

**Issue by Sunil-jain1980** [ARMmbed/mbedtls#4365]
_Note:_ this is a template, please remove the parts that are not
applicable (these initial notes, and the "Bug" section for a Feature request
and vice-versa).

**Note:** to report a security vulnerability, see
[SECURITY.md](../SECURITY.md). Please do not use github issues for
vulnerabilities.

_Note:_ to get support, see [SUPPORT.md](../SUPPORT.md). Please do not use
github issues for questions.

---------------------------------------------------------------
### Description: We support FTP server on our platform, FTP server has 2 connection, Control(Port 21) and Data (port20). we are fine with Control connection and we are able to do handshake on control connection and files are listed properly. 

But there is a problem with Data connection, when we do handshake, server is expecting client key exchange and is waiting for this packet from client. Handshake is failing with recv error.

- Type: Bug | Enhancement / Feature Request
- Priority: Blocker | Major | Minor

---------------------------------------------------------------
## Bug

**OS**  
RTXC

**mbed TLS build:**  
Version: 2.16

Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  

**Expected behavior**   : Handshake with both Control and data connection should be fine

**Actual behavior**  : only Control connection is working fine.

**Steps to reproduce**  

----------------------------------------------------------------
## Enhancement / Feature Request

**Suggested enhancement**  

**Justification - why does the library need this feature?**

**Comment by gilles-peskine-arm** [comment]
> server is expecting client key exchange and is waiting for this packet from client

That's normal for a TLS connection. What's the problem?

Note that FTP uses an inverted data connection by default: on the data connection, the FTP client calls `listen` and the FTP server calls `connect`. In other words, the FTP server is a TCP client on the data connection, and the FTP client is a TCP server on the data connection. If the data connection is protected by TLS, the FTP server is the TLS server even on the data connection, despite being the TCP client. Modern software usually uses passive mode, which makes things simpler because the server is the server for everything and the client is the server for everything. But this has to be explicitly enabled with the `PASV` command on the command connection. Are you using passive mode?

Since this seems to be a support request, and no potential bug in Mbed TLS is identified, I am closing this issue. We don't use GitHub for support. You can post support requests on the [mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls). Be sure to include **complete code to reproduce the problem**.
