### ISSUE TITLE
Investigate rejecting the use of private fields

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4372]
In Mbed TLS 3, as a general rule, structure fields are considered private. In addition to [documenting this](https://github.com/ARMmbed/mbedtls/issues/4371), we should add some hurdles if applications try to access private fields directly.

The goal of this task is to investigate ways in which we can ensure that in typical cases, an application that tries to access private fields won't build. The definition of done is when the development team agrees on an approach and the approach has been tried on at least one sample case. The follow-up task #4373 covers implementing the chosen approach everywhere.

Here are a few possible ways to approach the problem:
* `__attribute__((deprecated("This field is private and should not be accessed directly in application code")))`. Can this be cast away in `static inline` functions? What about non-gcc-like compilers?
* `int *MBEDTLS_PRIVATE_FIELD(foo);` with `#define MBEDTLS_PRIVATE_FIELD(name) do_not_use_private_field_##name` in public headers and `#define MBEDTLS_PRIVATE_FIELD(name) name` when processing library code and invasive test code.
* `typedef struct {struct private_fields { /*private fields go here*/ }} foo_t`. Use `foo.private_fields` in library code.

**Comment by hanno-arm** [comment]
As pointed out by @mpg, this could be done in Mbed TLS 3.1 if we don't have time to work out and implement a good solution for 3.0.

**Comment by mstarzyk-mobica** [comment]
Usage of __attribute__((deprecated)) will generate a series of warnings when library build is launched. Did you mean to supress these for library build?

**Comment by gilles-peskine-arm** [comment]
No, we don't want to disable warnings about `__attribute__((deprecated))` when building the library. If we deprecate a feature but then still accidentally use it in the library, we want to know.

If we use this approach to highlight private fields, we need to arrange for that not to cause warnings when building the library. This is easy: `#define MBEDTLS_PRIVATE_FIELD __attribute__((deprecated))` in public headers, `#undef MBEDTLS_PRIVATE_FIELD #define MBEDTLS_PRIVATE_FIELD` when building the library. We also need to arrange for that not to cause warnings in `static inline` accessor functions when building applications, and that's not so easy.

**Comment by mstarzyk-mobica** [comment]
### Hiding struct implementation behind a pointer

struct PubliclyAccesible {
   struct Private* priv;
}

Private struct implementation would reside inside C files, making it inaccesible outside.
The drawback here is that some tests actually need to know how the Private struct looks like, AND
maintaining the priv pointer will require additional allocation and deallocation.
Probably not the best solution for baremetal or embedded in general.

### Using the \_\_attribute\_\_(depracted)

#if defined(USE_PRIVATE_MEMBERS)
#define PRIVATE_MEMBER __attribute__(deprecated("This attribute is private"))
#else
#define PRIVATE_MEMBER
#endif

struct PubliclyAccessible {
   int PRIVATE_MEMBER variable;

}

A library makefile would then define a copmilation flag -DALLOW_PRIVATE_ACCESS.
This approach gives quite good results, however there are several header files, which define a set of static inlines functions operating on the structs. There is no work-around for this, static inlines will always be a problem when their behavior is ment to depend on the build-time macro.

### Using a macro accessor

#ifndef ALLOW_PRIVATE_ACCESS
#define PRIVATE(member) private_##member
#else
#define PRIVATE(member) member
#endif

this will change the variables names to include a `private` prefix, if ALLOW_PRIVATE_ACCESS is not defined.
Library and test makefiles will define a ALLOW_PRIVATE_ACCESS before compilation, so that no name changing takes place inside library and tests.

Please have a look at the draft PR for this approach: #4409

**Comment by gilles-peskine-arm** [comment]
```
struct PubliclyAccesible {
    struct Private* priv;
}
```
is a no-starter because it requires additional memory allocations. But a plausible solution would be
```
struct PubliclyAccesible {
    struct Private priv;
}
```

**Comment by mstarzyk-mobica** [comment]
> ```
> struct PubliclyAccesible {
>     struct Private* priv;
> }
> ```
> 
> is a no-starter because it requires additional memory allocations. But a plausible solution would be
> 
> ```
> struct PubliclyAccesible {
>     struct Private priv;
> }
> ```

Yeah, but this will require the Private struct defintion to reside in header file.

**Comment by gilles-peskine-arm** [comment]
> Yeah, but this will require the Private struct defintion to reside in header file.

It has to anyway since the compiler needs to know the size, and also needs to know the definition of `static inline` accessor functions (which we do want to have, for performance and to reduce code size).

**Comment by mpg** [comment]
Also, keep in mind that the goal is not to prevent any access to private struct fields: it's only to prevent _unintentional_ access. Said otherwise, we're not trying to protect ourselves from users, we're trying to help good-faith users who might not have read this part of the documentation, or who have legacy code with direct accesses to struct field, to notice that we no longer support such accesses. (Then if some users choose to access private fields anyway, it's their choice, it just voids their backwards-compatibility warranty.)

**Comment by mstarzyk-mobica** [comment]
well, this:
```
struct PubliclyAccesible {
    struct Private priv;
}
```
will result in all library references change from this:
`struct.member` to `struct.private.member`
which doesnt differ much from simply renaming all struct variables by adding a "private_" prefix.

**Comment by mpg** [comment]
Agreed, I think of the three approaches mentioned above, the third one has my strong preference if we are to do anything in this direction.

1. Nested struct. One-time cost: change all struct definitions + all accesses in the library. Long-term cost: decreased readability in the library.
2. Attribute: doesn't work with static inline functions.
3. Macro. One-time cost: change all struct definition (each field). Long-term cost: none.

**Comment by mstarzyk-mobica** [comment]
> 
>     3. Macro. One-time cost: change all struct definition (each field). Long-term cost: none.

Regarding one-time cost, in addition to changing struct defitinions, every static inline function that uses these structs will have to modified as well.

**Comment by gilles-peskine-arm** [comment]
The investigation is concluded: we're going to go with the approach in https://github.com/ARMmbed/mbedtls/pull/4409, with a macro `MBEDTLS_PRIVATE` around member names that is defined to have the short name when building the library and unit tests, but `private_xxx` when building application code and sample programs.
