### ISSUE TITLE
Remove the `MBEDTLS_ECDH_LEGACY_CONTEXT` config.h option

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#4404]
This option was introduced purely for backwards compatibility. Since the whole point of 3.0 is we can break compatibility, let's remove this option

Work to do: see the next comment!

(Original list for reference, which has been split in multiple issues in the meantime.)

1. Change how restartable ECDH works so that `MBEDTLS_ECP_RESTARTABLE` no longer depends on  `MBEDTLS_ECDH_LEGACY_CONTEXT`. *This step might be tricky or require familiarity with that part of the code.* At the end, one should be able to build with `MBEDTLS_ECP_RESTARTABLE` defined and `MBEDTLS_ECDH_LEGACY_CONTEXT` unset and all tests passing.
2. Adapt the benchmark program so that it no longer depends on that option. Remove the test that's specific to that option in `test_suite_ecdh`.
3. Remove `MBEDTLS_ECDH_LEGACY_CONTEXT` and let the code behave as if it was always disabled.
4. In the end `MBEDTLS_ECDH_LEGACY_CONTEXT` should find no match except in the ChangeLog and the CI should pass.

**Comment by gilles-peskine-arm** [comment]
In 3.0, we can do just the API change part, and defer the rest for later. In 3.0:

* Remove `MBEDTLS_ECDH_LEGACY_CONTEXT` from `config.h` and `check_config.h`.
* Define `MBEDTLS_ECDH_LEGACY_CONTEXT` in `ecdh.h` if `MBEDTLS_ECP_RESTARTABLE` is enabled and undefine it otherwise.
* Pass `check-names.sh`.
* Possibly adjust dependencies in `test_suite_ecdh.function`.
* Adjust `all.sh`.

Then, later, make the ECC restartable code use the new context format (https://github.com/ARMmbed/mbedtls/issues/4440), and remove the dead code referencing the old context format (https://github.com/ARMmbed/mbedtls/issues/4441).

**Comment by mpg** [comment]
@gilles-peskine-arm good point, and thanks for creating new issues for the deferred parts! What do you suggest we do about the `benchmark` program in 3.0, though? Just accept that it won't benchmark that part in the default configuration?

**Comment by gilles-peskine-arm** [comment]
I hadn't noticed that the benchmark (and also, less importantly, `ecdh_curve25519.c`) depended on the legacy context. It would be better to upgrade it, and it doesn't look very hard, but I think it's acceptable to disable it temporarily and file a bug.
