### ISSUE TITLE
Fix return value of psa_mac_sign_setup for bad (not a Mac algorithm)

### ISSUE THREAD

**Issue by maulik-arm** [ARMmbed/mbedtls#4431]
---------------------------------------------------------------
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: 2.26.0

**Expected behavior**   
As per the PSA Crypto Spec 1.0.0, psa_mac_sign_setup should return PSA_ERROR_NOT_SUPPORTED if the algorithm is not supported or is not a MAC algorithm.

**Actual behavior**  
psa_mac_sign_setup returns PSA_ERROR_INVALID_ARGUMENT if the algorithm is not supported or is not a MAC algorithm.

**Some code debug notes:**
psa_mac_sign_setup() -> psa_mac_setup() -> psa_mac_init()
And in psa_mac_init(),
         if( ! PSA_ALG_IS_MAC( alg ) )
             status = PSA_ERROR_INVALID_ARGUMENT;

**Comment by gilles-peskine-arm** [comment]
Haven't we discussed this before? If an algorithm is not a supported MAC algorithm, both `INVALID_ARGUMENT` and `NOT_SUPPORTED` are permitted. An implementation is encouraged to use `NOT_SUPPORTED` for values that encode something that's valid, but is not supported by this particular implementation, and `INVALID_ARGUMENT` for values that encode something that's not a defined value or is incompatible with other parameters. There's an intermediate case where an implementation might not know whether a value is potentially valid or not, where both error codes are supported.

**Comment by ronald-cron-arm** [comment]
> So can you please clarify what the buggy case is? If `PSA_ALG_IS_MAC(alg)` is false, then `INVALID_ARGUMENT` is the preferred error code for `psa_mac_sign_setup`.

That's not what eventually makes it to the spec it seems:

PSA_ERROR_INVALID_ARGUMENT key is not compatible with alg.
PSA_ERROR_NOT_SUPPORTED alg is not supported or is not a MAC algorithm.

**Comment by gilles-peskine-arm** [comment]
The lists of error codes for each function in the specification are not exhaustive. An implementation is allowed to return other error codes if they make sense given the general description of the error.

I would definitely prefer for those lists to be exhaustive (outside of implementation-specific error conditions), but this requires a significant amount of editorial work that nobody has had time for.

**Comment by ronald-cron-arm** [comment]
> 
> 
> Haven't we discussed this before? If an algorithm is not a supported MAC algorithm, both `INVALID_ARGUMENT` and `NOT_SUPPORTED` are permitted. An implementation is encouraged to use `NOT_SUPPORTED` for values that encode something that's valid, but is not supported by this particular implementation, and `INVALID_ARGUMENT` for values that encode something that's not a defined value or is incompatible with other parameters. There's an intermediate case where an implementation might not know whether a value is potentially valid or not, where both error codes are supported.
> 

That sounds completely reasonable to me and in the particular case pointed to by this PR I also think that `INVALID_ARGUMENT` as error code is the best solution.

The only issue I see here is that it is written explicitly in the specification that if `alg` is not a MAC algorithm the error code should be  PSA_ERROR_NOT_SUPPORTED.

I think that in the compliance test suite, when it comes to check the returned error code for an invalid algorithm identifier in general, the test suite should allow both `INVALID_ARGUMENT` and `NOT_SUPPORTED`. Otherwise , @gilles-peskine-arm could we expect at some point in the specification some clarification along the lines of your first comment in this issue regarding the `INVALID_ARGUMENT/NOT_SUPPORTED' story?

**Comment by gilles-peskine-arm** [comment]
> could we expect at some point in the specification some clarification along the lines of your first comment in this issue regarding the `INVALID_ARGUMENT/NOT_SUPPORTED' story?

Yes. As usual, it requires someone to have the time. I admit we didn't have an issue filed for it, but now we do ([private link](https://github.com/ARMmbed/psa-crypto-api/issues/492)).

**Comment by ronald-cron-arm** [comment]
@maulik-arm With the above explanations and the creation of the issue in psa-crypto-api to amend the PSA specification are you ok to close this issue and get in touch with the team responsible for the PSA crypto compliance test suite to allow both `INVALID_ARGUMENT` and `NOT_SUPPORTED` error codes when it comes to "invalid algorithm" compliance tests ? We can help in the discussions with them if necessary.

**Comment by maulik-arm** [comment]
Hello @ronald-cron-arm , yes I can have the discussion with the compliance test team, but are you getting the specification amended? If yes, can you point me to the link/issue, so that I can take that forward with the compliance test team. Thank you.

**Comment by gilles-peskine-arm** [comment]
@maulik-arm We (speaking now as API spec maintainers) are tracking that at https://github.com/ARMmbed/psa-crypto-api/issues/492. You should have access now, let me know if other people (Arm employees or contractors only) need access.

Since we (the people involved in this discussion) seem to be in agreement to treat this as a lack of clarity in the specification, I (as an Mbed TLS maintainer) am closing this issue.

**Comment by maulik-arm** [comment]
Hi @gilles-peskine-arm ,  thank you for pointing me to the private issue page, where it is being tracked. I will get PSA compliance test updated to consider either of the two values.
