### ISSUE TITLE
mbedtls_pk_get_name vs the rest

### ISSUE THREAD

**Issue by azadkuh** [ARMmbed/mbedtls#446]
on failure or uninitialized context the `mbedtls_pk_get_name()` returns `"invalid PK"` which is weird and looks odd!

```
// on failure:
mbedtls_pk_get_name() -> "invalid PK"
mbedtls_md_get_name() -> NULL
mbedtls_cipher_get_name() -> NULL
```

isn't it better that this function returns `NULL` like the other two functions?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-688

**Comment by sbutcher-arm** [comment]
Hi!

Thanks for the feedback. This is a very good point! Obviously a change to NULL may break some code, so we'll look into this and see how we can best fix it.

**Comment by gilles-peskine-arm** [comment]
The value returned by this function is only useful for debugging since we don't specify what the name is for each algorithm. If we change the value to NULL, we would break the expectation that you can write the value to a debug log.

I thought that `mbedtls_md_get_name` would be consistent, but it does return NULL. I would prefer to change it to return `"invalid MD"` for consistency and usefulness.

**Comment by azadkuh** [comment]
@gilles-peskine-arm 
i understand your point (for debugging since ...), but it's a hack rather a good design.
a `xxx_get_name()` function should return a name or nothing! :)

IMHO it's better to have `xxx_get_error_message()` function or so for debugging or log-strings.

**Comment by RonEld** [comment]
The structure `mbedtls_pk_context` (and module) is planned to be removed with the introduction of `mbed-crypto`, therefore closing this issue as it won't be fixed.
