### ISSUE TITLE
SSLv3 ClientHello contains extensions

### ISSUE THREAD

**Issue by jay** [ARMmbed/mbedtls#454]
This is a c&p from [my post](https://tls.mbed.org/discussions/bug-report-issues/sslv3-clienthello-contains-extensions) in your forum which went unanswered:

I have some legacy devices which only use SSLv3. In OpenSSL 1.0.2g I can connect to those devices fine when I set the protocol to SSLv3 but in mbedTLS/2.2.1 I cannot.

The error is: curl: (35) ssl_handshake returned - mbedTLS: (-0x7780) SSL - A fatal alert message was received from our peer

The cipher on successful negotiation with OpenSSL is TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a). I can see in Wireshark that the working cipher is in the cipher list for mbedTLS.

I see a notable difference in Wireshark which is OpenSSL does not send any extensions for SSLv3 but mbedTLS does. Is this a bug or intended? Is there any way I can disable extensions to do further testing?

As of today, we're doing basically this when the user requires SSLv3:
```
    mbedtls_ssl_conf_min_version(&connssl->config, MBEDTLS_SSL_MAJOR_VERSION_3,
                                 MBEDTLS_SSL_MINOR_VERSION_0);
    mbedtls_ssl_conf_max_version(&connssl->config, MBEDTLS_SSL_MAJOR_VERSION_3,
                                 MBEDTLS_SSL_MINOR_VERSION_0);
    mbedtls_ssl_conf_ciphersuites(&connssl->config,
                                  mbedtls_ssl_list_ciphersuites());
```

There is no way in the forum to stay subscribed to an individual thread (it seems to be all or nothing) and I'm getting a lot of topics that don't concern me so I'm unsubscribing. If you reply there please let me know here. Thanks

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-700

**Comment by yanesca** [comment]
Dear Jay, Thank you for taking interest in mbed TLS! I've just posted a reply to your issue on the [forum](https://tls.mbed.org/discussions/bug-report-issues/sslv3-clienthello-contains-extensions).

**Comment by sbutcher-arm** [comment]
Although this is an interoperability problem, it's not strictly a bug in mbed TLS, as we are standards compliant. However, we are studying a possible solution, which is really a feature more than a fix.

**Comment by sbutcher-arm** [comment]
Hi @jay,

I've posted another response to the forum [here](https://tls.mbed.org/discussions/bug-report-issues/sslv3-clienthello-contains-extensions), and created a new issue #467 to track this as a new feature request.

Internally we've been tracking your question as a support question/bug and because the resolution is a new feature I wanted to create a new item, to avoid confusing the way we use JIRA to mirror Github.
As a consequence, I'm closing this issue, but please feel free to reply here, on the forum or on the other issue, depending on what works for you!

Hope this helps.
