### ISSUE TITLE
Make blinding mandatory (f_rng is no longer optional)

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4544]
### Context

Asymmetric cryptography in Mbed TLS uses blinding as a defense against side channel attacks. Blinding is a technique that requires a random generator. Because Mbed TLS does not have a global RNG, every function that needs to do blinding takes an RNG as a parameter.

For historical reasons, some functions are documented as having an optional RNG. This may be due to a wish to maintain backward compatibility, a wish to allow speeding up execution, or some other reason I am not aware of.

Supporting the no-rng case is a maintenance burden and is a security risk in applications. Furthermore, support is inconsistently available for some functions but not for others with similar security characteristics. Therefore we should make blinding mandatory.

### Proposal

Make the RNG parameter compulsory in all asymmetric cryptography that uses a private key.

### Work items for 3.0

* For every function that has a parameter `f_rng`, document it as mandatory. Check the rest of the documentation of the function and remove any documentation concerning the behavior when the RNG is omitted. For example, sometimes the documentation of `p_rng` has a clause about `f_rng` being `NULL`, which will need to be removed.
* Remove the configuration option `MBEDTLS_ECP_NO_INTERNAL_RNG` which is no longer necessary (it was a workaround to do blinding in `mbedtls_ecp_mul` even with a null RNG parameter). In `all.sh`, remove `component_test_ecp_no_internal_rng` and `component_test_ecp_restartable_no_internal_rng`, and elsewhere remove `set MBEDTLS_ECP_NO_INTERNAL_RNG`. Do the minimum in `ecp.c` for the CI to pass.

### Work items for 3.x

* Adapt all test code and sample program code that calls private-key functions without an RNG.
* Remove all the dead code to cope with `f_rng == NULL` in asymmetric crypto. In `ecp.c`, this includes removing all the code to define `ecp_drbg_xxx`.

**Comment by gilles-peskine-arm** [comment]
For RSA, https://github.com/ARMmbed/mbedtls/pull/4515 touches the documentation of `f_rng` in some functions, and I'm already requesting to document it as mandatory even if the code doesn't change yet.

**Comment by stevew817** [comment]
What about `_ALT` implementations of ECDSA and ECDH? They might be hitting an accelerator with builtin TRNG and blinding. In such case the `f_rng` parameter *should* be `NULL` (or at least be allowed to be `NULL`) IMO, because the implementation won't use the provided entropy for blinding.

**Comment by yanesca** [comment]
> In such case the `f_rng` parameter should be `NULL`

I think `_ALT` implementations should define a `f_rng` callback specific to their hardware which would need to be passed to the function. Of course depending on how the hardware operates, this might just be a dummy function and will never be called. (In this case it must always return an error so that if it is accidentally passed to other implementations it won't break their security).

If the user knows what hardware is underneath, they need to pass the corresponding callback and from their perspective it doesn't matter wether that will be called or not. If the user doesn't know what implementation they are dealing with, then they pass a callback to a secure random generator and the implementation is free to ignore it if it doesn't need one because the hardware does it internally.

**Comment by mpg** [comment]
In addition to documenting the requirement, I think we want to check in the code and return an error if `f_rng == NULL`. I think that's nicer than dereferencing a NULL pointer if the user failed to update their code when upgrading to 3.0. Any objections?

**Comment by gilles-peskine-arm** [comment]
In new functions, I would just call `f_rng` without checking, but because it's an easy-to-miss API change, I prefer to return a clean error in existing functions. This can be a 3.1 task, however.

**Comment by mpg** [comment]
Ok, I've started work on this, adding NULL checks in relevant places, and I'm glad I did it now rather than wait for 3.1, because it revealed illegal uses in the library that are only fixable by adding a `f_rng` parameter to other library functions (`mbedtls_ecp_check_pub_priv()` so far, probably more to come).

**Comment by mpg** [comment]
Houston, we may have a problem. (Which we should have seen coming, because it was right there in the report of the vulnerability that made us introduce the ECP internal RNG...) We have a few library functions that currently call `mbedtls_ecp_mul()` without a RNG:

- `mbedtls_ecp_check_pub_priv()` which is indirectly called by `mbedtls_pk_check_pair()`
- `mbedtls_pk_parse_key()` which is called by `mbedtls_pk_parse_keyfile()`

None of these functions have a `f_rng` parameter, nor (being `mbedtls_` as opposed to `psa_` functions) guaranteed access to a global RNG instance. So, unless we want to keep playing tricks with internal RNG instances (which I assume we don't), I guess our only option is to add a `f_rng` parameter to these 4 functions.

I think that's pretty natural for the `check_pub_priv`/`check_pair` functions: you would expect that such functions perform some kind of private key operation as part of their check, which needs to be protected.

For the parsing functions, I think as a users I'd be more surprised to have to pass a RNG in order to parse a private key... this is for the case where the public part of the keypair was either omitted from the encoding (which is legal) or encoded in a way that we don't support (compressed), in which case we re-construct it from the private key... which is a private key operation hence needs to be protected.

Wdyt?

**Comment by mpg** [comment]
Note: I've checked and I think those are the only instances of API changes caused by making the RNG param of `ecp_mul()` mandatory. I used `cflow --reverse --depth=6 *.c 2>/dev/null | sed -n '/^mbedtls_ecp_mul\b/,/^[^ ]/ s/().*//p' | head -n-1` and then went of the tree, cutting a branch as soon as an OK function was reached, and extracting the `pk_parse_key()` subtree that would be repeated otherwise:
```
mbedtls_ecp_mul
    mbedtls_ecjpake_write_round_two         OK: has f_rng param
    mbedtls_ecjpake_derive_secret           OK: has f_rng param
    ecjpake_test_load                       OK: selftest, can add dummy RNG
    mbedtls_ecp_gen_keypair_base            OK: has f_rng param
    mbedtls_ecp_check_pub_priv              NEEDS API CHANGE
        eckey_check_pair                    internal, called dynamically by...
            mbedtls_pk_check_pair           NEEDS API CHANGE
    self_test_point                         OK: has f_rng param
    mbedtls_ecp_self_test                   OK: has f_rng param
    pk_parse_key_sec1_der                   internal
        pk_parse_key_pkcs8_unencrypted_der  internal
            pk_parse_key_pkcs8_encrypted_der internal
                mbedtls_pk_parse_key        NEEDS API CHANGE + see below
            mbedtls_pk_parse_key            see below
        mbedtls_pk_parse_key                see below
    ecdsa_verify_hash                       OK: uses PSA RNG

mbedtls_pk_parse_key
    mbedtls_pk_parse_keyfile                NEEDS API CHANGE
    mbedtls_psa_rsa_load_representation     OK: can use PSA RNG
```

**Comment by gilles-peskine-arm** [comment]
> For the parsing functions, I think as a users I'd be more surprised to have to pass a RNG in order to parse a private key...

Maybe, but it fits the general philosophy of

> a private key operation hence needs to be protected

which is natural when the library relies on blinding for security.

> If we add an RNG parameter to pk_parse_key it's unclear to me whether we want to make it mandatory: on one hand, for now it's not needed for parsing RSA key, but OTOH who know in the future?

Let's make it mandatory. We don't know what will change — maybe in the future we'll want to prepare some blinding values while parsing the key. Or maybe `mbedtls_rsa_complete` will need blinding — in fact I'm a bit surprised it gets away without blinding now. And even if blinding remains only needed for certain types of keys, if users are using the pk API, then they're typically interested in algorithm agility so the API doesn't need to have algorithm-specific constraint relaxations.
