### ISSUE TITLE
MbedTLS Installation errors via Julia

### ISSUE THREAD

**Issue by kuanxu** [ARMmbed/mbedtls#456]
Hi,

I'm trying to install MbedTLS via Julia (v0.4.5). Here is the error message I came across. Is this a bug or am I missing something? Sorry if I'm wrong.

```
julia> Pkg.add("MbedTLS")
INFO: Installing MbedTLS v0.2.1
INFO: Building MbedTLS
cmake command not found. installing cmake is required for building from source.
===============================[ ERROR: MbedTLS ]===============================

LoadError: failed process: Process(`./cmake_check.sh`, ProcessExited(1)) [1]
while loading /home/kuan/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 69

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in /home/kuan/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-704

**Comment by sbutcher-arm** [comment]
I don't think the error is occurring in mbed TLS, but in the Julia packaging which seems to depend on cmake. mbed TLS can work without cmake, but it looks like Julia expects it.

You can find [cmake here](https://cmake.org/), and depending on your OS or Linux distribution, there are packages available for most platforms that will fix this issue.

Because this isn't an issue in mbed TLS, I'm closing the issue, but please feel free to come back and ask further questions if this doesn't help.
