### ISSUE TITLE
Question: Crypto features not related to TLS

### ISSUE THREAD

**Issue by prusnak** [ARMmbed/mbedtls#460]
What is the general stance of the project to accepting new crypto primitives or features not directly used in or related to SSL/TLS? Are you open to such additions (mbedtls wants to become a generic crypto library) or you want to keep it just as a SSL/TLS implementation?

What I have in mind are primitives used in cryptocurrenciesut not in TLS/SSL such as base58 or similar.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-707

**Comment by sbutcher-arm** [comment]
Thanks for the interest in mbed TLS and the offer!

mbed TLS is designed to be a portable small footprint TLS library. Generally we accept contributions related to only TLS. However, because it's commonly deployed into small embedded devices (which is why [ARM](http://www.arm.com/) supports it, we also accept contributions which are of use to embedded devices which often use the crypto stack for their own applications as well as the TLS stack. So we don't *just* accept TLS contributions and are broader.

Unfortunately cryptocurrencies are a little outside that, and while base58 has multiple uses and may be usable to some of our users, I don't think it's close enough to our core purpose to accept, although there may be other primitives which are.

If you'd like to propose something, I suggest you post it to the [mbed TLS forum](https://tls.mbed.org/discussions/feature-request), where it can be discussed.

I hope this helps!

**Comment by prusnak** [comment]
Thanks for clarification.
