### ISSUE TITLE
Document some structure fields as public

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#4603]
https://github.com/ARMmbed/mbedtls/pull/4511 systematically documents all structure fields as private.

But some structure fields should remain public. The goal of this task is to take care of fields that should obviously remain public.

* https://github.com/ARMmbed/mbedtls/pull/4595 documents several fields of `mbedtls_ecp_group` as public.
* `mbedtls_x509_crt_profile` only makes sense if all its fields are public. We should document explicitly that new versions of the library may add fields. Done by #4671

**Comment by mpg** [comment]
In the past I've seen application code access the `state` field of `mbedtls_ssl_context`. I don't think we necessarily want to make that field public (as it could hinder work on 1.3 which has a different state machine), but we probably want to make some info public, for example "is the handshake over yet?", otherwise exposing `mbedtls_ssl_handshake_step()` in the API makes little sense.

**Comment by mpg** [comment]
I'm marking this issue as "size: S" and closed by #4671 as the description says this is about "obvious" fields and apparently this is the last "obvious" thing we notice. Further work in this area is tracked in #4383 and #4683 for the somewhat-known parts, and the mostly-unknown parts are represented by #4682.
