### ISSUE TITLE
Purpose of mbedtls_ssl_set_hostname() ?

### ISSUE THREAD

**Issue by bagder** [ARMmbed/mbedtls#466]
This function is documented as:

    Set hostname for ServerName TLS extension (client-side only) 

... which sounds like it is used for SNI (only) ?

But if that is so, how do I tell mbedtls which host name we connect to, to use when verifying the server certificate? Isn't it so that this function is used to for that purpose as well? Shouldn't that then be documented? If not, how do I set it?

If this function is used for both, how do I set _only_ the host name to verify the cert with, without setting the SNI name to the same?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-716

**Comment by bagder** [comment]
It might not have been immediately obvious in my first description, but there's a security problem angle to this that we could take off the public eye until worked out.

**Comment by jcowgill** [comment]
The documentation isn't very clear, but that function does set the CN used to verify the server's certificate as well. If you just want to verify the server's certificate and not use SNI for some reason, you have to do it manually (eg using `mbedtls_ssl_conf_verify`).

**Comment by bagder** [comment]
If I connect to an IP address and not a host name, I still need to set the IP address as the "host name" for the CN/SAN comparison's sake (to make it fail the cert test), even though it isn't a valid SNI name and not actually a host name. Yes that is confusing...

**Comment by jcowgill** [comment]
Hmm I forgot about IP addresses. mbedTLS sending them as ServerNames is probably a bug (along with the documentation clarity).

**Comment by sbutcher-arm** [comment]
Hi @bagder,

First, in general, if you have a security concern, please feel free to contact us through the [mbed TLS website here](https://tls.mbed.org/contact), after which we can exchange emails and discuss any issue. Open forums aren't necessarily the best place to discuss security issues as we may not want all details to be public until we have a resolution.

Next, concerning your issue with `mbedtls_ssl_set_hostname()`, I will agree the documentation isn't clear and needs improvement, both for this function and also for our implementation of SNI generally, and because of that, I think unfortunately you may have jumped to the wrong conclusion on how SNI works for mbed TLS.

I will translate this issue internally into a 'Fix the SNI documentation' JIRA ticket, and we'll try and address this soon with a [knowledge base entry](https://tls.mbed.org/kb-search). (We only track issues in github which can be fixed by the community, so I won't change this ticket into a documentation issue).

The function `mbedtls_ssl_set_hostname()` is used to define the ServerName extension used for SNI, but not as the address to use to establish the connection. For that, we use the different function `mbedtls_net_connect()`, where you can specify a different IP address or hostname.

Have a look at the [sample client code here](https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/ssl_client2.c).

If I've missed something and you see a security issue, please contact me through the link above. I think I've answered your question as well as I can without better documentation, so I will close the issue now, but if you still have a concern, please reply or again, contact us on the link above.

**Comment by jcowgill** [comment]
This isn't about the hostname used for network connections, it is about there being two uses for the  `mbedtls_ssl_set_hostname` function which clash if used with an IP addresses:

- Setting the hostname used for the ServerName TLS extension.
- Setting the CN used to verify server certificates.

Unless I have missed something, if you want to connect to a server with a certificate issued to an IP address you either:

- Don't call `mbedtls_ssl_set_hostname` and then verify the CN manually.
- Call `mbedtls_ssl_set_hostname` to get mbedTLS to do it, but this will violate the standards which prohibit using IP addresses in the ServerName extension.

**Comment by bagder** [comment]
@jcowgill is exactly right. So I would just beg of you that after you make the functionality clarified in the docs, you consider providing a more standard compliant way in the future, as doing our own CN/SAN verification is quite a steep step from using an API call. Thanks for your help!

**Comment by sbutcher-arm** [comment]
@bagder Sorry, I obviously misunderstood what you meant by connect, but I'm afraid we don't yet support certificates issued to IP addresses. This is something that's coming, but not quite available yet and involves API changes which I don't believe suffer from this problem. However, I don't want to get into code that we haven't merged yet, so am I missing something else here?

**Comment by bagder** [comment]
If we connect to a host specified as an IP address, we **must** still use `mbedtls_ssl_set_hostname` (despite the name and the documentation not making it very obvious) - since otherwise the CN/SAN check is simply skipped. (or as you say implement the check ourselves) Setting the host name is required to have mbedTLS check the cert and since it is an IP address, fail the verification.

My issue is mostly about mbedTLS silently accepting the cert if we don't set the "host name".

**Comment by sbutcher-arm** [comment]
Hi @bagder,

Thanks for the feedback. We'll consider this in the support we're adding for IP addresses that we're adding. 

Because this is a design consideration, and not an issue of non-compliance nor defect, I'll now close the issue.

**Comment by bagder** [comment]
For reference, this is the security problem we managed to get ourselves into, partly because of the misleading documentation (that you still haven't updated): [CVE-2016-3739](https://curl.haxx.se/docs/adv_20160518.html)

**Comment by sbutcher-arm** [comment]
Thanks for pointing out the CVE code. 

The documentation issue is still in our backlog, and is scheduled to be clarified in our next release.

**Comment by deleisha** [comment]
Has this issue been fixed and available for use?

**Comment by tomoveu** [comment]
@bagder to the best of your knowledge has this been resolved?

I am having an issue connecting over https using psoc6 & Mbedtls that led me here. The server rejects my request with error 421 because of SNI mismatch.

**Comment by bagder** [comment]
No, this issue was not fixed, it was just closed and nothing was changed.

The documentation still does not state clearly that *not* calling this function will skip the certificate check. Unless of course the library was modified in the mean time to actually fail unless this function is called, which I suspect it does not.

**Comment by tomoveu** [comment]
thank you @bagder  , I will try to involve people from ARM's Trusted Firmware group because this is a concerning issue

**Comment by bagder** [comment]
I can see how [CVE-2025-27809](https://github.com/advisories/GHSA-76fv-m4gp-q47j) was ultimately created identifying this problem, with a subsequent fix in the 3.6.3 release.

I'm glad you finally fixed this, even if it took almost nine years since I told you about it. However, I think it is a little weak of you to not credit me in the CVE reporting.

I told you about this flaw.

**Comment by bagder** [comment]
**Daniel Stenberg** would be just fine, thanks!

**Comment by davidhorstmann-arm** [comment]
Excellent, thanks! We'll update the CVE, ChangeLog and advisory.

**Comment by gilles-peskine-arm** [comment]
@bagder Please accept my apologies. It is indeed the thread here that alerted us to the problem when we reexamined it in 2025 — we misunderstood the scope back in 2016. I should have credited you in the changelog entry (per our usual policy), but it escaped my mind when I wrote it. Sorry about this.
