### ISSUE TITLE
Investigate coding style automatic check and enforcement

### ISSUE THREAD

**Issue by ronald-cron-arm** [ARMmbed/mbedtls#4668]
### Suggested enhancement
Investigate how we could check automatically our coding style and have a tool to format C code according to our coding style.

Stories:
- CI runs a coding style check script and the associated job fails if the check script finds an issue in the PR code changes (check of the diff not of whole modified files).
- The project contains a coding style check and formatting script that developers can use to check and enforce the coding style before to submit their code to GitHub.

Coding style change ?
To achieve this the current [coding style](https://tls.mbed.org/kb/development/mbedtls-coding-standards) could be modify to simplify things but this is not mandatory. To not disturb too much our current coding practices a coding style quite close to the current one would probably be better. 

Level of enforcement?
The scripts do not need to reach 100% enforcement if it is too complicated to do so.

Tooling?
In preliminary discussions clang-tidy was mentioned as a possibly suitable tool.  

### Justification
Mbed TLS needs this because this would save development and review time.

**Comment by mstarzyk-mobica** [comment]
Clang Tidy offers a variety of style checks, such as

option | style/convention
-- | --
darwin- | Checks related to Darwin coding conventions.
fuchsia- | Checks related to Fuchsia coding conventions.
google- | Checks related to Google coding conventions.
hicpp- | Checks related to High Integrity C++ Coding Standard.
linuxkernel- | Checks related to the Linux Kernel coding conventions.
llvm- | Checks related to the LLVM coding conventions.
llvmlibc- | Checks related to the LLVM-libc coding standards.

Why don't we use the existing style, instead of a custom one?

**Comment by ronald-cron-arm** [comment]
That's definitively an option. Is there one that is quite close to our current coding style ?

**Comment by mstarzyk-mobica** [comment]
> That's definitively an option. Is there one that is quite close to our current coding style ?

I'm looking into it.

**Comment by mstarzyk-mobica** [comment]
Unfortunately existing coding styles are quite similar to each other, and all differ from ours significantly.

**linux kernel:**
```
int fun(int a)
{
        int result = 0;
        char *buffer;

        buffer = kmalloc(SIZE, GFP_KERNEL);
        if (!buffer)
                return -ENOMEM;

        if (condition1) {
                while (loop1) {
                        ...
                }
                result = 1;
                goto out_free_buffer;
        }
        ...
out_free_buffer:
        kfree(buffer);
        return result;
}
```

**darwin kernel:**
```
Boolean
OSCompareAndSwap8(UInt8 oldValue, UInt8 newValue, volatile UInt8 *address)
{
	return (Boolean)os_atomic_cmpxchg(address, oldValue, newValue, acq_rel);
}
```

**google (and fuchsia)**
```
class Shape {
 public:
  virtual void Rotate(double radians) = 0;
};

class Circle : public Shape {
 public:
  void Rotate(double radians) override;
};

void Circle::Rotate(double /*radians*/) {}
```

**llvm-libc**
```
LLVM_LIBC_FUNCTION(int, sigaction,
                   (int signal, const struct __sigaction *__restrict libc_new,
                    struct __sigaction *__restrict libc_old)) {
  struct sigaction kernel_new;
  if (libc_new) {
    copySigaction(kernel_new, *libc_new);
    if (!(kernel_new.sa_flags & SA_RESTORER)) {
      kernel_new.sa_flags |= SA_RESTORER;
      kernel_new.sa_restorer = __restore_rt;
    }
  }
  ...
}
```

**gnu**
```
for (i = 0; i < num_elements; i++)
  {
    foo[i] = foo[i] + 42;

    if (foo[i] < 35)
      {
        printf ("Foo!");
        foo[i]--;
      }
    else
      {
        printf ("Bar!");
        foo[i]++;
      }
  }
```

In summary:
* no existing style is using 4-space indent, it's either 2 or 8.
* no existing style is using a space between function's paranthesis and it's arguments,
such as ` int do_calc_length( const unsigned char *str )`

**Comment by mstarzyk-mobica** [comment]
Perhaps it's necessary to actually write our own clang-tidy config file, however I would suggest leaning towards existing styles when it comes to indentation or space placement.
btw - what is the reason behind mbedTLS using it's own coding style?

**Comment by gilles-peskine-arm** [comment]
I don't know why Mbed TLS has its own coding style. It's already the case in the first git commit from PolarSSL (ancestor project of Mbed TLS) but not in the most recent version I have from XySSL (ancestor project of PolarSSL). In any case, I want to move away from this style to a standard style.

Here are my requirements for the coding style:

* Must be reasonably standard so that people can easily read and write code. I propose to start with K&R style, because that's a well-established point of reference, and any deviation must be justified.
* Must be mostly enforced by a tool so that we don't waste effort in reviews.
* Must make the code easy to read and debug without special tooling.
    * No tabs because you will end up with different people using different tab widths.
    * Avoid or forbid multiple instructions on the same line because it makes it harder to step through in a debugger.
    * Braces are preferred or mandatory even for single-line loop/conditional blocks to avoid [goto fail](https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/) bugs.
    * Empty statements need a comment because a lone `{}` or `;` is easily lost in refactoring.
    * 80 columns is recommended because that's the standard width, but not enforced because it's extra work to make and review refactorings when they introduce line breaks in random places.
    * Avoid mandating too many blank or almost-empty lines (e.g. lines with only `{`) because vertical space is expensive — many people are stuck with wide but short monitors.

I think we have a consensus on using clang-tidy as the tool. So I propose to write a script that reindents the whole code base with a given style, and look at the output for the standard styles. Then we pick one and tweak it if desired.

All contributors should be able to run the tool, so we shouldn't require a version that's too recent. Note that our CI still has systems with Ubuntu 16.04 where the version of clang-tidy is 3.8, but we can live with only running the tool on Ubuntu 18.04 with Clang 6.0.

**Comment by mstarzyk-mobica** [comment]
I found the clang-format file that linux kernel is using.
https://github.com/torvalds/linux/blob/master/.clang-format
I believe this could be tweaked a bit to achieve desired outcome.

**Comment by mstarzyk-mobica** [comment]
Attached a PR with aes.c modified by
`clang-format library/aes.c -i`
