### ISSUE TITLE
Why MBEDTLS_HAVE_INT32/MBEDTLS_HAVE_INT64 and MBEDTLS_HAVE_ASM cannot be defined simultaneously?

### ISSUE THREAD

**Issue by jingdlu** [ARMmbed/mbedtls#4711]
https://github.com/ARMmbed/mbedtls/blob/e9bc8573278cca9208d6b3a08c48d3c9f7e240ec/include/mbedtls/check_config.h#L768

I want to use AES NI support on x86 platform, so need to define MBEDTLS_HAVE_ASM. Can I define MBEDTLS_HAVE_INT64 simultaneously? 

Thanks,
Jingdong

**Comment by yanesca** [comment]
Hi @jingdlu, thank you for taking interest in Mbed TLS.

Mbed TLS automatically detects if the target has 64 bit integers. The macros `MBEDTLS_HAVE_INT64` and `MBEDTLS_HAVE_INT32` are used to override this detection. Since you are on x86, Mbed TLS should detect your architecture correctly and you shouldn't need to define `MBEDTLS_HAVE_INT64`.

Also, we will be trying to answer questions on here on github as well, but you can reach much more people (and more likely to get an answer or might get better answers) on the mailing list:
https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls

**Comment by yanesca** [comment]
I am going to close this issue now, but please let us continue the discussion on the mailing list if you have follow-up questions :
https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls
