### ISSUE TITLE
missing limits.h in bignum.c

### ISSUE THREAD

**Issue by krisk0** [ARMmbed/mbedtls#4929]
### Summary

File **library/bignum.c** is using CHAR_BIT macro but does not include **limits.h**.

The file does not compile when other included headers do not include **limits.h**, for instance on Linux/glibc/gcc 10.3.0.

### System information

Mbed TLS version (number or commit id): 3c28fd3393a2e85
Operating system and version: Gentoo Linux x86_64, glibc
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): -O2 -march=native
Additional environment information: 

### Expected behavior

everything compiles

### Actual behavior

library/bignum.c does not compile

### Steps to reproduce

Attempt to build with gcc 10.3.0 on Glibc'ish Linux with MBEDTLS_BIGNUM_C is enabled

### Additional information

I suggest that you add **#include <limits.h>** to **bignum.c**.

**Comment by gilles-peskine-arm** [comment]
How are you building the library exactly? In Mbed TLS 3.0 there's an inclusion chain `bignum.c` → `common.h` → `mbedtls/build_info.h` → `mbedtls/check_config.h` → `limits.h`. This is quite convoluted and it would be a good idea for `bignum.c` to include `limits.h` directly, but I can't see how you could end up building `bignum.c` without including `limits.h`.

This is a genuine bug in 2.16 and 2.2x where the inclusion of `check_config.h` is recommended, but since it goes through the user's `config.h`, it isn't guaranteed.

**Comment by krisk0** [comment]
Yes, my config.h did not include check_config.h. Does it need to? If yes then this is my fault.

**Comment by gilles-peskine-arm** [comment]
With Mbed TLS 3.0.0+, there shouldn't be a way to bypass `check_config.h`. If you managed to do it, that's a bug of its own, please let us know how.

With Mbed TLS 2.x, it is possible to bypass `check_config.h`. The fact that the library doesn't build when `config.h` just contains `#include MBEDTLS_BIGNUM_C` and nothing else is a bug.

**Comment by krisk0** [comment]
I experimented with an old version (2.20, commit 1146b4e06011b), but mentioned fresh commit 3c28fd3 in my bug report. Sorry for that.
If check_config.h is included by config.h, then bignum compiles.
I don't mind if you close the bug.
