### ISSUE TITLE
Negative return value when handshaking 

### ISSUE THREAD

**Issue by SuchatNg** [ARMmbed/mbedtls#503]
Hi,
Now, I am porting mbedTLS (TLS1.2) on ARM-coretex-M3. I am using ssl_client2.c as an example for my implementation. After I ported ssl_client2.c on ARM, there is an return error after handshaking in case of "MBEDTLS_SSL_SERVER_HELLO"

. Seeding the random number generator...  . Loading the CA root certificate ...  . Loading the client cert. and key...
  . Connecting to tcp/64.90.48.15/443...
 Net_connect...ok

Setting up the SSL/TLS structure... ok
  . Performing the SSL/TLS handshake...SOCKET_CLOSED 
SOCKT_INTI 
SOCKET_CLOSED 
SOCKT_INTI 
SOCKET_ESTABLISTHED 

MBEDTLS_SSL_CLIENT_HELLO ==>
<== MBEDTLS_SSL_SERVER_HELLO...ret = 0xffff8880
 failed
  ! mbedtls_ssl_handshake returned -0x7780
 failed
  ! mbedtls_ssl_handshake returned -0x7780

How to fix?
Many Thanks,
Suchat Ngamchuen

**Comment by pjbakker** [comment]
Enabling debugging will probably help you pinpoint the exact problem better.
`-0x7780` is `MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE`, meaning a fatal message from the server was received. Most likely because there was no compatibility to work with.

This is not an issue in mbed TLS. For further support, please use the [discussion forum](https://tls.mbed.org/discussions)
