### ISSUE TITLE
Server handshakes with mismatched public/private key pair

### ISSUE THREAD

**Issue by attilamolnar** [ARMmbed/mbedtls#507]
mbedTLS does not verify that the public/private key pair matches when doing a handshake, resulting in client side public key signature verification errors if they don't match. This was tested on 2.2.1.

If this is the desired behavior then the documentation of `mbedtls_ssl_conf_own_cert()` should be updated to mention this fact and also point to `mbedtls_pk_check_pair()`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-821

**Comment by mpg** [comment]
@attilamolnar Thanks for your report, and sorry for taking so long to reply!

We think the behaviour is as intended, since the check can be computationally expensive, which turned out to be a problem for some users depending on their workflow. So we're going to apply your suggestion and update the documentation to clarify that and reference `mbedtls_pk_check_pair()`.
