### ISSUE TITLE
No way to disable assembly via Yotta

### ISSUE THREAD

**Issue by Timmmm** [ARMmbed/mbedtls#512]
I'm using mbedtls via Yotta on an nRF51. It doesn't support Thumb mode so I have to disable assembly.

Unfortunately although there is a `MBEDTLS_HAVE_ASM` define, it is on by default. I can edit the code in `yotta_modules/mbedtls/mbedtls/config.h` but that's not a great solution because it will be overwritten.

A better solution would be to have an `MBEDTLS_NO_ASM` which *isn't* defined by default.

This is still not the best solution because when switching targets I probably want to enable/disable assembly depending on whether they support Thumb or not. Unfortunately yotta targets don't expose that information as far as I can tell.

**Comment by sbutcher-arm** [comment]
I think the issue for me is we currently have no clean when of specifying configurations to the mbed TLS library from the project. This is a known issue on the project, but not one with a github bug number, so I'll leave this issue open to track the resolution.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-820

**Comment by sbutcher-arm** [comment]
Hi,

It has been pointed out to me that there is an existing means of reconfiguring the settings in `config.h` which is described in the yotta module readme [here](https://github.com/ARMmbed/mbedtls/blob/development/yotta/data/README.md#configuring-mbed-tls-features).

That file described how you can create your own header file to include into the build and undefined the option within that.

Because this has a known solution, I've closing the issue, but if you have any further questions, please feel free to reply.
