### ISSUE TITLE
CTR_DRBG doesn't check output buffer for NULL

### ISSUE THREAD

**Issue by Vge0rge** [ARMmbed/mbedtls#5122]
### Summary
The function mbedtls_ctr_drbg_random_with_add does not check for NULL pointers on the output buffer. If the output length is set to >0 then it will blindly try to memset it. 

It will be helpful for this to be tested before using the pointer.  Additionally the additional data buffer can be tested as well. 

### System information

Mbed TLS version (number or commit id): 4313d3ac876eb433fe1beea79c65f7a9e4e16ed5
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior
Return some error code when NULL is passed as as pointer for the output or the additional data.

### Actual behavior
An memory exception is raised when the buffers are NULL.

### Steps to reproduce
Call the function mbedtls_ctr_drbg_random_with_add with the output buffer as NULL but the output length > 0.

**Comment by mpg** [comment]
Thanks for your report. However, not having NULL checks in all public functions that accept pointers is a deliberate choice. Having those checks would significantly increase the code size (and one of the goals of Mbed TLS is to be usable on highly constrained devices) while not providing enough value to make up for it.

In previous versions of Mbed TLS (all 2.x version starting with 2.16) there was a compile-time option `MBEDTLS_CHECK_PARAMS` that could be enabled to add such checks in an number of modules of the library (but apparently CTR-DRBG wasn't covered). In 3.0 we decided to remove that option because in our opinion it didn't bring enough value to justify its cost in terms of maintenance and testing.

So I'm afraid adding this check is not something we want to do, sorry.

What we probably want to do however is to explicitly mention in the documentation that this parameter must not be NULL, so I've opened https://github.com/ARMmbed/mbedtls/issues/5130 in order to track that.
