### ISSUE TITLE
Server certificate request with TLS 1.2

### ISSUE THREAD

**Issue by teumas** [ARMmbed/mbedtls#513]
I posted this in the mbedtls forum, here comes an updated version including the Client hello:

I run a webserver (hiawatha) which uses mbedtls 2.2.1. I have it configured to require client certificates for https access. I have a problem accessing the webserver from Internet Explorer using TLS 1.2.

Looking at the tls handshake:

In TLS 1.2 the 'supported_signature_algorithms' field was added to the certificate request sent by the server. It seems that mbedtls populates this field with data which invalidates the client certificate I have in IE. These images show part of the TLS handshake as captured by wireshark:

Client hello: http://imgbay.mobi/di/clienthello-jv23v.png

Server hello which decided cipher suite: http://imgbay.mobi/di/serverhello-jlx7a.png

Server certificate sent to client: http://imgbay.mobi/di/servercert-yentg.png

Server certificate request sent to client: http://imgbay.mobi/di/certificatereq-ewl2w.png

The client certificate uses the same algorithm as the server certificate (sha256 with rsa), but since the server requires sha384, IE says it does not have any valid certificates. (Looking at the Schannel event log client-side on Windows I get: "The remote server has requested TLS client authentication, but no suitable client certificate could be found.")

TLS 1.2 works on Firefox but that seems to be because they negotiate another cipher suite (ECDHE-ECDSA-AES128-GCM-SHA256), which makes mbedtls populate the 'supported_signature_algorithms' field with sha256 instead of sha384.

I am no expert on cipher suites, but it seems odd that mbedtls server side allows a cipher suite which would invalidate its own certificate.

Thankful for any help,

Thomas

**Comment by pjbakker** [comment]
Thomas,

The screenshot for the ClientHello only seems cutoff. The bottom part is what I'm interested in: the part after the list of ciphersuites (where the extensions live). Can you share that as well?

**Comment by teumas** [comment]
Just noticed I could export the data in text format, much easier than taking screenshots.. :)

[client-hello.txt](https://github.com/ARMmbed/mbedtls/files/318653/client-hello.txt)

**Comment by pjbakker** [comment]
Ok, thanks for the extra information.

The extension indicates what the client wants to receive from the server in the ServerCertificate and the ServerKeyExchange messages.

The list in the CertificateRequest messsage is what the server wants to receive in line of the current ciphersuite / capabilities. It does not 'invalidate' it's own certificate.
 
The behaviour is not optimal in your situation, but technically correct.
 
There is a decision to make there in the code. The server functionally supports a list of signature algorithms. But what MD is allowed to provide integrity in the certificate of the client for a connection that has it's security level set at SHA-384 (because of the ciphersuite)? Allowing a "lower" MD could mean that the whole connection security level should be considered lower as well. The current behaviour is to only allow the same sig alg as the connection (SHA-384) in your case. Which avoids the complex decision at that point.
 
And as IE indicates it wants a SHA-384 ciphersuite over a SHA-256 ciphersuite that breaks down.

When viewing it in your example, it seems overly strict. Then again. It upholds the security level negotiated with the client.
 
Better behaviour would be to allow a wider range of trusted MDs. Possibly should be part of our security profiles.

Short answer now: yes, the behaviour you see is technically correct. But an overly strict implementation. We will look at a less strict implementation within the bounds of security.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-819

**Comment by teumas** [comment]
Okay, thank you for the reply.

Regarding what you said about choosing a 'lower' MD for client certificate than that of the cipher suite, isn't the same true about the server certificate? Since the server chooses a SHA-256 certificate with a SHA-383 cipher suite, won't that lower the security level the same way?

Either way, seems like a complicated issue. Guess I'll take the easy way out and revert to 1.1 on I.E.

**Comment by pjbakker** [comment]
Yes it does. It's not consistent and that why I consider the current choices we made overly strict.

**Comment by sbutcher-arm** [comment]
This issue was fixed in PR #637 which was merged in `mbedtls-2.4.0` and shipped sometime ago. For some reason the PR was never closed, nor was this issue, so closing now.
