### ISSUE TITLE
mbedtls_timing_delay_context private fields getters

### ISSUE THREAD

**Issue by jaudiger** [ARMmbed/mbedtls#5183]
### Suggested enhancement

I would like to have access to private fields of `mbedtls_timing_delay_context` through getters. Right now, I'm using macro `MBEDTLS_PRIVATE()`.

### Justification

I have a use case where I need to handle the DTLS handshaking, and I need to know the next timer to send retransmissions.

For now, I just need to access the private fields:

- `fin_ms`

**Comment by mpg** [comment]
Thanks for your report!

Please note that you're welcome to write your own timer management function and pass them to `mbedtls_ssl_set_timer_cb()` instead of using the functions and structures from `timing.h`. This might give you more flexibility than trying to adapt the existing functions and structures if you need to do things very differently.

However, if the provided functions almost fit your needs, except for this point (read access to `fin_ms`), then indeed it makes sense to re-use the existing functions and structures and just add read access to this field.

Could you clarify a bit what is you use case and why you need access to this field? Thanks!

**Comment by jaudiger** [comment]
Hi @mpg,

I'm aware of the ability to set my own timer callbacks. But the ones provided through `mbedtls_timing_set_delay` and `mbedtls_timing_get_delay` are fine for my use case:

```c
mbedtls_ssl_set_timer_cb(sslContext, timingDelayCtx, mbedtls_timing_set_delay, mbedtls_timing_get_delay);
```

I have a DTLS/TLS Server application that needs to handle multiple clients at the same time. For this purpose, I'm calling `mbedtls_ssl_handshake_step()` and I need to know when to call it again if I don't received any message from the peer.

**Comment by mpg** [comment]
Ok, thanks for clarifying that.

I'm relabeling as "regression" as that's a legitimate use case that used to work before 3.0 and is now broken.
