### ISSUE TITLE
hardware acceleration for mbedtls_mpi_exp_mod, ecp_mul_comb, mbedtls_gcm_crypt_and_tag and etc

### ISSUE THREAD

**Issue by versaloon** [ARMmbed/mbedtls#5239]
### Suggested enhancement

I'm porting mbedtls to a wifi soc with hardware crypto engine, which can accelerate some APIs in mbedtls, like mbedtls_mpi_exp_mod etc. But I can not find MBEDTLS_XXX_ALT macros for these APIs. Is it possible to add _ALT configrations for these APIs or more APIs which are possible to be accelerated by hw?

Below is the list of APIs the wifi soc can support without MBEDTLS_XXX_ALT configurations:
mbedtls_aes_crypt_cbc
mbedtls_mpi_exp_mod
ecp_mul_comb
mbedtls_gcm_crypt_and_tag
mbedtls_sha256_ret

**Comment by versaloon** [comment]
For sha256 APIs, I think I will use MBEDTLS_SHA256_ALT.

**Comment by davidhorstmann-arm** [comment]
Thanks for your request!

Unfortunately we won't be adding any more `_ALT` interfaces as these are in the process of being deprecated. Going forward, the [PSA Crypto Device Driver API](https://github.com/ARMmbed/mbedtls/blob/development/docs/proposed/psa-driver-interface.md) is the recommended interface to hardware accelerators.

That being said, you should be able to use accelerators for all of these functions except `mbedtls_mpi_exp_mod()` using the existing `_ALT` interfaces by replacing whole modules, rather than just the individual functions. The relevant `_ALT` interfaces to use are: `MBEDTLS_AES_ALT`, `MBEDTLS_ECP_ALT`, `MBEDTLS_GCM_ALT` and `MBEDTLS_SHA256_ALT` (as you mentioned in your comment above).

You should also be able to use `MBEDTLS_RSA_ALT` and `MBEDTLS_DHM_ALT` to replace the RSA and DHM modules with modified ones that use the accelerator for `mbedtls_mpi_exp_mod()`.

**Comment by versaloon** [comment]
Thanks, I will take a look into these APIs.
