### ISSUE TITLE
PSA AEAD: detect invalid tag lengths during setup

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#5285]
`psa_aead_{encrypt,decrypt}_setup` don't always complain if the tag length encoded in the algorithm is invalid. The goal of this issue is to ensure that they do and that this is tested.

Acceptance: for each of {ChachaPoly, CCM, GCM},  
for each of a reasonable selection of invalid tag lengths (must include at least 0, min_tag_length-1 and, for CCM and GCM, a value between min_tag_length and max_tag_length),  
for each of {encrypt,decrypt}_setup,  
there shall be a passing test case validating that setup fails.

**Comment by AndrzejKurek** [comment]
The information about tag length is buried within the `operation->ctx.mbedtls_ctx`, or, in case of the test driver, `operation->ctx.transparent_test_driver_ctx`, and is set after a call to `psa_driver_wrapper_aead_encrypt_setup`.
The `psa_crypto.c` level of abstraction should (presumably) not check what's inside, so should the checks be added in `psa_crypto_driver_wrappers.c`? If so - there will be two separate calls (due to different contexts used): 
- to check the test driver implementation;
- to check the `mbedtls_psa_aead_encrypt_setup` implementation.
Since we only can inject errors to the test driver implementation, that's where the negative cases will be. Did you have a different approach in mind?

**Comment by gilles-peskine-arm** [comment]
`psa_crypto_aead.c` already has some code to validate tag lengths, but it's incomplete. For example:
```
            operation->alg = PSA_ALG_CCM;
            full_tag_length = 16;
            /* CCM allows the following tag lengths: 4, 6, 8, 10, 12, 14, 16.
             * The call to mbedtls_ccm_encrypt_and_tag or
             * mbedtls_ccm_auth_decrypt will validate the tag length. */
```
This was ok for one-shot operations, but it effectively delays the validation of the tag length until the `finish` call in multipart operations. Instead the tag length validation should be done during setup. The information in the comment should instead be enforced by the code.

**Comment by gilles-peskine-arm** [comment]
And regarding drivers: I think this validation should be in the front-end in `psa_crypto.c`, rather than only in our software implementation. Generally driver writers aren't always good at validating inputs, so it would be better to do all the validation we can in the generic code.
