### ISSUE TITLE
PSA AEAD: clarify testing of set_nonce + set_lengths

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#5287]
The unit tests for PSA multipart AEAD support calling `psa_aead_set_lengths` before `psa_aead_set_nonce`, after `psa_aead_set_nonce`, or not at all (which is an error for CCM). This is done in part based on certain bits in the input data, which makes it very hard to figure out the test coverage.

The goals of this task are:
1. Rework the applicable test functions so that the chosen set_lengths method is apparent in the test parameters.
2. Annotate test descriptions accordingly.
3. Ensure that there is adequate coverage:
    * Good case for all three methods, for each of CCM (except omitting set_lengths), GCM and ChachaPoly
    * Non-matching (too short, too long) AEAD length, for all three methods, for each algorithm
    * Non-matching (too short, too long) plaintext length, for all three methods, for each algorithm

**Comment by AndrzejKurek** [comment]
Would it be suitable to extend testing too lengthy `plaintext_length` and `ad_length` in [this function](https://github.com/ARMmbed/mbedtls/pull/5344/files#diff-7759025a8a7b87158e40d5c6789bdd199e68e51c95f3ff3d50ed34ebfdfbb14eR4817) in combination with set_nonce, instead of introducing three more (`ad_len`, `plaintext_len`, `expected_set_lengths_status`) arguments to the `aead_multipart_set_nonce` test?
The rest of the scope is handled here: https://github.com/ARMmbed/mbedtls/pull/5363.
