### ISSUE TITLE
TLS ECDH 2c: ECHDE in TLS 1.3 (client-side)

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#5321]
This task is to implement the ECDHE computation in the TLS 1.3 ephemeral key exchange (as it is in MVP, so client-side only) using PSA, regardless of the value of `MBEDTLS_USE_PSA_CRYPTO` (as that option is only for 1.2, and 1.3 should always use PSA).

See #2338 and #5291 for client-side support of ECDHE-ECDSA and ECDHE-RSA in TLS 1.2, and the description of #5317 for a comparison between the legacy `mbedtls_ecdh_` API and PSA Crypto.

**Note:** On-the-wire format for ECDHE parameters slightly differs between 1.2 and 1.3, so the TLS-specific writing/parsing code will probably differ. It's still possible to look at the 1.2 code for inspiration, keeping that in mind.

- [x] Make sure the `ecdh_psa_xxx` fields in `struct mbedtls_ssl_handshake_params` are present when TLS 1.3 is enabled even if `MBEDTLS_USE_PSA_CRYPTO` isn't.
- [x] #5509
- [x] Change `ssl_tls13_read_public_ecdhe_share()` to use TLS-specific parsing code.
- [x] Change `mbedtls_ssl_tls13_key_schedule_stage_handshake()` to use `psa_raw_key_agreement()`.

Depends on: #5291 (cleaned 1.2 code for re-use or inspiration).

**Comment by mprse** [comment]
I read about TLS Handshake 1.2 vs 1.3. In 1.3 version the number of transfers was reduced in order to speed up the process. As a result [ClientKeyExchange](https://datatracker.ietf.org/doc/html/rfc4492#section-5.7) message has been removed and in 1.3 public key is send together with Client Hello message in [key share extension](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.8). The goal here is to implement [ECDHE computation](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.8.2) for  TLS 1.3.

So looking at the second bullet. `ssl_tls13_generate_and_write_ecdh_key_exchange()` has to populate `key_exchange`  field of a `KeyShareEntry` in a `KeyShare` structure. `key_exchange` has the following format:
```
      struct {
          uint8 legacy_form = 4;
          opaque X[coordinate_length];
          opaque Y[coordinate_length];
      } UncompressedPointRepresentation;
```
and it seem that it is consistent with the result of `psa_export_public_key()`:
https://github.com/ARMmbed/mbedtls/blob/6ca6faa67e8ef792f05eedb12af5255a6641cd0a/include/psa/crypto.h#L779-L785

Does it mean that the output from `psa_export_public_key()` can be directly copied into the given buffer (for `key_exchange`) ?

When I was looking on current implementation for 1.3 (non-psa) this covers only one case for `MBEDTLS_ECP_TYPE_SHORT_WEIERSTRASS` group and `MBEDTLS_ECP_PF_UNCOMPRESSED` format:
https://github.com/ARMmbed/mbedtls/blob/6ca6faa67e8ef792f05eedb12af5255a6641cd0a/library/ecp.c#L721-L791

**Comment by mpg** [comment]
> Does it mean that the output from `psa_export_public_key()` can be directly copied into the given buffer (for `key_exchange`) ?

Yes, that should be the case, both for Short Weierstrass curves (secp256r1, secp384r1, and secp521r1) and for x25519, so you shouldn't have any transcoding do to. (TLS 1.2 originally had two points formats: compressed and uncompressed, now compressed has been deprecated, and we never had full support for it anyway (we could write but not read it) - TLS 1.3 only has uncompressed.)

(Also, when you read "peers MUST validate each other's public value Q by ensuring that the point is a valid point on the elliptic curve.", that's not something you need to worry about: it happens automatically when using the value to compute the shared secret, no need for a separate check.)

I'm not yet fully familiar with TLS 1.3, so take what follows with a grain of salt, but the formats should be fairly similar except for the following differences:

- As you pointed out, the names and more importantly ordering of the messages is different: in 1.2 (with ECDHE-RSA and ECDHE-ECDSA) the server sends its share first in ServerKeyExchange and the client replies in ClientKeyExchange; in 1.3 the client goes first with one or more shares in the the key share extension of its ClientHello, and the server responds in the key share extension of its ServerHello.
- As a consequence, in TLS 1.2 the server has to encode which curve it chose while the client doesn't; in TLS 1.3 I think both parties have to encode the chosen/offered curve(s)
- In TLS 1.2 when encoding the curve, we first need to encode the "curve type" (named or explicit), in TLS 1.3 only named curves are supported so the `curve_type` byte is not needed (also, terminology issues: NamedGroup in 1.3 is the equivalent of NamedCurve in 1.2).

So, except for the "extras" (namedcurve/group, possibly list structure, etc), the formats of the actual key shares should be identical between 1.2 and 1.3, and identical to the format PSA uses for inputs and outputs.
