### ISSUE TITLE
Out-of-bounds access to a buffer in ssl_tls.c is reported as high severity vulnerability by polaris

### ISSUE THREAD

**Issue by mmshaikh88** [ARMmbed/mbedtls#5375]
Following vulnerability is reported in mbedtls code for the version # 2.27.0:

Description: Access of memory not owned by this buffer may cause crashes or incorrect computations.

Related To:
CWE-119 CWE-121 CWE-122 CWE-123 CWE-124 PCI DSS 2018 2020 CWE Top 25 2019 CWE Top 25 7 Technical Risk Indicators

Contributing Code Events:

```
When MBEDTLS_SSL_PROTO_SSL3 is not defined, MBEDTLS_SSL_VERIFY_DATA_MAX_LEN is defined as 12.

In file ssl_tls.c

1. In function mbedtls_ssl_write_finished() condition "ssl->minor_ver == MBEDTLS_SSL_MINOR_VERSION_0", taking true branch.

2. Assigning: "hash_len" = "(ssl->minor_ver == 0) ? 36 : 12". The value of "hash_len" is now 36.

3459:    hash_len = ( ssl->minor_ver == MBEDTLS_SSL_MINOR_VERSION_0 ) ? 36 : 12;

3. Overrunning array "ssl->own_verify_data" of 12 bytes by passing it to a function which accesses it at byte offset 35 using argument "hash_len" (which evaluates to 36). [Note: The source code implementation of the function has been overridden by a builtin model.]

3463:    memcpy( ssl->own_verify_data, ssl->out_msg + 4, hash_len );
3464:#endif
3465:
3466:    ssl->out_msglen  = 4 + hash_len;
3467:    ssl->out_msgtype = MBEDTLS_SSL_MSG_HANDSHAKE;
```

**Comment by gilles-peskine-arm** [comment]
Thanks for reporting this! However, it's a false positive. When `mbedls_ssl_write_finished` is called, we know that `ssl->major_ver` and `ssl->minor_ver` designate a protocol version that's supported (otherwise the connection would stop well before the Finished message). `ssl->minor_ver == MBEDTLS_SSL_MINOR_VERSION_0` is only true for the protocol version SSL 3.0. This protocol version is only supported when `MBEDTLS_SSL_PROTO_SSL3` is defined. So, if `MBEDTLS_SSL_PROTO_SSL3` is not defined, then `ssl->minor_ver > 0` and so `hash_len` is set to 12, which is consistent with the definition of `MBEDTLS_SSL_VERIFY_DATA_MAX_LEN`.
