### ISSUE TITLE
What's the difference between TLS-ECDH-RSA-WITH-XXX and TLS-ECDH-ECDSA-WIT-HXXX

### ISSUE THREAD

**Issue by mrpre** [ARMmbed/mbedtls#612]
In server auth only, I dont't see any signature process in SSL handshake. So I want know what the 'RSA' or the 'ECDSA' (with ECDH)indicate.

**Comment by yanesca** [comment]
Hi @mrpre, thank you for taking interest in mbed TLS! Don't worry it is intentional: the reference to the signature in the cipher-suite name has a different meaning with DH and ECDH. 

In cipher-suites with DH and ECDH in their names the key agreement protocol uses fixed keys and therefore the server doesn't need to sign an ephemeral key to prove his identity. It has to provide a certificate applicable for the agreed Diffie-Hellman variant (DH or ECDH) and this certificate will prove the servers identity. The signature algorithm in the cipher-suite name refers to the algorithm with which the CA has to sign the servers certificate.

You can find more information on this in the [standard](https://tools.ietf.org/html/rfc4492#section-2.1).

**Comment by mrpre** [comment]
@yanesca Thank you for explaining so fully.
According to RFC , 'MUST' is used while describing 'ECDH_RSA'. 
Dose it means that server must ignore the cipher-suit ECDH_RSA(in clienthello's cipher-suit list) wihle the server are loading the ECDSA certificate , and the client must reject the connection after receiving the ECDSA signed certificate with cipher-suit ECDH-RSA ?

But both are ok when i use 'ECDH-RSA' and 'ECDH-ECDSA' to connect the server(./ssl_server2) which have load a certificate signed with ECDSA.

version: mbedtls-2.2.1

**Comment by yanesca** [comment]
You are right, that may be a problem...

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-987

**Comment by sbutcher-arm** [comment]
This issue has been duplicated by #1561, therefore closing this issue to be followed up there.
