### ISSUE TITLE
Disable seldomly needed exotic elliptic curves by default

### ISSUE THREAD

**Issue by hardfalcon** [ARMmbed/mbedtls#620]
Right now, mbedTLS by default advertises no less than 11 different curves to TLS clients, albeit no more than two or three of these (secp384r1, secp256r1 and perhaps secp521r1) are relevant in practical usage. More or less all of the offered curves are problematic according the well known "safe curves" table by Dan Bernstein:
https://safecurves.cr.yp.to/

Wouldn't it be a more sane alternative to disable by default all curves but the two or three named above? Right know, even curves such as secp192r1 and secp192k1 are supported and advertised by default, although they only offer a security level of 96 bits at best.

**Comment by sbutcher-arm** [comment]
Bernstein's recommendations are about how easy or how difficult it is to implement some curves correctly, and how many implementations leak information that can be exploited.  That doesn't mean the curves themselves are inherently unsafe, but that the implementations are difficult to do and difficult to trust.

Our defaults are carefully chosen for interoperability, code footprint and adherence to standards, and as an open source library we leave it open to those using the library to ultimately decide for themselves what to use.

**Comment by gilles-peskine-arm** [comment]
There was no pressing need to disable any curves, so we maintained backward compatibility with the default configuration throughout Mbed TLS 2.x. However, in Mbed TLS 3.0, I think it's time to disable some less-used curves by default.

We are not going to restrict the library to “safe curves”. A “safe curve” is one that is easier to implement securely; curves that are not “safe” according to DJB are actually safe in the vernacular sense if implemented securely.

What curves should be disabled by default? Since 2015, there is a “next-generation” profile `mbedtls_x509_crt_profile_next`. Now would be a good time to switch to this profile — but of course, 6 years later, we may want to revisit it.

As it turns out, the profile exactly corresponds (for Weierstrass curves) to disabling curves smaller than 256 bits. So I propose to do just that. This leaves three Brainpool curves, three NIST P curves, and SECP256K1.

I do not propose to disable Brainpool curves. It's good to have another curve family available in case a systemic problem affects the SEC P curves. I don't see any reason to disable the one Koblitz curve that's large enough.

Arguably we could disable SECP521R1 which is more prone to side channel attacks and is not even part of NSA suite B or CNSA.

Outside of Weierstrass curves, Mbed TLS currently also supports Curve25519 and Curve448. These aren't listed in the X.509 profile since they aren't usable for signatures. For TLS, I propose to switch the default to the same set of Weierstrass curves as the new default X.509 profile.
