### ISSUE TITLE
mbed TLS 2.3.0 - mbedtls_x509_get_sig() updating sig->tag incorrectly

### ISSUE THREAD

**Issue by subramanyam-c** [ARMmbed/mbedtls#622]
1. mbedtls_x509_get_sig() function updating output parameter "sig".

2. sig->tag need to be updated when "mbedtls_asn1_get_bitstring_null()" function returns "0" only .
 
3. updation of sig->tag = **p; statement need to be moved after checking of mbedtls_asn1_get_bitstring_null().

For reference,fix should be like below :

int mbedtls_x509_get_sig( unsigned char **p, const unsigned char *end, mbedtls_x509_buf *sig )
{
    int ret;
    size_t len;

    if( ( end - *p ) < 1 )
        return( MBEDTLS_ERR_X509_INVALID_SIGNATURE +
                MBEDTLS_ERR_ASN1_OUT_OF_DATA );

    sig->tag = **p; //**This line need to be removed**

    if( ( ret = mbedtls_asn1_get_bitstring_null( p, end, &len ) ) != 0 )
        return( MBEDTLS_ERR_X509_INVALID_SIGNATURE + ret );

    sig->tag = **p; //**This line need to be added for fix..**

    sig->len = len;
    sig->p = *p;

    *p += len;

    return( 0 );
}

**Comment by andresag01** [comment]
Thank you for your report. Based on your triage, it does appear that a fix is required because the `sig` data structure should not be updated if there is an error. However, after careful inspection of the documentation and the code in question, I think the proposed changes will introduce a problem. This is because the documentation for `mbedtls_asn1_get_bitstring()` states that:

```
Updates the pointer to immediately behind the full tag. 
```

After the `if` statement `*p` points to the actual tag string instead of the ASN1 type. In other words, applying the proposed fix could potentially set `sig->tag` to some value that is not an integer representing an ASN1 type, which is what `sig->tag` is meant to store (see documentation for `struct mbedtls_asn1_buf` in `mbedlts/asn1.h`).

Finally, I do consider that `sig` should not be updated if there is an error. I have created a PR (https://github.com/ARMmbed/mbedtls/pull/623) that introduces a temporary `int tag_type` variable that remembers the ASN1 type. Then, if the check succeeds, the value can be assigned to `sig->tag`.

**Comment by subramanyam-c** [comment]
[mbedtls_x509_get_sig- explanation.docx](https://github.com/ARMmbed/mbedtls/files/481758/mbedtls_x509_get_sig-.explanation.docx)
Please see the comments in my attached document

**Comment by andresag01** [comment]
Thanks for your response, but unfortunately due to our security policies, I'm unable to open your file. Would it be possible for you to reattach your file in markdown or a plain text file or something similar?

I apologise for any inconvenience.

**Comment by subramanyam-c** [comment]
[mbedtls_x509_get_sig- explanation.pdf](https://github.com/ARMmbed/mbedtls/files/482102/mbedtls_x509_get_sig-.explanation.pdf)
I attached pdf file or same content pasted on below....
30 0A 
        06 08 2A 86 48 CE 3D 04 03 02 //ecdsa-with-SHA256 - 1.2.840.10045.4.3.2
        //Signature
        03 49 00  
                **_30 46 02 21 00 81 F0 7C 85 B7 7B BB E8 B0 92
                60 D5 20 CC EA A2 68 7F 90 FA F0 2C C3 11 4F 3F
                F0 E9 87 C2 0F 60 02 21 00 86 F4 74 8C 34 45 B3
                61 1B AC 20 BD 2C 4D 49 16 64 0A 6C 2D 71 92 04 
                8E 7C F4 84 B2 56 E5 EF 66_**
                
The above example is one of the ECDSA with sha 256 signature data.

I actually understood, the caller who uses mbedtls_x509_get_sig() expecting the “sig” information should be Bold highlighted italic data and this way can store signature data(TLV).
Sig->Tag = 0x30;
Sig->len = 0x46;
Sig->p should point to the address of “0x02” location.
Let me know whether my understanding is correct or not.
**_One more thing I want say, mbedtls_x509_get_sig() function inside it is using mbedtls_asn1_get_bitstring_null()  not mbedtls_asn1_get_bitstring()._**

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-985

**Comment by andresag01** [comment]
I believe your understanding is correct. I have not checked the correctness of the raw hex data you have posted though. `mbedtls_x509_get_sig()` accepts a pointer to where the information to be parsed is stored. Reading the source code, it appears that the first byte should be the tag type which will be stored in `sig->tag`, the second byte is the length and from the third on is the actual data. Internally, `mbedtls_asn1_get_bitstring_null()` is called, which eventually calls `mbedtls_asn1_get_tag()` (extracts the first byte) and `mbedtls_asn1_get_len()` (extracts the second byte).

**Comment by sbutcher-arm** [comment]
Fixed in PR #623 and backported to mbedtls-2.1 and mbedtls-1.3. Issue can now be closed.
