### ISSUE TITLE
MBEDTLS_PSA_CRYPTO_STORAGE_C include "crypto_se_driver.h" which is deprecated?

### ISSUE THREAD

**Issue by VitSolcikNXP** [ARMmbed/mbedtls#6267]
Hi!

Based on current mbedtls_config.h present in MbedTLS 3.2.1 release, user is supposed to not use MBEDTLS_PSA_CRYPTO_SE_C as it is deprecated. However after enabling MBEDTLS_PSA_CRYPTO_STORAGE_C, it is included in psa_crypto_storage.h.

Include path looks like this:
psa_crypto_storage.c :
#if defined(MBEDTLS_PSA_CRYPTO_STORAGE_C)
#include "psa_crypto_storage.h"

psa_crypto_storage.h :
#include "psa/crypto_se_driver.h"

Currently I am interested in implementing PSA crypto driver that is supposed to handle opaque persistent keys, so I am evaluating MbedTLS PSA capability and which way to go. Any guide on this subject is more than welcome.

Thanks
VS

**Comment by gilles-peskine-arm** [comment]
It's quite possible that `#include "psa/crypto_se_driver.h"` is only needed when `MBEDTLS_PSA_CRYPTO_SE_C` is enabled. But we usually include headers unconditionally, since including unnecessary headers is harmless whereas adding guards around include directives adds clutter.

The documentation on drivers is in the Mbed TLS documentation tree: [driver interface](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/proposed/psa-driver-interface.md), [driver developer guide](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/proposed/psa-driver-developer-guide.md), [driver integration guide](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/proposed/psa-driver-integration-guide.md). I'm afraid both the implementation and the documentation are works in progress and still incomplete. Nonetheless, there are production implementations of the parts that are implemented.

Mbed TLS currently ships with a sample implementation of mock drivers that we use for testing (code guarded by `PSA_CRYPTO_DRIVER_TEST`). A good starting point for implementing an opaque driver would be to replace the `mbedtls_test_opaque_xxx()` calls by calls to your driver. Since the documentation is very incomplete, and not all features in the specification are implemented yet, please don't hesitate to ask if you run into difficulties.

For opaque persistent keys, if the keys are stored in wrapped form outside the secure element, this is supported in Mbed TLS for production. If the keys are stored inside the secure element, this is not yet supported for production because the implementation is not resilient: if the device loses power during a key creation or key destruction operation, it's possible to end up with a key in the secure element that's not visible through the API, or conversely with a key that isn't actually present in the secure element.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because we don't consider a header inclusion to be a bug. For support about Mbed TLS (including the driver interface), please use the [Mbed TLS mailing list](https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/).
