### ISSUE TITLE
Function declarations not conditionally compiled

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/mbedtls#660]
mbed TLS has compile-time options such as `MBEDTLS_SSL_TLS_C` that can be used to conditionally enable/disable library functionality. The problem is that some of these options remove the implementation source code in `library/*.c`, but not the declarations in `include/mbedtls/*.h`. This causes issues when building applications with compilers such as IAR and armcc because the linkers want to see both declaration and implementation even though that functionality will never be used.

**Comment by andresag01** [comment]
@sbutcher-arm @c1728p9

**Comment by kjbracey-arm** [comment]
The issue is not declarations without definitions exactly - that doesn't generate the linker problem on its own.

The linker problem arises because those functions /are/ actually being called. Albeit from code that is not called itself.

The Gnu linker lets you get away with that - calling non-existent functions from unused functions. ARMCC and IAR do not, and they're right. The C standard requires that any identifier referenced in an expression in your program must have exactly one definition.

If this code referencing SSL were linked as a library (as originally intended) there would be no issue - that code is not referenced itself, so it wouldn't be pulled in, so the lack of SSL would not be a problem.

But in mbed, every object file in the tree is built, and is part of the program, and hence subject to that "everything used in an expression must have a definition" rule.

Removing the declarations will help catch the error earlier - it will show up on both GCC and other tools then, so is worth doing.

**Comment by andresag01** [comment]
@kjbracey-arm: I agree with what you say, but I think from the mbed TLS's point of view the problem arises from the fact that we have declarations that are not conditionally compiled out when they should. And that is exactly what I want to flag here.

The particular problem described in the issues quoted is one of the effects, and I consider that instead of giving a linker problem with ARMCC and IAR, it should fail with all compilers if you have references (even unused ones) to mbed TLS functionality that is not available. Again, I think we are in agreement since you point out that:

```
Removing the declarations will help catch the error earlier - it will show up on both GCC and other tools then, so is worth doing.
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1056
