### ISSUE TITLE
cannot detect reliably expired/future CA  (since 2.3.0)

### ISSUE THREAD

**Issue by harmv** [ARMmbed/mbedtls#665]
I tried upgrading from 2.2.0 to 2.4.0 and I noticed a problem was introduced. (It got introduced in 2.3.0 see below for the exact commit.)

I use the method `mbedtls_ssl_get_verify_result()` to evaluate if I can trust a server certificate or not.
In my application have an option to ignore  the problem of expired certificate. (plain cert or CA certificate)

So I want to detect that
1. the CA is expired  
2. the server certificate is perfectly valid signed by the CA

This worked perfectly before, i could use `mbedtls_ssl_get_verify_result()` and check for the `MBEDTLS_X509_BADCERT_EXPIRED` bit. (and the absence of the `MBEDTLS_X509_BADCERT_NOT_TRUSTED` bit !!)

Since 2.3.0  an expired CA will (besides setting the `MBEDTLS_X509_BADCERT_EXPIRED` bit) also set the `MBEDTLS_X509_BADCERT_NOT_TRUSTED` bit.

Q:why is this a problem?
A: because I want to distinguish between a correctly signed server certificate (be it expired), and an **invalidly** signed certificate. 
I can no longer determine If I can trust the server certificate.  
I cannot check for both bits, as those will be set too if there is really a rogue server certificate.
### steps to reproduce
1. Have a server cert and CA certificate that are expired.
   (CA has signed the server certificate)
2. connect and call `mbedtls_ssl_get_verify_result()`
### result

`mbedtls_ssl_get_verify_result()`  sets both bits `MBEDTLS_X509_BADCERT_EXPIRED` and `MBEDTLS_X509_BADCERT_NOT_TRUSTED`. 
### expected result

Only the bit `MBEDTLS_X509_BADCERT_EXPIRED` is set, but _not_ the bit `MBEDTLS_X509_BADCERT_NOT_TRUSTED`.
### notes

The same problem exists when certificates (both server as CA) are not yet valid (`MBEDTLS_X509_BADCERT_FUTURE`)
Think of an embedded system that gets its date reset to 1970 (due to a software problem). And that system wants to explicitly allow  'future' certificates. but... _still_ wants to check if the server certificate was properly signed by the CA.
### version

This (regression) is caused by commit  b437b4b1  (Feb 19 2016 X509: Fix bug triggered by future CA among trusted)

**Comment by sbutcher-arm** [comment]
This looks like an unintended change to the interface. Thanks for the bug report. We'll look into it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1071

**Comment by NWilson** [comment]
:( The cert chain verification code is somewhat hard to read - there are three functions that are copy-and-paste duplicates of each other (check-leaf-cert/check-intermediate/check-top-cert). But sadly there are minor differences that are hard to spot, and when you have spotted them, it's hard to understand whether the changes are intentional or not. I've had a PR open for around a year now that consolidates the checking into a single routine (making the checking code 66% shorter) - I think it would really help comprehension, since we've had at least three/four bugs in that code in the last year.

On a side note, you should probably be careful about your expectations regarding CA cert expiry. OpenSSL/Java/GnuTLS have different conventions on how expired CA certs should be treated - and there's no obvious "right" answer. The CA certs are the ones you have told the application are "trusted", so really it's up to you to pick your CA certs correctly. I'd argue it's completely within the rights of a library to accept those CA certs and not check their validity at all. If you really care about expiry for the CA certs, you should be careful when you build the trusted list. Most CA certs on the public internet (those in browser & OS trust stores) have effectively indefinite lifetime, or "nominal" expiry dates around 2040 or later.

**Comment by andresag01** [comment]
This issue is related to https://github.com/ARMmbed/mbedtls/issues/561.

**Comment by sbutcher-arm** [comment]
Fixed, pending release.
