### ISSUE TITLE
Need to use mbedtls_time() instead of time()

### ISSUE THREAD

**Issue by wariua** [ARMmbed/mbedtls#666]
`mbedtls_ssl_cache_set()` in ssl_cache.c calls `time()` while `mbedtls_ssl_cache_get()` correctly calls `mbedtls_time()`. This may result in a link error when `MBEDTLS_PLATFORM_TIME_MACRO` is used.

**Comment by sbutcher-arm** [comment]
Thanks for the bug report!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1070

**Comment by sbutcher-arm** [comment]
This has now been fixed with commit a55e084, which has been pushed to the private `development` branch, pending release.

Thanks to @AntonBikineev and @OverDrewk, but unfortunately we have a policy of not merging contributions without a CLA, and although this is trivial I couldn't take your fixes. So instead, I've fixed the issue myself, rather than ask for CLA's which would be more work than this very simple fix. Regardless, thank you both for your contributions and support of the project.

This issue can now be closed.
