### ISSUE TITLE
Support port unification

### ISSUE THREAD

**Issue by nuuman** [ARMmbed/mbedtls#692]
An increasing number of server supports regular traffic and SSL traffic on the same port (especially prevalent in the Java space)

This means, detect SSL hello packet, then move to SSL for that client.

Would this be hard to implement? I suppose you need to put the hello packet back on the "read queue" so that the ssl api starts with the hello packet.

Ideas?

**Comment by NWilson** [comment]
That should be easy enough to do using the existing API. mbedTLS has no "read queue" or notion of I/O at all, it simply has read & write callbacks, so you can feed mbedTLS data from the network and take data in any way you choose.

An application using mbedTLS will need to have a networking layer with event notifications or event dispatch, and then call mbedtls_ssl_read to poke mbedTLS to consume some data from the callback. If you get an error consuming the handshake, you can clean up the SSL context and hand the data off as a raw TCP stream.

mbedTLS doesn't gobble up data - it's your application-provided callback that advances the read buffer, so you should be able to rewind your own buffer.

**Comment by nuuman** [comment]
@NWilson thanks!

**Comment by sbutcher-arm** [comment]
As @NWilson has pointed out, this is better handled by the application software that uses mbed TLS rather than mbed TLS itself.

As this is a live discussion, I won't close it just yet, but as a feature request - I don't see there's anything we need to implement here (although, as ever we're open minded if someone wants to convince us otherwise).

**Comment by nuuman** [comment]
>  I don't see there's  anything we need to implement here

I believe I agree with this. But it's still unclear to me how I use raw sockets (berkeley sockets) and mbedtls_net_accept, etc, at the same time. That is... how to move from raw tcp to SSL when I notice the hello packet (or the other way around)

I'd love to get some input on this.

**Comment by NWilson** [comment]
For anything this complicated, you can't really use the mbedTLS "_net_"
functions (or at least, I wouldn't). In fact, for a typical desktop
application with an event loop, I personally wouldn't find very useful,
since you'll be using I/O which integrates with your existing event loop.

For port unification, you'd have your own I/O callbacks, with your own
buffered I/O streams. I'd need to know more about your application to offer
more specific ideas - if you're writing a plain C application from scratch
(eg UNIX daemon) you'd have quite a bit of code to write up-front; if
you're writing a Qt desktop application, you'd be using a QTcpSocket, which
integrates easily with mbedTLS, etc...


-----
Nicholas Wilson: nicholas@nicholaswilson.me.uk
Site and blog: www.nicholaswilson.me.uk
29 Beales Way, CB4 2PW
07845 182898

**Comment by sbutcher-arm** [comment]
I recommend you post to the [mbed TLS discussion board](https://tls.mbed.org/discussions) if you want further help or advice. The mbed TLS development team regularly participates in discussions, and more people will see your question than here.

**Comment by nuuman** [comment]
Thanks for the input guys!
