### ISSUE TITLE
CMAC calculation is wrong when compared with Openssl

### ISSUE THREAD

**Issue by saratchandraprasadg** [ARMmbed/mbedtls#705]
Here is the test code.
#include "stdio.h"
#include "stdlib.h"
#include "string.h"

#include "openssl/evp.h"
#include "openssl/cmac.h"

#include "mbedtls/cmac.h"
#include "mbedtls/cipher.h"

unsigned char key[16]={0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
int main()
{
	unsigned char m[100],m_len=32;
	unsigned char out[16],out1[16],out2[16];
	size_t d_len;
	int i,ret;
	mbedtls_cipher_context_t m_ctx;	
	const mbedtls_cipher_info_t *cipher_info;	
	
	
	CMAC_CTX *ctx;
	ctx=CMAC_CTX_new();
	if(ctx==NULL)
	{
		printf("\nCreation of ctx is failed");
	}
	memset(m,'X',32);
	CMAC_Init(ctx,key,16,EVP_aes_128_cbc(),NULL);
	CMAC_Update(ctx,m,m_len);
	CMAC_Final(ctx,out,&d_len);
	printf("\nLength is %d\n",(int)d_len);
	for(i=0;i<d_len;i++)
	{
		printf("%x ",out[i]);
	}
	
memset(m,'X',32);
	cipher_info = mbedtls_cipher_info_from_type( MBEDTLS_CIPHER_AES_128_CBC );

	if(cipher_info==NULL)
		printf("\nmbedtls_cipher_info_from_type failed");
	
	mbedtls_cipher_init(&m_ctx);
	
	ret=mbedtls_cipher_setup( &m_ctx, cipher_info );
	 printf("\n mbedtls_cipher_setup returned %d %d",ret, m_ctx.cipher_info->type);
	
	
			
	ret=mbedtls_cipher_cmac_starts(&m_ctx,key,128);
    printf("\n mbedtls_cipher_cmac_starts returned %d",ret);

	ret= mbedtls_cipher_cmac_update(&m_ctx, m,m_len);
	 printf("\n mbedtls_cipher_cmac_update returned %d",ret);

	ret=mbedtls_cipher_cmac_finish(&m_ctx,out1);
          printf("\n mbedtls_cipher_cmac_starts returned %d",ret);
	d_len=16;	
	printf("\nLength is %d\n",(int)d_len);
	for(i=0;i<d_len;i++)
	{
		printf("%x ",out1[i]);
	}

	return 0;
	
}

**Comment by bmurray7** [comment]
CMAC requires an ECB cipher, not an CBC cipher.  Currently, `mbedtls_cipher_cmac_starts` does not check cipher type.

**Comment by saratchandraprasadg** [comment]
Hi,
Thank you, it solved my issue. But as CMAC(a.k.a OMAC1) uses AES in CBC
mode, may I know why it is been giving ECB cipher as a naming convention.


Regards,
Sarat G

**Comment by saratchandraprasadg** [comment]
Had a look into mbedtls_cipher_cmac_update and mbedtls_cipher_update and
got how CMAC is implemented, that's fine. So may be if there is a check in
mbedtls_cipher_cmac_starts we can either use ECB or CBC for CMAC
calculation. Is that right?

Thank You.

Regards,
Sarat G

**Comment by sbutcher-arm** [comment]
Hi @saratchandraprasadg, and thank you for the interest in mbed TLS!

I'm afraid I don't consider there to be a bug here. As has already been discussed, the cipher type needs to be AES ECB.

As you can see in [`cmac.c` line 218](https://github.com/ARMmbed/mbedtls/blob/development/library/cmac.c#L218) we actually have a runtime check for this, but it doesn't look like the error was caught in your own code because you're not checking the return value of `mbedtls_cipher_cmac_starts()`.

I think this could be better documented so I have created Pull Request #723. I hope this helps future users.

Given this is not an issue for us, I'm closing the defect. If you disagree in anyway, please feel free to reply.

**Comment by saratchandraprasadg** [comment]
Hi,
Earlier I just got confused with the usage of ECB for computing CMAC. But
after looking into the i was understand that it was not a bug. Please close
this ticket.

Thank You.
