### ISSUE TITLE
Getting MBEDTLS_ERR_RSA_PRIVATE_FAILED error

### ISSUE THREAD

**Issue by Astomat** [ARMmbed/mbedtls#755]
Hello,
I get MBEDTLS_ERR_RSA_PRIVATE_FAILED (0x4300) error during the negotiation.
This happens only when compiling the lib on MIPs.
Please advise.

Thanks,
Astomat

**Comment by guidovranken** [comment]
Which version are you using? Using any nonstandard settings or compiler flags? Does any test fail if you type ```make test``` ?

**Comment by Astomat** [comment]
The version is: 2.4.0.
We didn't change any compiler flags. We use MIPs gcc/sysroot in order to build mbedtls and our code.
No changed made in config.h.
All tests pass (make test).
The same code works fine on linux/windows (x86).
On MIPs, it compiles and runs, but when connecting it gives MBEDTLS_ERR_RSA_PRIVATE_FAILED (0x4300) during negotiation.

Thanks,
Astomat.

**Comment by sbutcher-arm** [comment]
Hi @Astomat. Are you still suffering from this problem? I see some discussion on the [mbed TLS forum](https://tls.mbed.org/discussions/generic/0x7200-error) which suggests you may have made more progress, and this isn't a library issue. 

At the moment, I'm not sure there's a bug to fix.

**Comment by RonEld** [comment]
HI Astomat,
Since the issue you are encountering happens only on MIPS, this issue is platform specific.
The only location in mbedTLS which is platform specific that I could think might affect the RSA private key handling is in `bn_mul.h`.
I suggest you try disabling the MIPS assembly code there, to see if it's related to this code segment, and let the code fall through to the C code implementation.
 
Regards
Mbed TLS team member
Ron

**Comment by RonEld** [comment]
This issue is closed since the question was answered.
If you are not happy with the answer, please reopen
