### ISSUE TITLE
PK: try cleaning up pkparse/pkwrite

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#7747]
Those files are becoming quite complex with multiple cases for how ECC keys are stored, on top of the initial complexity of support both RSA and ECC with multiple formats.

This task is to try identifying opportunities for simplifications / readability improvements, and do it.

**Comment by gilles-peskine-arm** [comment]
We're working on an equivalent PSA API. When we implement it, it'll help if we can reuse parts of the code from pkparse/pkwrite. At that point we will need the kind of better structure that this issue is about. For me the most obvious thing is to split big functions like `mbedtls_pk_parse_key`. Each time I need to understand exactly how a particular input gets routed, I get a headache.

**Comment by valeriosetti** [comment]
@mpg Since https://github.com/Mbed-TLS/mbedtls/pull/7863 was merged, I think you can now start working on this without any conflict with other ongoing PRs

**Comment by mpg** [comment]
Split into two tasks, as after working on it a bit, it looks bigger than an M: #7994 + #7995.
