### ISSUE TITLE
Mutexing of HW acceleration

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/mbedtls#863]
@yanesca @sbutcher-arm Following our conversation last week, I'd like to ask that you remove the mutexing from the mbedTLS ECP abstraction layer. For one because our devices (Silicon Labs) contain multiple accelerators (and so our ECC throughput would be cut in half by doing the mutexing inside of the mbedTLS library), but also because this is inconsistent with how hardware acceleration for AES and SHA operate today.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1342

**Comment by screamerbg** [comment]
@sbutcher-arm Any comment on this?

**Comment by sbutcher-arm** [comment]
Hi @screamerbg,

Just to clarify the problem, our position, and what we're going to do about it, so we can be a bit more transparent.

mbed TLS supports concurrency where different contexts are used. That is to say, if you have two threads, and they use different contexts, then they should be thread safe. This is discussed in the ['Thread Safety and Multi Threading: concurrency issues'](https://tls.mbed.org/kb/development/thread-safety-and-multi-threading) knowledgebase article.

However, within the mbed OS HAL (and as an extension of that, the mbed TLS acceleration driver code), there is no thread safety, and it's the responsibility of callers. This has been stated by @0xc0170 and
@sg- several times.

In the case of mbed TLS *that* means mbed TLS must take responsibility for thread safety, and must implement sufficient concurrency primitives as to be thread safe. Hence the mutex.

However - it's obviously the case that it isn't always necessary to block all access to all accelerating hardware - as in the case of Silicon Labs, it actually impedes performance. Therefore we recognise this is a problem that needs to be resolved and we accept this is a bug or necessary enhancement.

But ... what makes this slightly simpler, and means we don't have to address this immediately, is that threading isn't yet fully supported by mbed TLS in mbed OS and is [actually disabled](https://github.com/ARMmbed/mbed-os/blob/5.4.2/features/mbedtls/inc/mbedtls/config.h#L2340) out of the box.

This is something we plan to change - but it means currently the mutex shouldn't be a problem, and the problem is actually that we don't fully support concurrency yet.

**Comment by stevew817** [comment]
@screamerbg @sbutcher-arm 

I just want to point out that while, yes, in mbed OS the mutex is disabled by default (which is a separate problem, since there's no way to tell what'll happen if someone decides to do crypto from multiple threads in mbedOS), we also ship mbed TLS as a cryptographic library separately. In those cases, we do enable threading, as we should, when running with an RTOS. Then the mutex does become a problem, and we need to edit mbed TLS-provided code to remove it in our release.

Is it stated anywhere that mbed TLS acceleration drivers will always run inside of mbed OS, or that mbed TLS will only support mbed OS as a supplier of acceleration drivers? I think it is a mistake to look at mbed TLS acceleration APIs as a direct mbed OS HAL API. Just like the TRNG driver today, mbed OS can perfectly have a 'adaptation layer' to make the calls thread-safe.

Again, neither the AES nor the SHA acceleration APIs currently do mutexing, so why should ECP be any different?

**Comment by sbutcher-arm** [comment]
Hi @stevew817 

Thanks for the feedback. Well, as I said above, we plan to address this, and fix the mutex for you. 

> Is it stated anywhere that mbed TLS acceleration drivers will always run inside of mbed OS, or that mbed TLS will only support mbed OS as a supplier of acceleration drivers? I think it is a mistake to look at mbed TLS acceleration APIs as a direct mbed OS HAL API.

At the moment, we have no plans to distribute hardware acceleration drivers with mbed TLS in it's standalone form - only when bundled with mbed OS. 

The mbed TLS interface for providing acceleration is intended for *all* users, whether they use mbed OS or not. So, yes, it is intended for users of mbed TLS outside of mbed OS.

> Again, neither the AES nor the SHA acceleration APIs currently do mutexing, so why should ECP be any different?

As stated above - the mutex used in the ECP module will likely be removed or changed in a way that you can accept. As and when we push a pull request, I'll note to cc you on it so you can support the review.

**Comment by yanesca** [comment]
Hi @stevew817,

I have created a PR to remove the mutexes: #980 . Could you please have a look at it and provide some feedback?

**Comment by sbutcher-arm** [comment]
Issue resolved with PR #980.
