### ISSUE TITLE
MBEDTLS_ERR_THREADING_MUTEX_ERROR consistency

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#869]
There is inconsistency between returned error of mbedtls_mutex_lock and mbedtls_mutex_unlock within mbed TLS.
most functions that call mbedtls_mutex_lock, return the mutex return code, while most functions that call mbedtls_mutex_unlock, return MBEDTLS_ERR_THREADING_MUTEX_ERROR.
Raised  by Anton Lavrentiev

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1317

**Comment by alavrentiev** [comment]
Hi, I actually pointed out that code in x509.c should return the mutex error as returned by the callback
rather than replacing it with a generic error, that is:

    if( mbedtls_mutex_lock( &mbedtls_threading_gmtime_mutex ) != 0 )
        return( MBEDTLS_ERR_THREADING_MUTEX_ERROR );

should be

    if( (ret = mbedtls_mutex_lock( &mbedtls_threading_gmtime_mutex )) != 0 )
        return( ret );

and so with the _unlock calls within that module, just as it is done everywhere else throughout the library.

Also, I noticed in 2.4.2, ssl_cookie.c uses the lock/unlock inconsistently (dare I say incorrect), too:

    if( ( ret = mbedtls_mutex_lock( &ctx->mutex ) ) != 0 )
        return( MBEDTLS_ERR_SSL_INTERNAL_ERROR + ret );
...
    if( mbedtls_mutex_unlock( &ctx->mutex ) != 0 )
        return( MBEDTLS_ERR_SSL_INTERNAL_ERROR +
                MBEDTLS_ERR_THREADING_MUTEX_ERROR );

The first "if" should return just "ret", not a sum;  the second if should capture the return code and pass it through,
not return a sum of two errors, just shown above, "return( ret );"

Unfortunately, I cannot edit the bug report myself.  I'd appreciate if you could add this clarification in there.

Thanks again,

Anton Lavrentiev
Contractor NIH/NLM/NCBI

**Comment by RonEld** [comment]
@alavrentiev Hi, you are correct, however after you rightfully pointed us to this issue, we deep dived for all occurrences of `mbedtls_mutex_lock` and `mbedtls_mutex_unlock` we noticed that most of `mbedtls_mutex_unlock` failures return `MBEDTLS_ERR_THREADING_MUTEX_ERROR` , like in x509.c , and most of '`mbedtls_mutex_lock` failures return the error code of the failure, as you mentioned. However, there are some locations, such as in `mbedtls_ssl_cache_get' , that failures return 1, and no other error code.
The purpose of this issue is to define what should be the correct behavior of this inconsistency

**Comment by alavrentiev** [comment]
We're using the MBEDTLS_THREADING_ALT implementation for the locks so expect to see the errors that our lock/unlock callbacks have actually returned.
