### ISSUE TITLE
error in mbedtls_rsa_rsaes_oaep_encrypt

### ISSUE THREAD

**Issue by IrootGeek** [ARMmbed/mbedtls#887]
i use mbedtls_rsa_rsaes_oaep_encrypt with the good param but i have 0x4080 error
 
MBEDTLS_ERR_RSA_BAD_INPUT_DATA  0x4080

/**
 * \brief          Perform a PKCS#1 v2.1 OAEP encryption (RSAES-OAEP-ENCRYPT)
 *
 * \param ctx      RSA context
 * \param f_rng    RNG function (Needed for padding and PKCS#1 v2.1 encoding
 *                               and MBEDTLS_RSA_PRIVATE)
 * \param p_rng    RNG parameter
 * \param mode     MBEDTLS_RSA_PUBLIC or MBEDTLS_RSA_PRIVATE
 * \param label    buffer holding the custom label to use
 * \param label_len contains the label length
 * \param ilen     contains the plaintext length
 * \param input    buffer holding the data to be encrypted
 * \param output   buffer that will hold the ciphertext
 *
 * \return         0 if successful, or an MBEDTLS_ERR_RSA_XXX error code
 *
 * \note           The output buffer must be as large as the size
 *                 of ctx->N (eg. 128 bytes if RSA-1024 is used).
 */
int mbedtls_rsa_rsaes_oaep_encrypt( mbedtls_rsa_context *ctx,
                            int (*f_rng)(void *, unsigned char *, size_t),
                            void *p_rng,
                            int mode,
                            const unsigned char *label, size_t label_len,
                            size_t ilen,
                            const unsigned char *input,
                            unsigned char *output );
How to use this function?
Thanks,

**Comment by RonEld** [comment]
Hi @IrootGeek ,  
Please follow the example in [rsa_encrypt](https://github.com/ARMmbed/mbedtls/blob/development/programs/pkey/rsa_encrypt.c) which calls the wrapper code for rsa encryption (`mbedtls_rsa_pkcs1_encrypt`), but you can change it to `mbedtls_rsa_rsaes_oaep_encrypt`. If you are using private key, remember to load the private key instead of public key. (example in [rsa_decrypt](https://github.com/ARMmbed/mbedtls/blob/development/programs/pkey/rsa_decrypt.c)  ). In addition, remember to set the correct information in `mbedtls_rsa_init` ( `MBEDTLS_RSA_PKCS_V21` and relevant hash id)

**Comment by IrootGeek** [comment]
Hi @RonEld,
Yes i follow the example in rsa_encrypt, it's same to rsa_pkcs1_oaep, i just init rsa and use padding  MBEDTLS_RSA_PKCS_V21 and hash id, the function works for me,
Thank you, :+1:
