### ISSUE TITLE
Makefiles require GNU make

### ISSUE THREAD

**Issue by gilles-peskine-arm** [ARMmbed/mbedtls#967]
The [README](https://github.com/ARMmbed/mbedtls#make) claims that “We intentionally only use the minimum of Make functionality”. I think we make this statement in the knowledge base as well. But in fact the makefiles require GNU make for conditional processing (`ifdef` and `ifndef` directives).

The rule that we are actually following is not to depend on tools *other* than (GNU) make and a C compiler — the commands can be executed by `cmd` on Windows, they don't require a Unix-style shell and utilities.

We should either correct the documentation or rework the makefiles.

**Comment by sbutcher-arm** [comment]
Hi @gilles-peskine-arm,

I'm not sure about your statement "the makefiles require GNU make for conditional processing (`ifdef` and `ifndef` directives)".

`ifdef` and `ifndef` may not be POSIX (I checked [here](http://pubs.opengroup.org/onlinepubs/009695399/utilities/make.html)), but they are supported in BSD/Berkeley make, which I found documented [here](https://www.freebsd.org/cgi/man.cgi?make(1)), and the same documentation suggests they're in System V, and I know they were in older PC based Make's, such as Borland Turbo C++. 

We do build and support FreeBSD alongside Linux and Windows, although frustratingly, it looks like our CI system requires GNU Make on FreeBSD. Why, I do not know.

I always imagined that the Makefile may also be used by some of the implementations of Make which get shipped with compilers for embedded platforms. Not just GNU.

However - being vague and non-specific about what we support doesn't help with testing, nor gives much promise to users. I don't mind us being more specific about what we support and what we don't support, but I don't want to orphan any existing users.

I think someone should check how well we build on FreeBSD without GNU. @mazimkhan - Can you confirm please?

And then maybe we should state what we test with, rather than what is required.

**Comment by gilles-peskine-arm** [comment]
@sbutcher-arm BSD make does not have `ifdef`, it has `.ifdef`. I don't remember anything like this in System V; Solaris doesn't have either. I don't know of any tricks to use make this portable, it comes pretty early in the parsing. Seems that [Borland has `!ifdef`](https://www.dmi.unict.it/~tramonta/lessons/so/makedoc.pdf), just to keep developers on their toes. As far as I'm aware, only GNU make has `ifdef` (with no leading punctuation).

**Comment by mazimkhan** [comment]
FreeBSD has pmake (default make) and gmake (GNU make). If I try to build with default make command then it throws errors pretty much from all Makefiles. gmake works fine. Just as you said CI requires GNU make. That is what we really support.

**Comment by sbutcher-arm** [comment]
Ok - so `pmake` chokes on our Makefile, as if to make Gilles's point, and I guess in a very Unix-like way, each `make` has implemented the same feature with very slightly different syntax.

To rework the Makefiles to target different implementations of `make` we really need to know what we're targeting, and I don't think there's any demand for anything other than GNU Make. Therefore - I guess I have to concede to Gilles's point that we should update the README.

What I will say is though - we might only support GNU Make, but we still need to be cross-platform, and it should build happily on Linux, BSD and Windows.

**Comment by sbutcher-arm** [comment]
The `[README.md](https://github.com/ARMmbed/mbedtls/blob/development/README.md)` now explicitly states that GNU Make is required. I think that's explicit enough and answers the issue raised here.

Thus, closing this issue.
