### ISSUE TITLE
DTLS server demo doesn't work on all Windows platforms

### ISSUE THREAD

**Issue by Wizzard033** [ARMmbed/mbedtls#977]
Line 173 of dtls_server.c cannot use NULL in call to mbedtls_net_bind as 2nd argument
https://github.com/ARMmbed/mbedtls/blob/development/programs/ssl/dtls_server.c#L173

I've managed to fix my local copy by using "127.0.0.1" instead of NULL
https://tls.mbed.org/discussions/platform-specific/mbedtls-dtls-sample-on-windows-10

**Comment by RonEld** [comment]
Hi @Wizzard033 Thanks for raising this! Note that the sample applications are, as their name suggest, reference samples for users to look try, and not intended to work on all platforms. Having said that, since the issue is on Windows 10, it is highly reasonable that it should be updated.
We will look at what's the best approach for this issue, in order not to break backward compatibility, in addition of supporting future platforms.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1485

**Comment by RonEld** [comment]
According to https://github.com/ARMmbed/mbedtls/issues/859#issuecomment-387107720 , this issue reproduces also on Darwin Kernel Version 17.5.0

**Comment by catenacyber** [comment]
Yes : `mbedtls_net_accept` returned -74 because `connect( bind_ctx->fd, (struct sockaddr *) &client_addr, n )` returns an error with errno=EINVAL

There seems to be an explanation here https://patchwork.ozlabs.org/patch/744588/
If I understand, `connect` does not know which source address to use

**Comment by sbutcher-arm** [comment]
PR's #1627, #2041 and #2042 have fixed this issue, so it can now be closed.
