### ISSUE TITLE
Elliptic curve and MBEDTLS_ERR_SSL_BAD_HS_CLIENT_HELLO issue

### ISSUE THREAD

**Issue by aistodorescu** [ARMmbed/mbedtls#991]
When MBEDTLS_SSL_DTLS_HELLO_VERIFY is enabled and client wants to connect using an elliptic curve ciphersuite the second ClientHello gets dropped in ssl_parse_supported_elliptic_curves with MBEDTLS_ERR_SSL_BAD_HS_CLIENT_HELLO. The issue is caused because the pointer ssl->handshake->curves was already set by the first ClientHello parsing.
Commenting out this return code the handshake goes through.
Disabling the MBEDTLS_SSL_DTLS_HELLO_VERIFY on the server side makes the handshake successful.

**Comment by RonEld** [comment]
Hi @aistodorescu Thank you for raising this! We will look into it

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1503

**Comment by RonEld** [comment]
Hi @aistodorescu As mentioned in [ssl.h](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h#L2363):
~~~
 * \note           If DTLS is in use, then you may choose to handle
 *                 MBEDTLS_ERR_SSL_HELLO_VERIFY_REQUIRED specially for logging
 *                 purposes, as it is an expected return value rather than an
 *                 actual error, but you still need to reset/free the context.
~~~
This means, that if `MBEDTLS_SSL_DTLS_HELLO_VERIFY` is enabled, and you receive `MBEDTLS_ERR_SSL_HELLO_VERIFY_REQUIRED`, you should reset the context, and thus ` ssl->handshake->curves` would not be set.

**Comment by RonEld** [comment]
I believe the question was answered, therefore, closing it.
If you are not happy with answer, please reopen it.
